import React from 'react';
import * as Cycle from '../product/togetherCycleDepth.js';
import {CYCLE_FOOD_SOURCES} from '../product/togetherCycleFood.js';
import {CYCLE_IMAGERY_SOURCES} from '../product/togetherCycleImagery.js';
import * as Connection from '../product/togetherConnectionContent.js';
import {TOGETHER_RITUAL_SOURCES} from '../product/togetherRituals.js';
import {SKY_SOURCES} from '../product/skyContent.js';
import {SkyHelpIndex} from './skyHelpIndex.jsx';

export function AppSources({lang='cs',topic='obloha',trainingSources=[]}){
  const at=value=>Array.isArray(value)?value[lang==='en'?1:0]:typeof value==='object'?(value?.[lang]||value?.cs||''):value;
  const L=(cs,en)=>lang==='en'?en:cs;
  const links=items=><ul>{items.map(item=><li key={item.id||item.url}><a href={item.url} target="_blank" rel="noreferrer">{at(item.title)}</a></li>)}</ul>;
  const annotated=items=>items.map(item=><details key={item.id}><summary>{at(item.title)}</summary><p>{at(item.note)}</p>{links([item])}</details>);
  return <div className="tm-app-sources">
    <details open={topic==='muscles'}><summary>{L('Svalová mapa cviků','Exercise muscle map')}</summary><p>{L('Kresba a barevné oblasti jsou orientační anatomické schéma hlavních a vedlejších skupin uvedených u cviku. Hluboké svaly se promítají na povrch; překryv může pokračovat přes oblečení. Mapa neměří aktivaci konkrétního člověka. U mobility označuje zaměření pohybu. Chybějící nebo nejednoznačné přiřazení zůstává výslovně neurčené.','The drawing and coloured regions are an anatomical guide to the primary and secondary groups listed for the exercise. Deep muscles are projected onto the surface; overlays may continue over clothing. The map does not measure an individual person’s activation. For mobility, it shows the focus of the movement. Missing or ambiguous assignments remain explicitly unspecified.')}</p>{links([{title:'OpenStax · Muscles of the pectoral girdle and upper limbs',url:'https://openstax.org/books/anatomy-and-physiology-2e/pages/11-5-muscles-of-the-pectoral-girdle-and-upper-limbs'},{title:'OpenStax · Muscles of the pelvic girdle and lower limbs',url:'https://openstax.org/books/anatomy-and-physiology-2e/pages/11-6-appendicular-muscles-of-the-pelvic-girdle-and-lower-limbs'},{title:'AAOS · Foot and Ankle Conditioning Program',url:'https://orthoinfo.aaos.org/globalassets/pdfs/foot-and-ankle-conditioning-program---2025.pdf'},{title:'AAOS · Rotator Cuff and Shoulder Conditioning Program',url:'https://www.orthoinfo.org/recovery/rotator-cuff-and-shoulder-conditioning-program/'},{title:'ACE · Back exercise study',url:'https://contentcdn.eacefitness.com/April2018/ACE_BackExerStudy.pdf'}])}</details>
    <details open={topic==='obloha'}><summary>{L('Obloha: výpočty a tradice','Sky: calculations and traditions')}</summary>{SKY_SOURCES.map(item=><details key={item.id}><summary>{at(item.title)}</summary><p>{at(item.text)}</p>{links((item.links||[]).map(([title,url])=>({title,url})))}</details>)}<SkyHelpIndex lang={lang}/></details>
    <details open={topic==='cycle'}><summary>{L('Cyklus, tělo a jídlo','Cycle, body and food')}</summary>{(Cycle.CYCLE_METHOD_NOTES||[]).map((item,index)=>item.text?<details key={index}><summary>{at(item.title)}</summary><p>{at(item.text)}</p></details>:<p key={index}>{at(item)}</p>)}<details><summary>{L('Jídla: z čeho vychází jejich výběr','Meals: how they are selected')}</summary>{annotated(CYCLE_FOOD_SOURCES)}</details><details><summary>{L('Příběhy, rituály a spirály: prameny','Stories, rituals and spirals: sources')}</summary>{annotated(CYCLE_IMAGERY_SOURCES)}</details><details><summary>{L('Atlasová anatomie','Atlas anatomy')}</summary><p>{L('Obecná kresba dělohy vznikla pomocí generování obrazu a byla porovnána s výukovými prameny níže. Není klinicky recenzovanou ilustrací. Ve všech fázích používáme stejnou kresbu; zvýraznění označuje místo, nikoli měřenou tloušťku sliznice nebo aktivní vaječník. Text popisuje obvyklý průběh přirozeného cyklu.','The general uterus drawing was generated and compared with the educational sources below. It is not a clinically reviewed illustration. Every phase uses the same drawing; highlights locate structures rather than measured lining thickness or an active ovary. The text describes a typical natural cycle.')}</p>{links([{title:'OpenStax · Anatomy and Physiology of the Female Reproductive System',url:'https://openstax.org/books/anatomy-and-physiology/pages/27-2-anatomy-and-physiology-of-the-female-reproductive-system'},{title:'Cleveland Clinic · Cervical Mucus',url:'https://my.clevelandclinic.org/health/body/21957-cervical-mucus'},{title:'MedlinePlus · Menstruation',url:'https://medlineplus.gov/ency/article/002317.htm'}])}</details>{links(Cycle.CYCLE_DEPTH_SOURCES)}</details>
    <details open={topic==='together'}><summary>{L('Rozhovory a společné chvíle','Conversations and shared moments')}</summary>{(Connection.RELATIONSHIP_SOURCE_NOTES||[]).map((item,index)=><p key={index}>{at(item)}</p>)}{links([...TOGETHER_RITUAL_SOURCES,...(Connection.RELATIONSHIP_SOURCES||[])].filter((item,index,all)=>all.findIndex(other=>other.url===item.url)===index))}</details>
    {trainingSources.length>0&&<details open={topic==='training'}><summary>{L('Trénink a knihovna postupů','Training and the methods library')}</summary>{trainingSources.map(doc=><details key={doc.id}><summary>{at(doc.title)}</summary><p>{doc.author}</p>{doc.notes.map((note,index)=><details key={index}><summary>{at(note.title)}</summary><p>{at(note.text)}</p></details>)}<ul>{doc.sources.map((source,index)=><li key={index}>{at(source)}</li>)}</ul>{doc.assets?.length>0&&links(doc.assets)}</details>)}</details>}
    <details><summary>{L('Kalendář a synchronizace','Calendar and synchronization')}</summary><p>{L('Spolu používá oddělený kalendář vytvořený aplikací. Přenáší jen společné plány. Změny času nebo názvu z Googlu se vracejí jako návrh, který druhý člověk znovu potvrdí. Přístupový token zůstává pouze v paměti prohlížeče.','Together uses a separate app-created calendar and only transfers shared plans. Changes to time or title from Google return as a proposal for the other person to confirm. The access token stays only in browser memory.')}</p>{links([{title:'Google Calendar: incremental synchronization',url:'https://developers.google.com/workspace/calendar/api/guides/sync'},{title:'Google Identity: token model',url:'https://developers.google.com/identity/oauth2/web/guides/use-token-model'}])}</details>
  </div>;
}
