import React,{useState} from "react";
import {SKY_BODY_POINTS,SKY_ELEMENTS} from "../product/skyContent.js";
import {expectedSkyNostril,skyDateKey} from "../product/skyJournal.js";
import {ASTRO_PLANETS,ASTRO_ASPECTS} from "../product/togetherAstrologyEditorial.js";
import {ZODIAC} from "../product/togetherMoon.js";
import {SkyHeading,SkyHelp,SkyEmpty,skyTime} from "./skyUi.jsx";

const glyph={Rahu:"☊",Ketu:"☋",Saturn:"♄",lights:"☉ ☽"};
export const skyPosition=(planet,L)=>planet&&Number.isFinite(planet.longitude)?`${Math.floor(planet.degree??planet.longitude%30)}°${String(Math.floor(((planet.degree??planet.longitude%30)%1)*60)).padStart(2,"0")}′ ${L(...ZODIAC[planet.sign??Math.floor(planet.longitude/30)])}`:"—";
export function SkyBodyFigure({personal=false,onSelect,selected=null,lang="cs",dreamRegions=[]}){
  const L=(cs,en)=>lang==="en"?en:cs;
  return <svg className="sky-body-image" viewBox="0 0 300 430" fill="none" stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" role="img" aria-label={L("Symbolická mapa vadžrového těla","Symbolic vajra body map")}>
    <path d="M133 32c-12 11-13 35-4 49l4 12-2 12c-25 8-43 21-50 39-8 24-10 51-17 77-6 23-13 43-17 62-1 9 7 12 11 3l23-48 16-48c-1 39 6 57 12 75l-7 61-9 83c0 10 17 10 19 1l22-101 16-40 17 40 22 101c2 9 19 9 18-1l-9-83-7-61c6-18 13-36 12-75l16 48 23 48c4 9 12 6 11-3-4-19-11-39-17-62-7-26-9-53-17-77-7-18-25-31-50-39l-2-12 4-12c9-14 8-38-4-49-10-9-24-9-34 0Z" strokeWidth="1.3"/>
    <path d="M132 54c7-5 29-5 36 0M138 73c7 4 17 4 24 0M117 119c13 8 53 8 66 0M109 148c8 0 14 2 19 6m44 0c5-4 11-6 19-6M138 259c7 4 17 4 24 0" opacity=".35"/>
    <path d="M150 94V307" strokeWidth="1.8" opacity={personal?1:.35}/>
    <path d="M141 100c-17 35-17 59 2 83s-16 39-13 62 13 37 20 57M159 100c17 35 17 59-2 83s16 39 13 62-13 37-20 57" strokeWidth="1.1" opacity={personal?.65:.2}/>
    <circle cx="150" cy="244" r="13" opacity=".35"/><circle cx="150" cy="244" r="3" opacity=".6"/>
    {dreamRegions.map(region=><ellipse key={region} cx="150" cy={region==="upper"?105:region==="middle"?215:315} rx={region==="upper"?33:45} ry="43" fill="currentColor" fillOpacity=".09" strokeDasharray="2 5" opacity=".7"/>)}
    {personal&&onSelect&&SKY_BODY_POINTS.map(p=><g key={p.id} className="sky-body-point" role="button" tabIndex={0} aria-label={L(...p.name)} aria-pressed={selected===p.id} onClick={()=>onSelect(p.id)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();onSelect(p.id);}}}><circle cx={p.x} cy={p.y} r={p.id==="lights"?24:19}/><text x={p.x} y={p.y+6} textAnchor="middle">{glyph[p.id]}</text></g>)}
  </svg>;
}
export function SkyBodyPointDetail({id,natal,sky,lang="cs",onSettings}){
  const L=(cs,en)=>lang==="en"?en:cs,p=SKY_BODY_POINTS.find(v=>v.id===id),ids=id==="lights"?["Sun","Moon"]:[id];
  const birth=[...(natal?.planets||[]),...(natal?.nodes||[])],now=natal?.gochara||[...sky.planets,...(sky.nodes||[])];
  if(!p)return null;
  return <><p className="sky-lead">{L(...p.text)}</p>{ids.map(body=><div key={body} className="sky-record"><h4>{ASTRO_PLANETS[body]?L(...ASTRO_PLANETS[body].name):body}</h4><div className="sky-pair"><div><span className="sky-small">{L("Při narození","At birth")}</span><p className="sky-fact">{skyPosition(birth.find(v=>v.id===body),L)}</p></div><div><span className="sky-small">{L("Vybraný okamžik","Selected instant")}</span><p className="sky-fact">{skyPosition(now.find(v=>v.id===body),L)}</p></div></div></div>)}
    {!birth.length&&<button type="button" onClick={onSettings}>{L("Doplnit údaje narození","Add birth details")}</button>}
    {(natal?.transits||[]).filter(v=>ids.includes(v.natalPlanet)).map((v,i)=><p className="sky-small" key={i}>{ASTRO_PLANETS[v.planet]?L(...ASTRO_PLANETS[v.planet].name):v.planet} → {ASTRO_PLANETS[v.natalPlanet]?L(...ASTRO_PLANETS[v.natalPlanet].name):v.natalPlanet} · {ASTRO_ASPECTS[v.id]?L(...ASTRO_ASPECTS[v.id].name):`${v.angle}°`}{Number.isFinite(v.orb)?` · ${v.orb.toFixed(2)}°`:""}</p>)}
  </>;
}
export function SkyInnerWheel({internal,date,lang="cs",onOpen}){
  const L=(cs,en)=>lang==="en"?en:cs,segments=internal?.segments||[],current=typeof internal?.current==="number"?internal.current:internal?.current?.index!=null?internal.current.index-1:null;
  return <><SkyHeading id="T08" onOpen={onOpen} lang={lang}>{L("Vnitřní slunce","Inner sun")}</SkyHeading>{segments.length?<>
    <svg viewBox="0 0 240 240" className="sky-inner-wheel sky-clock" fill="none" stroke="currentColor" role="img" aria-label={`${L("Vnitřní úsek","Inner interval")} ${Number.isInteger(current)?current+1:"—"}`}>
      <circle cx="120" cy="120" r="101" opacity=".45"/>{segments.map((s,i)=>{const angle=(i-3)*Math.PI/6,mid=angle+Math.PI/12,next=angle+Math.PI/6;return <g key={i}>{i===current&&<path d={`M120 120L${120+101*Math.cos(angle)} ${120+101*Math.sin(angle)}A101 101 0 0 1 ${120+101*Math.cos(next)} ${120+101*Math.sin(next)}Z`} fill="currentColor" fillOpacity=".12" stroke="none"/>}<path d={`M${120+60*Math.cos(angle)} ${120+60*Math.sin(angle)}L${120+101*Math.cos(angle)} ${120+101*Math.sin(angle)}`} opacity=".45"/><text x={120+81*Math.cos(mid)} y={124+81*Math.sin(mid)} textAnchor="middle">{i+1}</text></g>;})}<circle cx="120" cy="120" r="44" opacity=".35"/><text x="120" y="116" textAnchor="middle" style={{fontSize:26}}>{Number.isInteger(current)?current+1:"—"}</text><text x="120" y="138" textAnchor="middle">1 800</text>
    </svg><p className="sky-model">{L("Model dvanácti úseků · 1 800 dechů v tradičním počtu","Twelve-interval model · 1,800 breaths in the traditional count")}</p><p className="sky-small" style={{textAlign:"center"}}>{L("Znamení a střídání dírek zatím nejsou ověřené.","Sign and nostril assignments are not verified yet.")}</p>
    <details><summary>{L("Průběh dvanácti úseků","The twelve intervals")}</summary>{segments.map((s,i)=><div className="sky-record" key={i}>{i+1}. · {skyTime(s.start,lang,date.timeZone)}–{skyTime(s.end,lang,date.timeZone)}{i===current?` · ${L("právě teď v mapě","current in the map")}`:""}</div>)}</details>
  </>:<SkyEmpty text={L("Pro tento den nejsou dostupné dva místní východy Slunce.","Two local sunrises are not available for this day.")}/>}</>;
}
export function SkyBody({sky,details,journal,update,ready,day,lang="cs",onOpen,onSettings,cycle}){
  const L=(cs,en)=>lang==="en"?en:cs,[side,setSide]=useState(null),[comfort,setComfort]=useState(false),[note,setNote]=useState(""),[dream,setDream]=useState(""),[regions,setRegions]=useState([]),[message,setMessage]=useState("");
  const zone=journal.settings.location.timeZone,personal=Boolean(details?.natal?.planets?.length),today=skyDateKey(Date.now(),zone);
  const dayRecords=journal.nostrils.filter(n=>skyDateKey(n.time,zone)===day),dayDreams=journal.dreams.filter(n=>skyDateKey(n.time,zone)===day);
  const saveObservation=()=>{if(!side||!ready)return;if(update(d=>({...d,nostrils:[...d.nostrils,{id:crypto.randomUUID(),time:Date.now(),side,comfort,note:note.trim().slice(0,500)}]}))){setMessage(L("Pozorování uložené pro dnešek.","Observation saved for today."));setNote("");}};
  const saveDream=()=>{if(!dream.trim()||!ready)return;if(update(d=>({...d,dreams:[...d.dreams,{id:crypto.randomUUID(),time:Date.now(),text:dream.trim().slice(0,8000),regions}]}))){setDream("");setRegions([]);setMessage(L("Sen uložený.","Dream saved."));}};
  return <>
    <SkyHeading id="T01" onOpen={onOpen} lang={lang}>{L("Dvě zrcadla, jeden střed","Two mirrors, one centre")}</SkyHeading>
    <div className="sky-body-layout"><SkyBodyFigure personal={personal} onSelect={id=>onOpen({kind:"body",id})} lang={lang}/><div>{personal?<><p>{L("Touha, karmický vítr, oheň a dvě světla. Čtyři vstupy do mapy podle podání tvého učitele.","Desire, karmic wind, fire and two lights. Four entries into the map in your teacher's account.")}</p><div className="sky-body-actions">{SKY_BODY_POINTS.map(p=><div key={p.id} style={{display:"flex",alignItems:"center",gap:4}}><button type="button" style={{flex:1}} onClick={()=>onOpen({kind:"body",id:p.id})}>{L(...p.name)}</button><SkyHelp id={p.help} onOpen={onOpen} lang={lang}/></div>)}</div></>:<SkyEmpty text={L("Doplň údaje narození a spoj svou výchozí oblohu s dnešním pohybem.","Add birth details to connect your starting sky with today's movement.")}><button type="button" onClick={onSettings}>{L("Doplnit narození","Add birth details")}</button></SkyEmpty>}</div></div>
    <div className="sky-links"><button type="button" onClick={()=>onOpen({kind:"elements"})}>{L("Šest prvků","Six elements")}</button><button type="button" onClick={()=>onOpen({kind:"help",id:"T07"})}>{L("Deset větrů","Ten winds")}</button><button type="button" onClick={()=>onOpen({kind:"help",id:"T13"})}>{L("La · životní síla","La · life force")}</button></div>
    <SkyInnerWheel internal={details?.internalDay} date={{timeZone:zone}} lang={lang} onOpen={onOpen}/>
    <SkyHeading id="T10" onOpen={onOpen} lang={lang}>{L("Jak právě proudí dech","Notice the breath now")}</SkyHeading>
    {day!==today&&<p className="sky-small">{L("Nové pozorování se uloží do dneška, i když prohlížíš jiný den.","A new observation is saved for today even while exploring another day.")}</p>}
    <fieldset disabled={!ready}><div className="sky-observe" role="group" aria-label={L("Vnímaná průchodnost dírek","Perceived nostril flow")}>{[["left","L","L"],["right","P","R"],["both","Obě","Both"],["unknown","Nevím","Unsure"]].map(([id,cs,en])=><button type="button" key={id} aria-pressed={side===id} onClick={()=>setSide(id)}>{L(cs,en)}</button>)}</div>
      <label className="sky-check"><input type="checkbox" checked={comfort} onChange={e=>setComfort(e.target.checked)}/><span>{L("V těle je mi příjemně","My body feels comfortable")}</span></label>
      <label>{L("Krátká poznámka","A short note")}<input value={note} maxLength={500} placeholder={L("Co právě vnímám…","What I notice…")} onChange={e=>setNote(e.target.value)}/></label><button type="button" onClick={saveObservation} disabled={!side}>{L("Zapsat teď","Record now")}</button>
    </fieldset>
    {journal.settings.modules.swara&&<div className="sky-record"><SkyHeading id="T11" onOpen={onOpen} lang={lang}>{L("Očekávání při východu","Expected at sunrise")}</SkyHeading><p>{L("Model k ověření","Model to verify")} · {expectedSkyNostril(details?.panchanga?.atSunrise?.tithi)==="left"?L("levá","left"):expectedSkyNostril(details?.panchanga?.atSunrise?.tithi)==="right"?L("pravá","right"):"—"}</p></div>}
    <details><summary>{L("Zápisy vybraného dne","Selected day's observations")} · {dayRecords.length} <SkyHelp id="T12" onOpen={onOpen} lang={lang}/></summary>{dayRecords.length?dayRecords.map(n=><div className="sky-record" key={n.id}><time>{skyTime(n.time,lang,zone)}</time><p>{({left:L("Levá · lunární","Left · lunar"),right:L("Pravá · solární","Right · solar"),both:L("Obě · rovnováha","Both · balance"),unknown:L("Nejisté pozorování","Uncertain observation")})[n.side]}{n.comfort?` · ${L("příjemný pocit","comfortable")}`:""}</p>{n.note&&<p>{n.note}</p>}</div>):<SkyEmpty text={L("Pro tento den zatím nemáš pozorování.","No observations for this day yet.")}/>}<button type="button" onClick={()=>onOpen({kind:"records",type:"nostrils"})}>{L("Celá historie","Full history")}</button></details>
    {journal.settings.modules.cycle&&<><SkyHeading id="T14" onOpen={onOpen} lang={lang}>{L("Cyklus vedle Luny","Cycle beside the Moon")}</SkyHeading><div className="sky-pair"><div><span className="sky-small">{L("Záznam cyklu","Cycle record")}</span><p className="sky-fact">{cycle?.cycle?.day?`${cycle.cycle.day}. ${L("den","day")}`:L("Bez záznamu","No record")}</p>{cycle?.cycle?.certainty&&<small>{cycle.cycle.certainty==="recorded"?L("zapsáno","recorded"):L("odhad","estimate")}</small>}</div><div><span className="sky-small">{L("Světlo Luny","Moon illumination")}</span><p className="sky-fact">{sky.moon.light} %</p><span>{sky.jyotish.waxing?L("Dorůstá","Waxing"):L("Ubývá","Waning")}</span></div></div></>}
    {journal.settings.modules.dream&&<><SkyHeading id="T15" onOpen={onOpen} lang={lang}>{L("Co přinesla noc","What the night brought")}</SkyHeading><fieldset disabled={!ready}><label htmlFor="sky-dream">{L("Můj ranní sen","My morning dream")}</label><textarea id="sky-dream" rows={4} value={dream} maxLength={8000} placeholder={L("Zůstal mi obraz…","An image stayed with me…")} onChange={e=>setDream(e.target.value)}/><div className="sky-actions" role="group" aria-label={L("Prostředí snu","Dream setting")}>{[["upper","Hory a nebe","Mountains and sky"],["middle","Lidská místa","Human places"],["lower","Podzemí a voda","Underground and water"]].map(([id,cs,en])=><button type="button" key={id} aria-pressed={regions.includes(id)} onClick={()=>setRegions(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}>{L(cs,en)}</button>)}</div><button type="button" disabled={!dream.trim()} onClick={saveDream}>{L("Uložit sen","Save dream")}</button></fieldset>
      {dayDreams.map(n=><article className="sky-record" key={n.id}><time>{skyTime(n.time,lang,zone)}</time><p>{n.text}</p>{n.regions?.length>0&&<button type="button" onClick={()=>onOpen({kind:"dream",record:n})}>{L("Otevřít obraz v těle","Open the body image")}</button>}</article>)}<div className="sky-actions"><button type="button" className="sky-quiet" onClick={()=>onOpen({kind:"records",type:"dreams"})}>{L("Historie snů","Dream history")}</button></div></>}
    <p role="status" className="sky-status">{message}</p>
  </>;
}
export function SkyElements({lang="cs"}){const L=(cs,en)=>lang==="en"?en:cs;return <>{SKY_ELEMENTS.map(e=><article className="sky-record" key={e.id}><h3>{L(...e.name)}</h3><p>{L(...e.text)}</p></article>)}</>;}
