import React from "react";
import {ASTRO_PLANETS,ASTRO_SIGNS,ASTRO_ELEMENTS,ASTRO_MODES,ASTRO_ASPECTS,ASTRO_DIGNITIES,ASTRO_LENSES,JYOTISH_READINGS} from "../product/togetherAstrologyEditorial.js";
import {angleDistance} from "../product/togetherAstrology.js";
import {astrologyEventTitle,astrologyEventReading} from "../product/togetherAstrologyOverviewEditorial.js";
import {ZODIAC} from "../product/togetherMoon.js";
import {SKY_HELP,SKY_PRACTICES} from "../product/skyContent.js";
import {SkyHeading,SkyHelpContent,SkyEmpty,skyTime} from "./skyUi.jsx";
import {SkyBodyFigure,SkyBodyPointDetail,SkyElements,skyPosition} from "./skyBody.jsx";
import {SkyDecision,SkyRecordHistory} from "./skyPractice.jsx";
import {skyPlanetName} from "./skyNebe.jsx";

export function skyDetailTitle(detail,lang){const L=(cs,en)=>lang==="en"?en:cs;return detail.kind==="help"?L(SKY_HELP[detail.id]?.title||"O tomto místě","About this part"):detail.kind==="planet"?skyPlanetName(detail.id,L):detail.kind==="practice"?L(...(SKY_PRACTICES[detail.id]?.name||["Praxe","Practice"])):({hours:L("Hodiny dne","Hours of the day"),panchanga:L("Pět částí dne","Five parts of the day"),hellenistic:L("Helénistický klíč","Hellenistic key"),jyotish:L("Džjótiš klíč","Jyotisha key"),tradition:L("Klíč k tradicím","A key to traditions"),body:L("Mapa těla","Body map"),elements:L("Šest prvků","Six elements"),dream:L("Sen v tělesné mapě","Dream in the body map"),records:L("Moje zápisy","My records"),decision:L("Otázka a rozhodnutí","Question and decision"),eclipse:L("Zatmění","Eclipse"),event:L("Předěl v obloze","A change in the sky")})[detail.kind]||L("Podrobnosti","Details");}
function PlanetDetail({id,sky,lang,onOpen}){
  const L=(cs,en)=>lang==="en"?en:cs,p=[...sky.planets,...sky.nodes].find(v=>v.id===id);if(!p)return null;
  const entry=ASTRO_PLANETS[id],dignity=ASTRO_DIGNITIES[p.dignity],ruler=sky.planets.find(v=>v.id===p.ruler),connections=sky.aspects.filter(v=>v.a===id||v.b===id),sun=sky.planets.find(v=>v.id==="Sun");
  return <><SkyHeading id="D01" onOpen={onOpen} lang={lang}>{skyPosition(p,L)}</SkyHeading><p className="sky-small">{p.retrograde?L("℞ Zdánlivě zpětný pohyb","℞ Apparent retrograde motion"):L("Přímý pohyb","Direct motion")} · {Math.abs(p.speed).toFixed(3)}°/{L("den","day")}</p>
    {entry?<><h3>{L(...entry.theme)}</h3><p>{sky.lens==="jyotish"?L(...(JYOTISH_READINGS[id]||entry.text)):L(...entry.text)}</p></>:<p>{id==="Rahu"?L("Vzestupný uzel lunární dráhy. V učitelově mapě ukazuje k touze a centrálnímu kanálu.","The ascending node of the lunar orbit. In your teacher's map it points toward desire and the central channel."):L("Sestupný uzel lunární dráhy. V učitelově mapě připomíná oheň, který uvolňuje sevření příběhu.","The descending node of the lunar orbit. In your teacher's map it recalls the fire that loosens a story's grip.")}</p>}
    <SkyHeading id="D02" onOpen={onOpen} lang={lang}>{L(...ZODIAC[p.sign])}</SkyHeading><p className="sky-small">{L(...ASTRO_ELEMENTS[p.sign%4])} · {L(...ASTRO_MODES[ASTRO_SIGNS[p.sign].mode])}</p><p>{L(...ASTRO_SIGNS[p.sign].text)}</p>
    {dignity&&ruler&&<><SkyHeading id="D05" onOpen={onOpen} lang={lang}>{L(...dignity.name)}</SkyHeading><p>{L(...dignity.text)}</p><button type="button" className="sky-quiet" onClick={()=>onOpen({kind:"planet",id:ruler.id})}>{L("Hostitel","Host")}: {skyPlanetName(ruler.id,L)} · {skyPosition(ruler,L)} →</button></>}
    {entry&&<><SkyHeading id="D04" onOpen={onOpen} lang={lang}>{L("Dar a jeho stín","The gift and its shadow")}</SkyHeading><p>{L(...entry.shadow)}</p><SkyHeading id="D03" onOpen={onOpen} lang={lang}>{L("Vazby této planety","This planet's connections")}</SkyHeading>{connections.length?connections.map(a=>{const other=a.a===id?a.b:a.a,meaning=ASTRO_ASPECTS[a.id];return <article className="sky-record" key={other}><h4>{skyPlanetName(other,L)} · {L(...meaning.name)}</h4><p className="sky-small">{a.angle}° · {L("odchylka","orb")} {a.orb.toFixed(2)}° · {a.applying?L("sbíhavý","applying"):L("rozbíhavý","separating")}</p><p>{L(...meaning.text)}</p><button type="button" className="sky-quiet" onClick={()=>onOpen({kind:"planet",id:other})}>{L("Prozkoumat","Explore")} {skyPlanetName(other,L)} →</button></article>}):<p>{L("Pro tuto planetu nyní není hlavní aspekt v nastavených mezích.","No major aspect is within the tracked orb for this planet now.")}</p>}</>}
    {id!=="Sun"&&<><SkyHeading id="D06" onOpen={onOpen} lang={lang}>{L("Vztah ke Slunci","Relationship to the Sun")}</SkyHeading><p>{angleDistance(p.longitude,sun.longitude).toFixed(1)}° · {L("rozdíl ekliptikálních délek","ecliptic longitude separation")}</p></>}
  </>;
}
export function SkyDetails({detail,sky,details,journal,update,ready,lang="cs",onOpen,onSettings,onDay}){
  const L=(cs,en)=>lang==="en"?en:cs,zone=journal.settings.location.timeZone,n=details.natal,p=details.panchanga;
  const absent=<SkyEmpty text={L("Osobní výpočet čeká na jednoznačný čas a místo narození.","Personal calculations need an unambiguous birth time and location.")}><button type="button" onClick={onSettings}>{L("Doplnit narození","Add birth details")}</button></SkyEmpty>;
  if(detail.kind==="event"&&detail.event.type==="eclipse")return <SkyDetails {...{sky,details,journal,update,ready,lang,onOpen,onSettings,onDay}} detail={{kind:"eclipse",event:{...detail.event,type:detail.event.eclipseType}}}/>;
  if(detail.kind==="event"&&detail.event.type==="season"){
    const names={"march-equinox":["Březnová rovnodennost","March equinox"],"june-solstice":["Červnový slunovrat","June solstice"],"september-equinox":["Zářijová rovnodennost","September equinox"],"december-solstice":["Prosincový slunovrat","December solstice"]};
    return <><h3>{L(...(names[detail.event.seasonId]||["Předěl roku","Seasonal turning point"]))}</h3><p>{skyTime(detail.event.time,lang,zone,true)}</p><SkyHelpContent id="Y01" lang={lang}/><button type="button" onClick={()=>onDay(detail.event.time)}>{L("Otevřít tento okamžik","Open this instant")} →</button></>;
  }
  switch(detail.kind){
    case "help":return <SkyHelpContent id={detail.id} lang={lang}/>;
    case "planet":return <PlanetDetail id={detail.id} sky={sky} lang={lang} onOpen={onOpen}/>;
    case "body":return <SkyBodyPointDetail id={detail.id} natal={n} sky={sky} lang={lang} onSettings={onSettings}/>;
    case "elements":return <><SkyHelpContent id="T06" lang={lang}/><SkyElements lang={lang}/></>;
    case "dream":return <><p>{detail.record.text}</p><SkyBodyFigure personal={false} dreamRegions={detail.record.regions} lang={lang}/><SkyHelpContent id="T16" lang={lang}/></>;
    case "records":return <SkyRecordHistory type={detail.type} journal={journal} update={update} ready={ready} lang={lang} onOpen={onOpen}/>;
    case "decision":return <SkyDecision key={detail.record?.id||"new"} record={detail.record} journal={journal} update={update} ready={ready} lang={lang}/>;
    case "practice":return <><p className="sky-lead">{L(...SKY_PRACTICES[detail.id].text)}</p><SkyHelpContent id={detail.id==="hevajra"?"P03":detail.id==="vajrayogini"?"P07":detail.id==="sadhana"?"P06":"P01"} lang={lang}/></>;
    case "hours":return <><SkyHelpContent id="N08" lang={lang}/>{details.planetaryHours.hours.length?<div className="sky-timeline">{details.planetaryHours.hours.map(h=><div className="sky-hour-row" key={h.start} aria-current={h.start===details.planetaryHours.current?.start?"time":undefined}><span className="sky-small">{h.index}. · {h.daytime?L("denní","daylight"):L("noční","night")}</span><strong>{skyPlanetName(h.planet,L)}</strong><span>{skyTime(h.start,lang,zone)}–{skyTime(h.end,lang,zone)}</span></div>)}</div>:<SkyEmpty text={L("Pro toto místo a den není ohraničený úsek od východu do dalšího východu.","No bounded sunrise-to-sunrise interval is available here for this day.")}/>}</>;
    case "panchanga":return <><SkyHelpContent id="J01" lang={lang}/>{[["N06",L("Vára · planeta dne","Vara · day ruler"),skyPlanetName(p.dayPlanet,L)],["N04",L("Tithi · lunární den","Tithi · lunar day"),`${p.tithi}. ${p.tithiName}`],["N05",L("Nakšatra · lunární dům","Nakshatra · lunar mansion"),`${p.nakshatraName} · ${p.pada}`],["J04",L("Jóga · součet světel","Yoga · sum of the lights"),p.yogaName],["J05",L("Karana · půlden Luny","Karana · lunar half-day"),p.karanaName]].map(([id,title,value])=><div key={id}><SkyHeading id={id} onOpen={onOpen} lang={lang}>{title}</SkyHeading><p className="sky-fact">{value}</p>{p.transitions.find(v=>({N04:"tithi",N05:"nakshatra",J04:"yoga",J05:"karana"})[id]===v.type)&&<p className="sky-small">{L("Další přechod","Next transition")} · {skyTime(p.transitions.find(v=>({N04:"tithi",N05:"nakshatra",J04:"yoga",J05:"karana"})[id]===v.type).time,lang,zone,true)}</p>}</div>)}{p.atSunrise&&<p className="sky-small">{L("Při východu","At sunrise")} {skyTime(p.sunrise,lang,zone,true)}: {p.atSunrise.tithi}. {p.atSunrise.tithiName}</p>}</>;
    case "hellenistic":return <><SkyHeading id="H01" onOpen={onOpen} lang={lang}>{L("Sedm světel a jejich hostitelé","Seven lights and their hosts")}</SkyHeading><p>{L(...ASTRO_LENSES.hellenistic.text)}</p>{n.status!=="ok"?absent:<><SkyHeading id="H02" onOpen={onOpen} lang={lang}>{L("Sekta narození","Birth sect")}</SkyHeading><p className="sky-fact">{n.sect==="day"?L("Denní · Slunce nad obzorem","Day · Sun above the horizon"):n.sect==="night"?L("Noční · Slunce pod obzorem","Night · Sun below the horizon"):L("Na hranici obzoru","At the horizon boundary")}</p><SkyHeading id="H03" onOpen={onOpen} lang={lang}>{L("Vládce osobního roku","Personal year ruler")}</SkyHeading><p className="sky-fact">{skyPlanetName(n.profection?.ruler,L)}</p>{n.profection&&<p>{n.profection.house}. {L("dům","house")} · {L(...ZODIAC[n.profection.sign])} · {n.profection.age} {L("dokončených let","completed years")}</p>}<SkyHeading id="H04" onOpen={onOpen} lang={lang}>{L("Los Štěstí a Los Ducha","Lot of Fortune and Lot of Spirit")}</SkyHeading>{n.lots?<div className="sky-pair"><div>{L("Štěstí","Fortune")}<p>{skyPosition(n.lots.fortune,L)}</p></div><div>{L("Duch","Spirit")}<p>{skyPosition(n.lots.spirit,L)}</p></div></div>:<p>{L("Při nejisté sektě losy nepočítáme.","Lots are not assigned when sect is uncertain.")}</p>}</>}</>;
    case "jyotish":return <><p>{L(...ASTRO_LENSES.jyotish.text)}</p><button type="button" className="sky-quiet" onClick={()=>onOpen({kind:"panchanga"})}>{L("Otevřít pančángu","Open panchanga")} →</button><SkyHeading id="J02" onOpen={onOpen} lang={lang}>{L("Gočara · dnešní průchod","Gochara · today's passage")}</SkyHeading>{n.status!=="ok"?absent:<>{n.gochara.map(v=><div className="sky-record" key={v.id}><strong>{skyPlanetName(v.id,L)}</strong> · {skyPosition(v,L)}<p className="sky-small">{v.houseFromMoon}. {L("znamení od natální Luny","sign from the natal Moon")}</p></div>)}<SkyHeading id="J03" onOpen={onOpen} lang={lang}>{L("Vimšóttarí daša","Vimshottari dasha")}</SkyHeading>{n.dasha?.current?<><p className="sky-fact">{skyPlanetName(n.dasha.lord,L)} · {skyPlanetName(n.dasha.subperiod?.lord,L)}</p><p>{new Date(n.dasha.start).toLocaleDateString(lang==="en"?"en-GB":"cs-CZ",{timeZone:zone,day:"numeric",month:"long",year:"numeric"})} — {new Date(n.dasha.end).toLocaleDateString(lang==="en"?"en-GB":"cs-CZ",{timeZone:zone,day:"numeric",month:"long",year:"numeric"})}</p><button type="button" onClick={()=>onOpen({kind:"life"})}>{L("Celá mapa období","Full lifetime map")} →</button></>:<p>{L("Pro tento den není dostupná daša.","No dasha is available for this day.")}</p>}</>}</>;
    case "tradition":return <>{Object.entries(ASTRO_LENSES).filter(([key])=>journal.settings.traditions[key]).map(([key,v])=><article className="sky-record" key={key}><h3>{L(...v.name)}</h3><p>{L(...v.text)}</p></article>)}<SkyHelpContent id="G08" lang={lang}/></>;
    case "event":return <><p className="sky-small">{skyTime(detail.event.time,lang,zone,true)}</p><h3>{astrologyEventTitle(detail.event,lang)}</h3><p>{astrologyEventReading(detail.event,detail.lens||sky.lens,lang)}</p><button type="button" onClick={()=>onDay(detail.event.time)}>{L("Otevřít tento okamžik","Open this instant")} →</button></>;
    case "eclipse":return <><h3>{detail.event.kind==="solar"?L("Zatmění Slunce","Solar eclipse"):L("Zatmění Měsíce","Lunar eclipse")}</h3><p>{skyTime(detail.event.time,lang,zone,true)}</p><p>{({total:L("Úplné","Total"),annular:L("Prstencové","Annular"),partial:L("Částečné","Partial"),hybrid:L("Hybridní","Hybrid"),penumbral:L("Polostínové","Penumbral")})[detail.event.type]}</p><p>{detail.event.visible===true?L("Viditelné z vybraného místa.","Visible from the selected location."):detail.event.visible===false?L("Z vybraného místa není viditelné.","Not visible from the selected location."):L("Místní viditelnost není určena.","Local visibility is not determined.")}</p><SkyHelpContent id="N16" lang={lang}/></>;
    default:return <SkyHelpContent id={detail.id||"G06"} lang={lang}/>;
  }
}
