import React,{useId,useState} from "react";
import {ASTRO_PLANETS,ASTRO_ASPECTS} from "../product/togetherAstrologyEditorial.js";
import {CLASSICAL_BODIES} from "../product/togetherAstrology.js";
import {MOON_NAMES} from "../product/togetherMoon.js";
import {LUNAR_PHASE_PRACTICES} from "../product/togetherMoonEditorial.js";
import {SkyChart} from "./skyChart.jsx";
import {SkyHeading,SkyHelp,skyTime} from "./skyUi.jsx";
import {skyPosition} from "./skyBody.jsx";
import {TogetherAstrologyOverview} from "./togetherAstrologyOverview.jsx";

export const skyPlanetName=(id,L)=>ASTRO_PLANETS[id]?L(...ASTRO_PLANETS[id].name):id||"—";
export function SkyMoon({phase,light,label}){
  const uid=useId(),k=Math.cos(phase*2*Math.PI),waxing=phase<.5;
  return <svg viewBox="0 0 120 120" width="112" height="112" role="img" aria-label={label} style={{display:"block",margin:"12px auto",color:"var(--astro-ink)"}}><defs><clipPath id={uid}><circle cx="60" cy="60" r="46"/></clipPath></defs><circle cx="60" cy="60" r="46" fill="currentColor" fillOpacity=".08"/><g clipPath={`url(#${uid})`} fill="currentColor" opacity=".7"><path d={waxing?"M60 14A46 46 0 0 1 60 106Z":"M60 14A46 46 0 0 0 60 106Z"}/>{k<0?<ellipse cx="60" cy="60" rx={Math.abs(k)*46} ry="46"/>:null}</g>{k>0&&<ellipse cx="60" cy="60" rx={k*46} ry="46" fill="var(--astro-bg)"/>}<circle cx="60" cy="60" r="46" fill="none" stroke="currentColor" strokeWidth=".8"/><text x="60" y="64" textAnchor="middle" fontSize="16" fill="var(--astro-text)" style={{paintOrder:"stroke",stroke:"var(--astro-bg)",strokeWidth:3}}>{light} %</text></svg>;
}
export function SkyNebe({sky,details,day,journal,lang="cs",onOpen,onWeek}){
  const L=(cs,en)=>lang==="en"?en:cs,zone=journal.settings.location.timeZone,p=details.panchanga,h=details.planetaryHours;
  const [filter,setFilter]=useState(sky.lens==="western"?"all":"classical"),[aspect,setAspect]=useState("all"),[lines,setLines]=useState(true),[nodes,setNodes]=useState(sky.lens==="jyotish"),[mansions,setMansions]=useState(true);
  const planets=sky.planets.filter(v=>filter==="lights"?["Sun","Moon"].includes(v.id):filter==="classical"?CLASSICAL_BODIES.includes(v.id):true),chartPlanets=nodes?[...planets,...sky.nodes]:planets;
  const aspects=sky.aspects.filter(v=>aspect==="all"||v.id===aspect),lead=sky.aspects.filter(a=>sky.lens==="western"||(CLASSICAL_BODIES.includes(a.a)&&CLASSICAL_BODIES.includes(a.b))).filter(a=>["Sun","Moon","Mercury","Venus","Mars"].includes(a.a)||["Sun","Moon","Mercury","Venus","Mars"].includes(a.b)).sort((a,b)=>a.orb-b.orb)[0];
  const sentence=lead?L(`${skyPlanetName(lead.a,L)} a ${skyPlanetName(lead.b,L)}: ${L(...ASTRO_ASPECTS[lead.id].name).toLowerCase()}. Dnes nejdřív naslouchej, potom zvol jeden vědomý krok.`,`${skyPlanetName(lead.a,L)} and ${skyPlanetName(lead.b,L)}: ${L(...ASTRO_ASPECTS[lead.id].name).toLowerCase()}. Listen first, then choose one deliberate step.`):L("Dnešní obloha otevírá prostor pro pozorný dech a jeden vědomý krok.","Today's sky invites an attentive breath and one deliberate step.");
  const planet=id=>onOpen({kind:"planet",id});
  return <>
    <div className="sky-heading"><p className="sky-lead">{sentence}</p><SkyHelp id="N01" onOpen={onOpen} lang={lang}/></div>
    <div className="sky-pair"><div><SkyHeading id="N02" onOpen={onOpen} lang={lang}>{L("Slunce","Sun")}</SkyHeading><svg viewBox="0 0 120 120" width="112" height="112" fill="none" stroke="currentColor" aria-hidden="true" style={{display:"block",margin:"12px auto",color:"var(--astro-ink)"}}><circle cx="60" cy="60" r="26"/>{Array.from({length:12},(_,i)=><path key={i} d="M60 19v-9" transform={`rotate(${i*30} 60 60)`}/>)}<circle cx="60" cy="60" r="20" opacity=".25"/></svg><div className="sky-fact">{skyTime(details.solar.sunrise,lang,zone)} <span className="sky-small">↑</span><br/>{skyTime(details.solar.sunset,lang,zone)} <span className="sky-small">↓</span></div>{details.solar.status!=="ok"&&<p className="sky-small">{details.solar.status==="polar-day"?L("Polární den","Polar day"):details.solar.status==="polar-night"?L("Polární noc","Polar night"):L("V tomto občanském dni chybí jeden přechod.","One crossing falls outside this civil day.")}</p>}</div>
      <div><SkyHeading id="N03" onOpen={onOpen} lang={lang}>{L("Luna","Moon")}</SkyHeading><SkyMoon phase={sky.moon.phase} light={sky.moon.light} label={`${L(...MOON_NAMES[sky.moon.index])}, ${sky.moon.light} %`}/><p className="sky-fact">{L(...MOON_NAMES[sky.moon.index])}</p><span className="sky-small">{p.waxing?L("Dorůstá","Waxing"):L("Ubývá","Waning")}</span></div></div>
    {sky.lens==="jyotish"&&<div className="sky-pair"><div><SkyHeading id="N04" onOpen={onOpen} lang={lang}>{L("Lunární den","Lunar day")}</SkyHeading><button type="button" className="sky-quiet" onClick={()=>onOpen({kind:"panchanga"})}><span className="sky-fact">{p.tithi}. · {p.tithiName}</span></button><p className="sky-small">{L("Končí","Ends")} {skyTime(p.tithiEnd,lang,zone,true)}</p></div><div><SkyHeading id="N05" onOpen={onOpen} lang={lang}>{L("Lunární dům","Lunar mansion")}</SkyHeading><p className="sky-fact">{p.nakshatraName}</p><span className="sky-small">{L("Páda","Pada")} {p.pada} · {L("do","until")} {skyTime(p.nakshatraEnd,lang,zone,true)}</span></div></div>}
    <p className="sky-small">{L("Další hlavní fáze","Next principal phase")}: {L(...MOON_NAMES[sky.moon.nextIndex])} · {skyTime(sky.moon.next,lang,zone,true)}</p>
    <details><summary>{L("Dva časy jedné oblohy","Two timescales of one sky")}</summary><p>{L(...LUNAR_PHASE_PRACTICES[sky.moon.index].text)}</p><p>{L("Luna promění svou tvář během měsíce. Pomalé planety nesou pozadí mnoha měsíců i let. Všímej si, co je dnešní vlna a co delší proud.","The Moon changes its face within a month. Slow planets carry the background of months and years. Notice today's wave within the longer current.")}</p></details>
    <div className="sky-pair"><div><SkyHeading id="N06" onOpen={onOpen} lang={lang}>{L("Planeta dne","Day ruler")}</SkyHeading><p className="sky-fact">{skyPlanetName(h.dayPlanet,L)}</p></div><div><SkyHeading id="N07" onOpen={onOpen} lang={lang}>{L("Hodina teď","Current hour")}</SkyHeading><button type="button" className="sky-quiet" onClick={()=>onOpen({kind:"hours"})}><span className="sky-fact">{skyPlanetName(h.current?.planet,L)}</span></button><p className="sky-small">{h.current?`${skyTime(h.current.start,lang,zone)}–${skyTime(h.current.end,lang,zone)}`:L("Bez ohraničeného slunečního dne","No bounded solar day")}</p></div></div>
    <div className="sky-links"><button type="button" onClick={()=>onOpen({kind:"hours"})}>{L("Rozvinout hodiny dne","Unfold the day's hours")} →</button><SkyHelp id="N08" onOpen={onOpen} lang={lang}/></div>
    <TogetherAstrologyOverview sky={sky} day={day} lens={sky.lens} lang={lang} timeZone={zone} onOpen={onOpen} onWeek={onWeek}/>
    <SkyHeading id="N11" onOpen={onOpen} lang={lang}>{L("Kolo oblohy","Sky wheel")}</SkyHeading><p className="sky-small">{sky.lens==="jyotish"?L("Siderický zvěrokruh · Lahiri","Sidereal zodiac · Lahiri"):L("Tropický zvěrokruh","Tropical zodiac")} <SkyHelp id="N12" onOpen={onOpen} lang={lang}/></p>
    <SkyChart planets={chartPlanets} aspects={lines?aspects:[]} selected={null} onSelect={planet} nakshatra={sky.lens==="jyotish"&&mansions} L={L}/>
    <details><summary>{L("Vrstvy a filtry grafu","Chart layers and filters")}</summary><div className="sky-actions">{[["all","Všechny planety","All planets"],["classical","Sedm světel","Seven lights"],["lights","Slunce a Luna","Sun and Moon"]].map(([id,cs,en])=><button key={id} type="button" aria-pressed={filter===id} onClick={()=>setFilter(id)}>{L(cs,en)}</button>)}</div><label className="sky-check"><input type="checkbox" checked={nodes} onChange={e=>setNodes(e.target.checked)}/>{sky.lens==="jyotish"?L("Rahu a Ketu","Rahu and Ketu"):L("Lunární uzly","Lunar nodes")}</label><label className="sky-check"><input type="checkbox" checked={lines} onChange={e=>setLines(e.target.checked)}/>{L("Aspektové vazby","Aspect connections")}</label>{sky.lens==="jyotish"&&<label className="sky-check"><input type="checkbox" checked={mansions} onChange={e=>setMansions(e.target.checked)}/>{L("27 lunárních domů","27 lunar mansions")}</label>}<label>{L("Aspekty","Aspects")}<select value={aspect} onChange={e=>setAspect(e.target.value)}><option value="all">{L("Všechny","All")}</option>{Object.entries(ASTRO_ASPECTS).map(([id,v])=><option key={id} value={id}>{L(...v.name)}</option>)}</select></label><SkyHelp id="N13" onOpen={onOpen} lang={lang}/></details>
    <SkyHeading id="N14" onOpen={onOpen} lang={lang}>{L("Planety v pohybu","Planets in motion")}</SkyHeading><div className="sky-planet-list">{chartPlanets.map(v=><button type="button" key={v.id} onClick={()=>planet(v.id)}><span className="sky-planet-glyph" aria-hidden="true">{ASTRO_PLANETS[v.id]?.symbol||(v.id==="Rahu"?"☊":"☋")}</span><span>{skyPlanetName(v.id,L)}{v.retrograde&&<em aria-label={L("Retrográdní","Retrograde")}> ℞</em>}<small>{skyPosition(v,L)}</small></span><span aria-hidden="true">›</span></button>)}</div>
    {planets.some(v=>v.retrograde)&&<div className="sky-heading"><p className="sky-small">℞ {L("Právě retrográdní","Currently retrograde")}: {planets.filter(v=>v.retrograde).map(v=>skyPlanetName(v.id,L)).join(", ")}</p><SkyHelp id="N15" onOpen={onOpen} lang={lang}/></div>}
    {details.eclipses.length>0&&<><SkyHeading id="N16" onOpen={onOpen} lang={lang}>{L("Zatmění v tomto dni","Eclipse on this day")}</SkyHeading>{details.eclipses.map(e=><button type="button" key={e.time} className="sky-quiet" onClick={()=>onOpen({kind:"eclipse",event:e})}>{skyTime(e.time,lang,zone,true)} · {e.kind==="solar"?L("Slunce","Sun"):L("Luna","Moon")} →</button>)}</>}
    <div className="sky-links">{sky.lens==="hellenistic"&&<button type="button" onClick={()=>onOpen({kind:"hellenistic"})}>{L("Helénistický klíč","Hellenistic key")} ↗</button>}{sky.lens==="jyotish"&&<button type="button" onClick={()=>onOpen({kind:"jyotish"})}>{L("Džjótiš klíč","Jyotisha key")} ↗</button>}<button type="button" onClick={()=>onOpen({kind:"tradition"})}>{L("Klíč k tradicím","A key to the traditions")}</button></div>
  </>;
}
