import React,{useId,useState} from "react";
import {ASTRO_PLANETS,ASTRO_ASPECTS} from "../product/togetherAstrologyEditorial.js";
import {CLASSICAL_BODIES} from "../product/togetherAstrology.js";
import {MOON_NAMES} from "../product/togetherMoon.js";
import {LUNAR_PHASE_PRACTICES} from "../product/togetherMoonEditorial.js";
import {SkyChart} from "./skyChart.jsx";
import {SkyHeading,SkyHelp,skyTime} from "./skyUi.jsx";
import {skyPosition} from "./skyBody.jsx";
import {SkyExplore,SkyNote,SkyStep,skyOrientation} from "./skyExplore.jsx";
import {SkyPersonalContext} from "./skyPeriods.jsx";
import {TogetherAstrologyOverview} from "./togetherAstrologyOverview.jsx";

export const skyPlanetName=(id,L)=>ASTRO_PLANETS[id]?L(...ASTRO_PLANETS[id].name):id||"—";
export function SkyMoon({phase,light,label}){
  const uid=useId(),k=Math.cos(phase*2*Math.PI),waxing=phase<.5;
  return <svg viewBox="0 0 120 120" width="112" height="112" role="img" aria-label={label} style={{display:"block",margin:"12px auto",color:"var(--astro-ink)"}}><defs><clipPath id={uid}><circle cx="60" cy="60" r="46"/></clipPath></defs><circle cx="60" cy="60" r="46" fill="currentColor" fillOpacity=".08"/><g clipPath={`url(#${uid})`} fill="currentColor" opacity=".7"><path d={waxing?"M60 14A46 46 0 0 1 60 106Z":"M60 14A46 46 0 0 0 60 106Z"}/>{k<0?<ellipse cx="60" cy="60" rx={Math.abs(k)*46} ry="46"/>:null}</g>{k>0&&<ellipse cx="60" cy="60" rx={k*46} ry="46" fill="var(--astro-bg)"/>}<circle cx="60" cy="60" r="46" fill="none" stroke="currentColor" strokeWidth=".8"/><text x="60" y="64" textAnchor="middle" fontSize="16" fill="var(--astro-text)" style={{paintOrder:"stroke",stroke:"var(--astro-bg)",strokeWidth:3}}>{light} %</text></svg>;
}

function DayChanges({sky,details,lang,zone,onDay,onOpen}){
  const L=(cs,en)=>lang==="en"?en:cs,h=details.planetaryHours,now=Date.parse(sky.date);
  const nextHour=h.hours.find(hour=>hour.start===h.current?.end),changes=[];
  if(nextHour)changes.push({id:"hour",time:nextHour.start,title:L("Nová planetární hodina","Next planetary hour"),value:skyPlanetName(nextHour.planet,L),open:()=>onOpen({kind:"hours"})});
  if(sky.moon.next)changes.push({id:"phase",time:sky.moon.next,title:L("Další hlavní fáze","Next principal phase"),value:L(...MOON_NAMES[sky.moon.nextIndex]),open:()=>onOpen({kind:"help",id:"N03"})});
  if(sky.lens==="jyotish")for(const event of details.panchanga.transitions.filter(e=>["tithi","nakshatra"].includes(e.type)))changes.push({id:event.type,time:event.time,title:event.type==="tithi"?L("Mění se lunární den","Lunar day changes"):L("Mění se lunární dům","Lunar mansion changes"),value:event.type==="tithi"?`${event.from}. → ${event.to}. tithi`:L("Hranice nakšatry","Nakshatra boundary"),open:()=>onOpen({kind:"panchanga"})});
  for(const e of details.eclipses)changes.push({id:`eclipse:${e.time}`,time:e.time,title:e.kind==="solar"?L("Zatmění Slunce","Solar eclipse"):L("Zatmění Měsíce","Lunar eclipse"),value:L("Událost vybraného dne","Event on the selected day"),open:()=>onOpen({kind:"eclipse",event:e})});
  changes.sort((a,b)=>Date.parse(a.time)-Date.parse(b.time));
  return <details className="sky-unfold"><summary>{L("Co se mění dál","What changes next")}</summary><ol className="sky-change-path">{changes.map(event=><li key={event.id}><time className="sky-small">{skyTime(event.time,lang,zone,true)}{Date.parse(event.time)<now?` · ${L("před vybraným časem","before the selected time")}`:""}</time><h4>{event.title}</h4><p>{event.value}</p><div className="sky-links">{onDay&&<button type="button" onClick={()=>onDay(event.time)}>{L("Přejít do tohoto času","Go to this time")} →</button>}<button type="button" onClick={event.open}>{L("Vysvětlit","Explain")}</button></div></li>)}</ol></details>;
}
export function SkyNebe({sky,details,day,journal,update,ready,lang="cs",onOpen,onWeek,onDay}){
  const L=(cs,en)=>lang==="en"?en:cs,zone=journal.settings.location.timeZone,p=details.panchanga,h=details.planetaryHours,orientation=skyOrientation(sky,details,lang);
  const [filter,setFilter]=useState(sky.lens==="western"?"all":"classical"),[aspect,setAspect]=useState("all"),[lines,setLines]=useState(true),[nodes,setNodes]=useState(sky.lens==="jyotish"),[mansions,setMansions]=useState(true),[selected,setSelected]=useState(null);
  const planets=sky.planets.filter(v=>filter==="lights"?["Sun","Moon"].includes(v.id):filter==="classical"?CLASSICAL_BODIES.includes(v.id):true),chartPlanets=nodes?[...planets,...sky.nodes]:planets;
  const aspects=sky.aspects.filter(v=>aspect==="all"||v.id===aspect),active=chartPlanets.find(v=>v.id===selected),editorial=active&&ASTRO_PLANETS[active.id];
  const planet=id=>onOpen({kind:"planet",id});
  const now=<>
    <div className="sky-wheel-caption"><span className="sky-small">{sky.lens==="jyotish"?L("Siderický zvěrokruh · Lahiri","Sidereal zodiac · Lahiri"):L("Tropický zvěrokruh","Tropical zodiac")} · {skyTime(sky.date,lang,zone)}</span><SkyHelp id="N11" onOpen={onOpen} lang={lang}/></div>
    <SkyChart planets={chartPlanets} aspects={lines?aspects:[]} selected={active?.id||null} onSelect={setSelected} nakshatra={sky.lens==="jyotish"&&mansions} L={L}/>
    <p className="sky-wheel-hint sky-small">{L("Vyber planetu v kole. Posun času nahoře promění její polohu.","Choose a planet in the wheel. Moving the clock above changes its position.")}</p>
    {active?<div className="sky-planet-focus" key={active.id}><div className="sky-heading"><span className="sky-label">{skyPlanetName(active.id,L)}{active.retrograde?" · ℞":""}</span><button type="button" className="sky-quiet sky-small" onClick={()=>setSelected(null)}>{L("Celá obloha","Whole sky")}</button></div><h3>{editorial?L(...editorial.theme):L("Průsečík dráhy Luny","Intersection of the Moon's orbit")}</h3><p className="sky-data sky-small">{skyPosition(active,L)}</p><p>{editorial?L(...editorial.text).split(/(?<=[.!?])\s/)[0]:L("Lunární uzel je vypočtený bod, kde se dráha Luny protíná s ekliptikou.","A lunar node is a calculated point where the Moon's orbit crosses the ecliptic.")}</p><div className="sky-links"><button type="button" onClick={()=>planet(active.id)}>{L("Otevřít význam a souvislosti","Open meaning and context")} ↗</button></div></div>:<div className="sky-orientation"><div className="sky-heading"><span className="sky-label">{L("Symbolické čtení okamžiku","A symbolic reading of the moment")}</span><SkyHelp id={orientation.help} onOpen={onOpen} lang={lang}/></div><h3>{orientation.title}</h3><p className="sky-data sky-small">{orientation.fact}</p><p>{orientation.meaning}</p></div>}
    <details className="sky-unfold"><summary>{L("Planety, polohy a vrstvy kola","Planets, positions and wheel layers")}</summary><SkyHeading id="N14" onOpen={onOpen} lang={lang}>{L("Planety v pohybu","Planets in motion")}</SkyHeading><div className="sky-planet-list">{chartPlanets.map(v=><button type="button" key={v.id} onClick={()=>planet(v.id)}><span className="sky-planet-glyph" aria-hidden="true">{`${ASTRO_PLANETS[v.id]?.symbol||(v.id==="Rahu"?"☊":"☋")}\uFE0E`}</span><span>{skyPlanetName(v.id,L)}{v.retrograde&&<em aria-label={L("Retrográdní","Retrograde")}> ℞</em>}<small>{skyPosition(v,L)}</small></span><span aria-hidden="true">›</span></button>)}</div>
      <details><summary>{L("Vrstvy a filtry grafu","Chart layers and filters")}</summary><div className="sky-actions">{[["all","Všechny planety","All planets"],["classical","Sedm světel","Seven lights"],["lights","Slunce a Luna","Sun and Moon"]].map(([id,cs,en])=><button key={id} type="button" aria-pressed={filter===id} onClick={()=>setFilter(id)}>{L(cs,en)}</button>)}</div><label className="sky-check"><input type="checkbox" checked={nodes} onChange={e=>setNodes(e.target.checked)}/>{sky.lens==="jyotish"?L("Rahu a Ketu","Rahu and Ketu"):L("Lunární uzly","Lunar nodes")}</label><label className="sky-check"><input type="checkbox" checked={lines} onChange={e=>setLines(e.target.checked)}/>{L("Aspektové vazby","Aspect connections")}</label>{sky.lens==="jyotish"&&<label className="sky-check"><input type="checkbox" checked={mansions} onChange={e=>setMansions(e.target.checked)}/>{L("27 lunárních domů","27 lunar mansions")}</label>}<label>{L("Aspekty","Aspects")}<select value={aspect} onChange={e=>setAspect(e.target.value)}><option value="all">{L("Všechny","All")}</option>{Object.entries(ASTRO_ASPECTS).map(([id,v])=><option key={id} value={id}>{L(...v.name)}</option>)}</select></label><SkyHelp id="N13" onOpen={onOpen} lang={lang}/></details></details>
    <DayChanges sky={sky} details={details} lang={lang} zone={zone} onDay={onDay} onOpen={onOpen}/>
    <details className="sky-unfold"><summary>{L("Časy a údaje dne","Times and facts of the day")}</summary><div className="sky-pair"><div><SkyHeading id="N02" onOpen={onOpen} lang={lang}>{L("Slunce","Sun")}</SkyHeading><p className="sky-fact">{skyTime(details.solar.sunrise,lang,zone)} <span className="sky-small">↑</span><br/>{skyTime(details.solar.sunset,lang,zone)} <span className="sky-small">↓</span></p>{details.solar.status!=="ok"&&<p className="sky-small">{details.solar.status==="polar-day"?L("Polární den","Polar day"):details.solar.status==="polar-night"?L("Polární noc","Polar night"):L("V tomto občanském dni chybí jeden přechod.","One crossing falls outside this civil day.")}</p>}</div><div><SkyHeading id="N03" onOpen={onOpen} lang={lang}>{L("Luna","Moon")}</SkyHeading><SkyMoon phase={sky.moon.phase} light={sky.moon.light} label={`${L(...MOON_NAMES[sky.moon.index])}, ${sky.moon.light} %`}/><p className="sky-fact">{L(...MOON_NAMES[sky.moon.index])}</p></div></div>
      {sky.lens==="jyotish"&&<div className="sky-pair"><div><SkyHeading id="N04" onOpen={onOpen} lang={lang}>{L("Lunární den","Lunar day")}</SkyHeading><button type="button" className="sky-quiet" onClick={()=>onOpen({kind:"panchanga"})}><span className="sky-fact">{p.tithi}. · {p.tithiName}</span></button><p className="sky-small">{L("Končí","Ends")} {skyTime(p.tithiEnd,lang,zone,true)}</p></div><div><SkyHeading id="N05" onOpen={onOpen} lang={lang}>{L("Lunární dům","Lunar mansion")}</SkyHeading><p className="sky-fact">{p.nakshatraName}</p><span className="sky-small">{L("Páda","Pada")} {p.pada} · {L("do","until")} {skyTime(p.nakshatraEnd,lang,zone,true)}</span></div></div>}
      <div className="sky-pair"><div><SkyHeading id="N06" onOpen={onOpen} lang={lang}>{L("Planeta dne","Day ruler")}</SkyHeading><p className="sky-fact">{skyPlanetName(h.dayPlanet,L)}</p></div><div><SkyHeading id="N07" onOpen={onOpen} lang={lang}>{L("Hodina teď","Current hour")}</SkyHeading><button type="button" className="sky-quiet" onClick={()=>onOpen({kind:"hours"})}><span className="sky-fact">{skyPlanetName(h.current?.planet,L)}</span></button><p className="sky-small">{h.current?`${skyTime(h.current.start,lang,zone)}–${skyTime(h.current.end,lang,zone)}`:L("Bez ohraničeného slunečního dne","No bounded solar day")}</p></div></div><div className="sky-links"><button type="button" onClick={()=>onOpen({kind:"hours"})}>{L("Rozvinout hodiny dne","Unfold the day's hours")} →</button><SkyHelp id="N08" onOpen={onOpen} lang={lang}/></div>
      {planets.some(v=>v.retrograde)&&<div className="sky-heading"><p className="sky-small">℞ {L("Právě retrográdní","Currently retrograde")}: {planets.filter(v=>v.retrograde).map(v=>skyPlanetName(v.id,L)).join(", ")}</p><SkyHelp id="N15" onOpen={onOpen} lang={lang}/></div>}
    </details>
    <details className="sky-unfold"><summary>{L("Celý výklad a souvislosti","Full reading and context")}</summary><TogetherAstrologyOverview sky={sky} day={day} lens={sky.lens} lang={lang} timeZone={zone} onOpen={onOpen} onWeek={onWeek}/><details><summary>{L("Dva časy jedné oblohy","Two timescales of one sky")}</summary><p>{L(...LUNAR_PHASE_PRACTICES[sky.moon.index].text)}</p><p>{L("Luna promění svou tvář během měsíce. Pomalé planety nesou pozadí mnoha měsíců i let.","The Moon changes its face within a month. Slow planets carry the background of months and years.")}</p></details></details>
  </>;
  const personal=<><p className="sky-small">{L("Osobní souvislosti podle údajů narození. Symbolická mapa pro vlastní uvažování.","Personal context from birth details. A symbolic map for your own reflection.")}</p><SkyPersonalContext natal={details.natal} birth={journal.settings.birth} sky={sky} day={day} lens={sky.lens} lang={lang} onOpen={onOpen} compact/><div className="sky-links">{sky.lens==="hellenistic"&&<button type="button" onClick={()=>onOpen({kind:"hellenistic"})}>{L("Helénistický klíč","Hellenistic key")} ↗</button>}{sky.lens==="jyotish"&&<button type="button" onClick={()=>onOpen({kind:"jyotish"})}>{L("Džjótiš klíč","Jyotisha key")} ↗</button>}<button type="button" onClick={()=>onOpen({kind:"tradition"})}>{L("Klíč k tradicím","A key to the traditions")}</button></div></>;
  return <SkyExplore lang={lang} panels={[{id:"now",title:L("Co se děje","What's happening"),content:now},{id:"personal",title:L("Pro mě","For me"),content:personal},{id:"step",title:L("Jeden krok","One step"),content:<SkyStep orientation={orientation} lang={lang} day={day}><SkyNote storageKey={`day:${day}`} title={L("Můj vlastní krok pro tento den","My own step for this day")} journal={journal} update={update} ready={ready} lang={lang}/></SkyStep>}]}/>;
}
