import React,{useEffect,useRef,useState} from "react";
import {SKY_PRACTICES,skyPracticeInvitations} from "../product/skyContent.js";
import {canCastSkyDecision,makeSkyDecision,dueSkyDecisions,skyDateKey,skyQuote} from "../product/skyJournal.js";
import {SkyHeading,SkyEmpty,SkyHelp,SkyHelpContent,skyTime} from "./skyUi.jsx";

export function SkyPractice({sky,details,journal,update,ready,day,lang="cs",onOpen,onPlan,menstruation=false}){
  const L=(cs,en)=>lang==="en"?en:cs,settings=journal.settings,zone=settings.location.timeZone;
  const invitations=skyPracticeInvitations({tithi:details?.panchanga?.tithi??sky.jyotish.tithi,dayPlanet:details?.planetaryHours?.dayPlanet,
    retrogradeMercury:sky.planets.some(p=>p.id==="Mercury"&&p.retrograde),eclipse:details?.eclipses?.some(e=>skyDateKey(Date.parse(e.time),zone)===day),menstruation,settings});
  const rhythm=[{id:"morning",name:L("Ráno","Morning"),forms:settings.practices.guru?["guru"]:[]},{id:"day",name:L("Přes den","Daytime"),forms:settings.practices.dzambhala?["dzambhala"]:[]},{id:"evening",name:L("Večer","Evening"),forms:[...(settings.practices.guru?["guru"]:[]),...(settings.practices.protector?["protector"]:[])]}];
  const due=dueSkyDecisions(journal),weekday=new Date(`${day}T12:00:00Z`).getUTCDay();
  const tick=(key,checked)=>update(d=>({...d,practice:{...d.practice,[key]:{done:checked,time:Date.now(),day}}}));
  return <>
    <SkyHeading id="P01" onOpen={onOpen} lang={lang}>{L("Dnešní pozvání","Today's invitation")}</SkyHeading>
    {invitations.map(item=><article className="sky-practice-invite" key={item.key}><button type="button" onClick={()=>onOpen({kind:"practice",id:item.key})}>{L(...item.name)} <span aria-hidden="true">›</span></button><p className="sky-small">{L(...item.reason)}</p><p>{L(...item.text)}</p></article>)}
    <SkyHeading id="P05" onOpen={onOpen} lang={lang}>{L("Rytmus dne","The day's rhythm")}</SkyHeading>
    <p className="sky-small">{new Date(`${day}T12:00:00Z`).toLocaleDateString(lang==="en"?"en-GB":"cs-CZ",{timeZone:"UTC",day:"numeric",month:"long",year:"numeric"})}</p>
    <fieldset disabled={!ready}><div className="sky-rhythm">{rhythm.map(slot=><div key={slot.id}><h4>{slot.name}</h4>{slot.forms.length?slot.forms.map(key=>{const id=`${day}:${slot.id}:${key}`;return <label className="sky-check" key={key}><input type="checkbox" checked={Boolean(journal.practice[id]?.done)} onChange={e=>tick(id,e.target.checked)}/><span>{L(...SKY_PRACTICES[key].name)}</span><button type="button" className="sky-quiet" aria-label={`${L("Otevřít","Open")} ${L(...SKY_PRACTICES[key].name)}`} onClick={e=>{e.preventDefault();onOpen({kind:"practice",id:key});}}>›</button></label>;}):<p className="sky-small">{L("Volný prostor","Open space")}</p>}</div>)}</div>
      {weekday===Number(settings.practices.weeklyDay)&&<label className="sky-check"><input type="checkbox" checked={Boolean(journal.practice[`${day}:sadhana`]?.done)} onChange={e=>tick(`${day}:sadhana`,e.target.checked)}/><span>{L("Celá sádhana · můj týdenní den","Full sadhana · my weekly day")}</span></label>}
    </fieldset>
    <div className="sky-links"><button type="button" onClick={()=>onOpen({kind:"records",type:"practice"})}>{L("Moje předchozí praxe","My practice history")}</button></div>
    {journal.settings.modules.dice&&<><SkyHeading id="P08" onOpen={onOpen} lang={lang}>{L("Nechat prostor náhodě","Leave room for chance")}</SkyHeading><div className="sky-actions"><button type="button" onClick={()=>onOpen({kind:"decision"})}>{L("Položit otázku","Ask a question")}</button><button type="button" className="sky-quiet" onClick={()=>onOpen({kind:"records",type:"decisions"})}>{L("Moje rozhodnutí","My decisions")}</button></div>{due.map(d=><article className="sky-record" key={d.id}><span className="sky-small">{L("Čas na ohlédnutí","Time to reflect")}</span><h4>{d.question}</h4><p>{L("Bylo to dobré pro tebe i pro druhé?","Was it good for you and for others?")}</p><button type="button" onClick={()=>onOpen({kind:"decision",record:d})}>{L("Zapsat ohlédnutí","Write a reflection")}</button></article>)}</>}
    <div className="sky-heading"><blockquote>{skyQuote(day)}</blockquote><SkyHelp id="P11" onOpen={onOpen} lang={lang}/></div>
    {onPlan&&<><SkyHeading id="G07" onOpen={onOpen} lang={lang}>{L("Vzít obraz ven","Take the image outside")}</SkyHeading><p>{L("Na chvíli odlož výklad i telefon. Vyjdi pod skutečnou oblohu a nech dnešní obraz setkat se s tím, co právě žiješ.","Put the reading and phone aside for a while. Step under the actual sky and let today's image meet your lived experience.")}</p><button type="button" onClick={()=>onPlan({title:L("Chvíle pod oblohou","A moment under the sky"),date:day,minutes:10,note:L("Vyjdeme na chvíli ven. Každý pak může přinést jeden obraz, který v něm zůstal.","Step outside for a while, then each share one image that stayed with you.")})}>{L("Navrhnout chvíli venku","Propose time outside")}</button></>}
  </>;
}
export function SkyDecision({journal,update,ready,lang="cs",record}){
  const L=(cs,en)=>lang==="en"?en:cs,[question,setQuestion]=useState(record?.question||""),[choices,setChoices]=useState(record?.options?.join("\n")||""),[message,setMessage]=useState(""),[result,setResult]=useState(record?.result!=null?record:null),[decision,setDecision]=useState(record?.decision||""),[review,setReview]=useState(record?.review||""),[clock,setClock]=useState(Date.now());
  const [help,setHelp]=useState(null),openHelp=value=>setHelp(current=>current===value.id?null:value.id);
  const draftIdentity=useRef({id:record?.id||null,time:record?.time||Date.now()});
  useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),15000);return()=>clearInterval(timer);},[]);
  const last=journal.nostrils.at(-1),canCast=canCastSkyDecision(last,clock),zone=journal.settings.location.timeZone;
  const storeRecord=value=>update(d=>({...d,decisions:[...d.decisions.filter(v=>v.id!==value.id&&v.id!==record?.id),value]}));
  const cast=()=>{try{const value=makeSkyDecision({id:draftIdentity.current.id,question,options:choices.split("\n").map(v=>v.trim()).filter(Boolean),observation:last,timeZone:zone});if(storeRecord(value)){draftIdentity.current={id:value.id,time:value.time};setResult(value);setMessage("");}}catch(e){setMessage(e.message==="observation-required"?L("Nejdřív zapiš čerstvé pozorování obou dírek a příjemný pocit v těle.","First record a fresh balanced and comfortable observation."):L("Napiš otázku a dvě až šest různých možností, každou na vlastní řádek.","Write a question and two to six different choices, one per line."));}};
  const savePending=()=>{if(!question.trim())return;draftIdentity.current.id??=crypto.randomUUID();const value={...draftIdentity.current,timeZone:zone,question:question.trim(),options:choices.split("\n").map(v=>v.trim()).filter(Boolean),result:null,decision:"",review:""};if(storeRecord(value))setMessage(L("Otázka čeká v tvé historii.","The question is waiting in your history."));};
  return <fieldset disabled={!ready}>{result?<>
    <p className="sky-lead">{result.question}</p><SkyHeading id="P09" onOpen={openHelp} lang={lang} level={4}>{L("Náhodný podnět","Random prompt")}</SkyHeading>{help==="P09"&&<SkyHelpContent id="P09" lang={lang}/>}<h3>{result.options[result.result]}</h3><p className="sky-small">{skyTime(result.time,lang,result.timeZone,true)}</p>
    <label htmlFor="sky-decision-action">{L("Moje rozhodnutí a další krok","My decision and next step")}</label><textarea id="sky-decision-action" rows={3} value={decision} maxLength={2000} onChange={e=>setDecision(e.target.value)} placeholder={L("Můj skutečný krok…","My actual step…")}/>
    <SkyHeading id="P10" onOpen={openHelp} lang={lang} level={4}>{L("Bylo to dobré pro tebe i pro druhé?","Was it good for you and for others?")}</SkyHeading>{help==="P10"&&<SkyHelpContent id="P10" lang={lang}/>}<p className="sky-small">{L("Ohlédnutí od","Review from")} {result.reviewDate}</p><label className="sky-small" htmlFor="sky-decision-review">{L("Moje ohlédnutí","My reflection")}</label><textarea id="sky-decision-review" rows={3} value={review} maxLength={4000} onChange={e=>setReview(e.target.value)} placeholder={L("Když se vracím k tomuto kroku…","Returning to this step…")}/><button type="button" onClick={()=>{if(storeRecord({...result,decision:decision.trim(),review:review.trim(),reviewedAt:review.trim()?Date.now():null}))setMessage(L("Rozhodnutí a ohlédnutí uložené.","Decision and reflection saved."));}}>{L("Uložit","Save")}</button>
  </>:<><label htmlFor="sky-question">{L("Moje otázka","My question")}</label><textarea id="sky-question" rows={2} value={question} maxLength={1000} onChange={e=>setQuestion(e.target.value)} placeholder={L("Kudy se teď vydat…","Which way to take…")}/><label htmlFor="sky-choices">{L("Dvě až šest možností, každá na jednom řádku","Two to six choices, one per line")}</label><textarea id="sky-choices" rows={4} maxLength={1200} value={choices} onChange={e=>setChoices(e.target.value)} placeholder={L("Jedna možnost\nDruhá možnost","One choice\nAnother choice")}/><p>{canCast?L("Čerstvý záznam: obě dírky a příjemný pocit. Můžeš hodit.","Fresh record: both nostrils and a comfortable feeling. You can throw."):L("Hod se otevře po čerstvém záznamu obou dírek a příjemného pocitu v Těle. Otázku si můžeš nechat na později.","A throw opens after a fresh balanced and comfortable observation in Body. You can keep the question for later.")}</p><div className="sky-actions"><button type="button" className="sky-primary" disabled={!canCast||!question.trim()} onClick={cast}>{L("Hodit","Throw")}</button><button type="button" onClick={savePending} disabled={!question.trim()}>{L("Nechat na později","Keep for later")}</button></div></>}
    <p role="status" className="sky-status">{message}</p>
  </fieldset>;
}
export function SkyRecordHistory({type,journal,update,ready,lang="cs",onOpen}){
  const L=(cs,en)=>lang==="en"?en:cs,zone=journal.settings.location.timeZone;
  const entries=type==="practice"?Object.entries(journal.practice).filter(([,v])=>v.done).map(([id,v])=>({...v,id})):journal[type]||[];
  const remove=id=>{if(!ready||!window.confirm(L("Odstranit tento vlastní záznam z tohoto prohlížeče?","Remove this personal record from this browser?")))return;update(d=>{if(type==="practice"){const practice={...d.practice};delete practice[id];return {...d,practice};}return {...d,[type]:d[type].filter(v=>v.id!==id)};});};
  if(!entries.length)return <SkyEmpty text={L("Tady bude tvoje vlastní zkušenost, až ji zapíšeš.","Your own experience will appear here when you record it.")}/>;
  return [...entries].sort((a,b)=>b.time-a.time).map(n=><article className="sky-record" key={n.id}>
    <time>{skyTime(n.time,lang,n.timeZone||zone,true)}</time>
    {type==="nostrils"&&<><h4>{({left:L("Levá","Left"),right:L("Pravá","Right"),both:L("Obě","Both"),unknown:L("Nevím","Unsure")})[n.side]}</h4><p>{n.comfort?L("Příjemný pocit v těle","Comfortable in the body"):""}</p>{n.note&&<p>{n.note}</p>}</>}
    {type==="dreams"&&<><p>{n.text}</p>{n.regions?.length>0&&<button type="button" onClick={()=>onOpen({kind:"dream",record:n})}>{L("Obraz v těle","Body image")}</button>}</>}
    {type==="decisions"&&<><h3>{n.question}</h3><p>{n.result!=null?n.options[n.result]:L("Otázka čeká","Question waiting")}</p><button type="button" onClick={()=>onOpen({kind:"decision",record:n})}>{L("Otevřít a ohlédnout se","Open and reflect")}</button></>}
    {type==="practice"&&<p>{n.day} · {L(...(SKY_PRACTICES[n.id.split(":").at(-1)]?.name||[n.id,n.id]))}</p>}
    <button type="button" className="sky-quiet sky-small" onClick={()=>remove(n.id)} disabled={!ready}>{L("Odstranit zápis","Remove record")}</button>
  </article>);
}
