import React,{useEffect,useRef,useState} from "react";
import {validTimeZone} from "../product/skyJournal.js";
import {SKY_TRADITIONS,skyZodiac} from "../product/skyTraditions.js";
import {PersonalProfileSettings,openAppSources} from "./personalProfile.jsx";
import {SkyHeading} from "./skyUi.jsx";
import {SkyPlacePicker} from "./skyPlacePicker.jsx";
import {skyBirthAtLocation,skyBirthHasPlace,skyBirthUsesObservation,skyChangeObservation,skyPreparePlaceSettings} from "../product/skyPlaceSettings.js";

export function SkySettings({journal,update,ready,lang="cs",onOpen}){
  const L=(cs,en)=>lang==="en"?en:cs,[draft,replaceDraft]=useState(()=>skyPreparePlaceSettings(structuredClone(journal.settings))),[message,setMessage]=useState(""),[conflict,setConflict]=useState(false),[pending,setPending]=useState({location:false,birth:false}),[placeEpoch,setPlaceEpoch]=useState(0),dirty=useRef(false),baseline=useRef(JSON.stringify(journal.settings));
  const setDraft=value=>{dirty.current=true;replaceDraft(value);};
  useEffect(()=>{if(ready&&!dirty.current){replaceDraft(skyPreparePlaceSettings(structuredClone(journal.settings)));baseline.current=JSON.stringify(journal.settings);}},[ready,journal.settings]);
  const reload=()=>{replaceDraft(skyPreparePlaceSettings(structuredClone(journal.settings)));baseline.current=JSON.stringify(journal.settings);dirty.current=false;setConflict(false);setMessage("");setPending({location:false,birth:false});setPlaceEpoch(n=>n+1);};
  const field=(group,key,value)=>setDraft(s=>({...s,[group]:{...s[group],[key]:value}}));
  const sameBirthPlace=skyBirthUsesObservation(draft);
  const placePending=(group,value)=>{if(value)dirty.current=true;setPending(p=>p[group]===value?p:{...p,[group]:value});};
  const changeLocation=location=>setDraft(s=>skyChangeObservation(s,location,{preserveBirth:Boolean(journal.settings.birth.date&&skyBirthHasPlace(journal.settings.birth))}));
  const separateBirth=separate=>{setPending(p=>({...p,birth:false}));setDraft(s=>({...s,birth:separate?{...s.birth,locationMode:"independent"}:skyBirthAtLocation(s.birth,s.location)}));};
  const save=e=>{
    e?.preventDefault();if(!ready)return;if(JSON.stringify(journal.settings)!==baseline.current){setConflict(true);setMessage(L("Nastavení se mezitím změnilo v jiné kartě. Načti uloženou podobu, než ji upravíš.","Settings changed in another tab. Load the saved version before editing it."));return;}if(pending.location||(!sameBirthPlace&&pending.birth)){setMessage(L("Vyber nalezené místo nebo potvrď ručně zadané souřadnice.","Choose a matching place or confirm the manually entered coordinates."));return;}const prepared=skyPreparePlaceSettings(draft),loc=prepared.location,b=prepared.birth;
    if(loc.latitude===""||loc.longitude===""||!Number.isFinite(Number(loc.latitude))||Math.abs(Number(loc.latitude))>90||!Number.isFinite(Number(loc.longitude))||Math.abs(Number(loc.longitude))>180||!validTimeZone(loc.timeZone)){setMessage(L("Zkontroluj souřadnice a časové pásmo místa.","Check the location coordinates and time zone."));return;}
    if(b.date&&(!/^\d{4}-\d{2}-\d{2}$/.test(b.date)||b.date<"1900-01-01"||b.date>"2100-12-31")){setMessage(L("Datum narození musí být v podporovaném rozsahu 1900–2100.","Birth date must be within the supported 1900–2100 range."));return;}
    if(b.date&&(b.latitude===""||b.longitude===""||!Number.isFinite(Number(b.latitude))||Math.abs(Number(b.latitude))>90||!Number.isFinite(Number(b.longitude))||Math.abs(Number(b.longitude))>180||!validTimeZone(b.timeZone))){setMessage(L("Doplň souřadnice a historické pásmo místa narození.","Add the birth location coordinates and historical time zone."));return;}
    if(b.date&&b.timeKnown&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(b.time)){setMessage(L("Zadej známý čas narození nebo vypni přesný čas.","Enter the known birth time or switch off exact time."));return;}
    if(update(d=>({...d,settings:{...prepared,location:{...loc,latitude:Number(loc.latitude),longitude:Number(loc.longitude)}}}))){dirty.current=false;setConflict(false);setMessage(L("Nastavení Oblohy je uložené v tomto prohlížeči.","Sky settings are saved in this browser."));}
  };
  const requestNotifications=async()=>{if(!("Notification" in window)){setMessage(L("Tento prohlížeč nepodporuje upozornění. Ohlédnutí uvidíš při otevření aplikace.","This browser does not support notifications. Reviews remain visible when you open the app."));return;}const permission=await Notification.requestPermission();setDraft(d=>({...d,notifications:permission==="granted"}));setMessage(permission==="granted"?L("Upozornění povolena. Ulož nastavení.","Notifications allowed. Save settings."):L("Upozornění nepovolena. Připomínky zůstávají uvnitř aplikace.","Notifications not allowed. Reminders remain in the app."));};
  return <>
    <form onSubmit={save}><fieldset disabled={!ready}>
      <section className="sky-setting"><SkyHeading id="S03" onOpen={onOpen} lang={lang}>{L("Astrologické systémy","Astrological systems")}</SkyHeading>
        <label>{L("Výchozí systém","Default system")}<select value={draft.tradition} onChange={e=>setDraft(d=>({...d,tradition:e.target.value,zodiac:skyZodiac(e.target.value)}))}>{SKY_TRADITIONS.map(item=><option key={item.id} value={item.id}>{L(...item.title)}</option>)}</select></label>
        <p className="sky-small">{L("Mezi třemi systémy můžeš kdykoli přepínat v Obloze. Západní a helénistický pohled používají tropický zvěrokruh, džjótiša siderický s ajanámšou Lahiri.","Switch among the three systems at any time in Sky. Western and Hellenistic views use the tropical zodiac; Jyotisha uses a sidereal zodiac with Lahiri ayanamsa.")}</p>
        <details><summary>{L("Podrobnosti výpočtu","Calculation details")}</summary><label>{L("Lunární uzly","Lunar nodes")}<select value={draft.nodes} onChange={e=>setDraft({...draft,nodes:e.target.value})}><option value="mean">{L("Střední uzel","Mean node")}</option><option value="true">{L("Pravý uzel","True node")}</option></select></label></details>
      </section>
      <section className="sky-setting"><SkyHeading id="S08" onOpen={onOpen} lang={lang}>{L("Tibetský pohled","Tibetan perspective")}</SkyHeading><label className="sky-check"><input type="checkbox" checked={draft.tibetanEnabled} onChange={e=>setDraft(d=>({...d,tibetanEnabled:e.target.checked}))}/><span>{L("Přidat tibetský pohled do Oblohy","Add the Tibetan perspective to Sky")}</span></label>
        <p>{L("Krátký úvod do tradiční tibetské astrologie, práce s kalendářem a vlastní pozorování. Můžeš začít bez předchozích znalostí.","A short introduction to traditional Tibetan astrology, its calendar and your own observations. No prior knowledge is needed.")}</p><p className="sky-small">{L("Zobrazené fáze Luny jsou astronomické. Přesná tibetská data a osobní elementální výpočty tu zatím nejsou.","The Moon phases shown are astronomical. Exact Tibetan dates and personal elemental calculations are not available here yet.")}</p>
      </section>

      <section className="sky-setting"><SkyHeading id="S06" onOpen={onOpen} lang={lang}>{L("Místo a čas","Place and time")}</SkyHeading>
        <SkyPlacePicker key={`location-${placeEpoch}`} value={draft.location} onChange={changeLocation} onPending={value=>placePending("location",value)} label={L("Místo pozorování","Observing location")} lang={lang}/>
      </section>
      <section className="sky-setting" id="sky-birth-settings"><SkyHeading id="S07" onOpen={onOpen} lang={lang}>{L("Údaje narození","Birth details")}</SkyHeading><div className="sky-settings-grid">
        <label>{L("Datum narození","Birth date")}<input type="date" min="1900-01-01" max="2100-12-31" value={draft.birth.date} onInput={e=>field("birth","date",e.target.value)} onChange={e=>field("birth","date",e.target.value)}/></label>
        <label>{L("Čas narození","Birth time")}<input type="time" disabled={!draft.birth.timeKnown} value={draft.birth.time} onInput={e=>field("birth","time",e.target.value)} onChange={e=>field("birth","time",e.target.value)}/></label>
        <label className="sky-check wide"><input type="checkbox" checked={draft.birth.timeKnown} onChange={e=>field("birth","timeKnown",e.target.checked)}/><span>{L("Znám přesný čas narození","I know the exact birth time")}</span></label>
        <label className="sky-check wide"><input type="checkbox" checked={!sameBirthPlace} onChange={e=>separateBirth(e.target.checked)}/><span>{L("Jiné místo narození","Different birthplace")}</span></label>
        {sameBirthPlace?<p className="sky-small wide">{L("Místo narození:","Birthplace:")} {draft.location.name}. {L("Při uložení se použijí stejné souřadnice a pásmo. Pozdější změna místa pozorování je nepřepíše.","Saving uses the same coordinates and time zone. A later change of observing location will not overwrite them.")}</p>:<div className="wide"><SkyPlacePicker key={`birth-${placeEpoch}`} value={{name:draft.birth.place,latitude:draft.birth.latitude,longitude:draft.birth.longitude,timeZone:draft.birth.timeZone}} onChange={place=>setDraft(s=>({...s,birth:{...s.birth,place:place.name,latitude:place.latitude,longitude:place.longitude,timeZone:place.timeZone,locationMode:"independent"}}))} onPending={value=>placePending("birth",value)} label={L("Místo narození","Birthplace")} lang={lang}/></div>}
      </div><p className="sky-small">{L("Neznámý čas zůstane neznámý. Osobní údaje se tímto nastavením nesdílejí s partnerem.","An unknown time remains unknown. These settings do not share your birth details with a partner.")}</p></section>
      <datalist id="sky-time-zones">{["Europe/Prague","Europe/London","Europe/Paris","Europe/Lisbon","America/New_York","America/Los_Angeles","Asia/Kolkata","Asia/Kathmandu","Asia/Bangkok","Australia/Sydney","UTC"].map(z=><option key={z} value={z}/>)}</datalist>
      <section className="sky-setting"><SkyHeading id="S12" onOpen={onOpen} lang={lang}>{L("Zápisy a připomínky","Records and reminders")}</SkyHeading><p>{L("Zápisy Oblohy zůstávají u tvého účtu v tomto prohlížeči. Připomínku ohlédnutí uvidíš při otevření aplikace.","Sky records stay with your account in this browser. Review reminders appear when you open the app.")}</p><label className="sky-check"><input type="checkbox" checked={draft.notifications} onChange={e=>{if(e.target.checked)requestNotifications();else setDraft(d=>({...d,notifications:false}));}}/><span>{L("Upozornit na ohlédnutí, když je aplikace otevřená","Notify me about reviews while the app is open")}</span></label></section>
      <div className="sky-actions"><button type="submit" className="sky-primary">{L("Uložit nastavení Oblohy","Save Sky settings")}</button>{conflict&&<button type="button" onClick={reload}>{L("Načíst uložené nastavení","Load saved settings")}</button>}</div><p role="status" className="sky-status">{message}</p>
    </fieldset></form>
    <SkyHeading id="S01" onOpen={onOpen} lang={lang}>{L("Tvůj profil","Your profile")}</SkyHeading><PersonalProfileSettings lang={lang}/>

    <section className="sky-setting"><h3>{L("Moje uložené zápisy","My saved records")}</h3><p className="sky-small">{L("Vlastní pozorování, záměry i dřívější zápisy najdeš pohromadě. Zůstávají soukromé.","Your observations, intentions and earlier records stay together and remain private.")}</p><button type="button" onClick={()=>onOpen({kind:"archive"})}>{L("Prohlédnout moje zápisy","View my records")}</button></section>
    <section className="sky-setting"><SkyHeading id="S11" onOpen={onOpen} lang={lang}>{L("Jazyk","Language")}</SkyHeading><div className="sky-actions">{[["cs","Česky"],["en","English"]].map(([value,title])=><button type="button" key={value} aria-pressed={lang===value} onClick={()=>window.dispatchEvent(new CustomEvent("tm-set-language",{detail:{lang:value}}))}>{title}</button>)}</div></section>
    <section className="sky-setting"><SkyHeading id="S14" onOpen={onOpen} lang={lang}>{L("Společný kalendář","Shared calendar")}</SkyHeading><button type="button" onClick={()=>window.dispatchEvent(new CustomEvent("tm-open-personal-settings",{detail:{section:"calendar"}}))}>{L("Nastavit Google kalendář","Set up Google Calendar")}</button></section>
    <section className="sky-setting"><SkyHeading id="S13" onOpen={onOpen} lang={lang}>{L("Zdroje","Sources")}</SkyHeading><button type="button" onClick={()=>openAppSources("obloha")}>{L("Otevřít zdroje a výpočty","Open sources and methods")}</button></section>
  </>;
}
