import React,{useEffect,useRef,useState} from "react";
import {validTimeZone,SKY_PRACTICE_DAYS} from "../product/skyJournal.js";
import {SKY_PRACTICES} from "../product/skyContent.js";
import {PersonalProfileSettings,openAppSources} from "./personalProfile.jsx";
import {SkyHeading} from "./skyUi.jsx";

export function SkySettings({journal,update,ready,lang="cs",onOpen}){
  const L=(cs,en)=>lang==="en"?en:cs,[draft,replaceDraft]=useState(()=>structuredClone(journal.settings)),[message,setMessage]=useState(""),[conflict,setConflict]=useState(false),dirty=useRef(false),baseline=useRef(JSON.stringify(journal.settings));
  const setDraft=value=>{dirty.current=true;replaceDraft(value);};
  useEffect(()=>{if(ready&&!dirty.current){replaceDraft(structuredClone(journal.settings));baseline.current=JSON.stringify(journal.settings);}},[ready,journal.settings]);
  const reload=()=>{replaceDraft(structuredClone(journal.settings));baseline.current=JSON.stringify(journal.settings);dirty.current=false;setConflict(false);setMessage("");};
  const field=(group,key,value)=>setDraft(s=>({...s,[group]:{...s[group],[key]:value}}));
  const save=e=>{
    e?.preventDefault();if(!ready)return;if(JSON.stringify(journal.settings)!==baseline.current){setConflict(true);setMessage(L("Nastavení se mezitím změnilo v jiné kartě. Načti uloženou podobu, než ji upravíš.","Settings changed in another tab. Load the saved version before editing it."));return;}const loc=draft.location,b=draft.birth;
    if(loc.latitude===""||loc.longitude===""||!Number.isFinite(Number(loc.latitude))||Math.abs(Number(loc.latitude))>90||!Number.isFinite(Number(loc.longitude))||Math.abs(Number(loc.longitude))>180||!validTimeZone(loc.timeZone)){setMessage(L("Zkontroluj souřadnice a časové pásmo místa.","Check the location coordinates and time zone."));return;}
    if(b.date&&(!/^\d{4}-\d{2}-\d{2}$/.test(b.date)||b.date<"1900-01-01"||b.date>"2100-12-31")){setMessage(L("Datum narození musí být v podporovaném rozsahu 1900–2100.","Birth date must be within the supported 1900–2100 range."));return;}
    if(b.date&&(b.latitude===""||b.longitude===""||!Number.isFinite(Number(b.latitude))||Math.abs(Number(b.latitude))>90||!Number.isFinite(Number(b.longitude))||Math.abs(Number(b.longitude))>180||!validTimeZone(b.timeZone))){setMessage(L("Doplň souřadnice a historické pásmo místa narození.","Add the birth location coordinates and historical time zone."));return;}
    if(b.date&&b.timeKnown&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(b.time)){setMessage(L("Zadej známý čas narození nebo vypni přesný čas.","Enter the known birth time or switch off exact time."));return;}
    if(update(d=>({...d,settings:{...draft,location:{...loc,latitude:Number(loc.latitude),longitude:Number(loc.longitude)}}}))){dirty.current=false;setConflict(false);setMessage(L("Nastavení Oblohy je uložené v tomto prohlížeči.","Sky settings are saved in this browser."));}
  };
  const requestNotifications=async()=>{if(!("Notification" in window)){setMessage(L("Tento prohlížeč nepodporuje upozornění. Ohlédnutí uvidíš při otevření aplikace.","This browser does not support notifications. Reviews remain visible when you open the app."));return;}const permission=await Notification.requestPermission();setDraft(d=>({...d,notifications:permission==="granted"}));setMessage(permission==="granted"?L("Upozornění povolena. Ulož nastavení.","Notifications allowed. Save settings."):L("Upozornění nepovolena. Připomínky zůstávají uvnitř aplikace.","Notifications not allowed. Reminders remain in the app."));};
  return <>
    <SkyHeading id="S01" onOpen={onOpen} lang={lang}>{L("Tvůj profil","Your profile")}</SkyHeading><PersonalProfileSettings lang={lang}/>
    <form onSubmit={save}><fieldset disabled={!ready}>
      <section className="sky-setting"><SkyHeading id="S06" onOpen={onOpen} lang={lang}>{L("Místo a čas","Place and time")}</SkyHeading><div className="sky-settings-grid">
        <label className="wide">{L("Místo pozorování","Observing location")}<input autoComplete="off" value={draft.location.name} maxLength={120} onChange={e=>field("location","name",e.target.value)}/></label>
        <label>{L("Zeměpisná šířka","Latitude")}<input type="number" inputMode="decimal" min="-90" max="90" step="any" value={draft.location.latitude} onChange={e=>field("location","latitude",e.target.value)}/></label>
        <label>{L("Zeměpisná délka","Longitude")}<input type="number" inputMode="decimal" min="-180" max="180" step="any" value={draft.location.longitude} onChange={e=>field("location","longitude",e.target.value)}/></label>
        <label className="wide">{L("Časové pásmo","Time zone")}<input list="sky-time-zones" value={draft.location.timeZone} onChange={e=>field("location","timeZone",e.target.value)} placeholder="Europe/Prague"/></label>
      </div></section>
      <section className="sky-setting" id="sky-birth-settings"><SkyHeading id="S07" onOpen={onOpen} lang={lang}>{L("Údaje narození","Birth details")}</SkyHeading><div className="sky-settings-grid">
        <label>{L("Datum narození","Birth date")}<input type="date" min="1900-01-01" max="2100-12-31" value={draft.birth.date} onInput={e=>field("birth","date",e.target.value)} onChange={e=>field("birth","date",e.target.value)}/></label>
        <label>{L("Čas narození","Birth time")}<input type="time" disabled={!draft.birth.timeKnown} value={draft.birth.time} onInput={e=>field("birth","time",e.target.value)} onChange={e=>field("birth","time",e.target.value)}/></label>
        <label className="sky-check wide"><input type="checkbox" checked={draft.birth.timeKnown} onChange={e=>field("birth","timeKnown",e.target.checked)}/><span>{L("Znám přesný čas narození","I know the exact birth time")}</span></label>
        <label className="wide">{L("Místo narození","Birthplace")}<input value={draft.birth.place} maxLength={120} onChange={e=>field("birth","place",e.target.value)}/></label>
        <label>{L("Zeměpisná šířka","Latitude")}<input type="number" inputMode="decimal" step="any" min="-90" max="90" value={draft.birth.latitude} onChange={e=>field("birth","latitude",e.target.value)}/></label>
        <label>{L("Zeměpisná délka","Longitude")}<input type="number" inputMode="decimal" step="any" min="-180" max="180" value={draft.birth.longitude} onChange={e=>field("birth","longitude",e.target.value)}/></label>
        <label className="wide">{L("Pásmo místa narození","Birthplace time zone")}<input list="sky-time-zones" value={draft.birth.timeZone} onChange={e=>field("birth","timeZone",e.target.value)}/></label>
      </div><p className="sky-small">{L("Neznámý čas zůstane neznámý. Osobní údaje se tímto nastavením nesdílejí s partnerem.","An unknown time remains unknown. These settings do not share your birth details with a partner.")}</p></section>
      <datalist id="sky-time-zones">{["Europe/Prague","Europe/London","Europe/Paris","Europe/Lisbon","America/New_York","America/Los_Angeles","Asia/Kolkata","Asia/Kathmandu","Asia/Bangkok","Australia/Sydney","UTC"].map(z=><option key={z} value={z}/>)}</datalist>
      <section className="sky-setting"><SkyHeading id="S03" onOpen={onOpen} lang={lang}>{L("Způsoby čtení","Ways of reading")}</SkyHeading>{[["jyotish","Džjótiša","Jyotisha"],["hellenistic","Helénistický klíč","Hellenistic key"],["western","Západní tropický klíč","Western tropical key"]].map(([id,cs,en])=><label key={id} className="sky-check"><input type="checkbox" checked={draft.traditions[id]} onChange={e=>field("traditions",id,e.target.checked)}/><span>{L(cs,en)}</span></label>)}
        <div className="sky-settings-grid"><label>{L("Výchozí kolo","Default wheel")}<select value={draft.zodiac} onChange={e=>setDraft({...draft,zodiac:e.target.value})}><option value="sidereal">{L("Siderický · Lahiri","Sidereal · Lahiri")}</option><option value="tropical">{L("Tropický","Tropical")}</option></select></label><label>{L("Lunární uzly","Lunar nodes")}<select value={draft.nodes} onChange={e=>setDraft({...draft,nodes:e.target.value})}><option value="mean">{L("Střední uzel","Mean node")}</option><option value="true">{L("Pravý uzel","True node")}</option></select></label></div>
      </section>
      <section className="sky-setting"><SkyHeading id="S08" onOpen={onOpen} lang={lang}>{L("Dny praxe","Practice days")}</SkyHeading><div className="sky-actions" role="group" aria-label={L("Sledované lunární dny","Selected lunar days")}>{SKY_PRACTICE_DAYS.map(n=><button type="button" key={n} aria-pressed={draft.practiceDays.includes(n)} onClick={()=>setDraft(d=>({...d,practiceDays:d.practiceDays.includes(n)?d.practiceDays.filter(x=>x!==n):[...d.practiceDays,n].sort((a,b)=>a-b)}))}>{n}</button>)}</div><p className="sky-small">{L("Orientačně podle tithi. Přesný tibetský kalendář zatím není zapnutý.","Approximate dates from tithi. A verified Tibetan calendar is not enabled yet.")}</p></section>
      <section className="sky-setting"><SkyHeading id="S09" onOpen={onOpen} lang={lang}>{L("Moje praxe","My practice")}</SkyHeading>{["guru","dzambhala","protector","vajrayogini"].map(id=><label className="sky-check" key={id}><input type="checkbox" checked={draft.practices[id]} onChange={e=>field("practices",id,e.target.checked)}/><span>{L(...SKY_PRACTICES[id].name)}</span></label>)}
        <label className="sky-check"><input type="checkbox" checked={draft.practices.mercury} onChange={e=>field("practices","mercury",e.target.checked)}/><span>{L("Při retrográdním Merkuru připomenout revizi","Remind me to revise during Mercury retrograde")}</span></label>
        <label className="sky-check"><input type="checkbox" checked={draft.practices.eclipses} onChange={e=>field("practices","eclipses",e.target.checked)}/><span>{L("Zatmění jako čas praxe","Eclipses as a time for practice")}</span></label>
        <label>{L("Den pro celou sádhanu","Day for a full sadhana")}<select value={draft.practices.weeklyDay} onChange={e=>field("practices","weeklyDay",Number(e.target.value))}>{[[1,"Pondělí","Monday"],[2,"Úterý","Tuesday"],[3,"Středa","Wednesday"],[4,"Čtvrtek","Thursday"],[5,"Pátek","Friday"],[6,"Sobota","Saturday"],[0,"Neděle","Sunday"]].map(([value,cs,en])=><option key={value} value={value}>{L(cs,en)}</option>)}</select></label>
      </section>
      <section className="sky-setting"><SkyHeading id="S10" onOpen={onOpen} lang={lang}>{L("Co chci sledovat","What I want to explore")}</SkyHeading>{[["swara","Švarodaja · model k ověření","Swara · model to verify"],["cycle","Cyklus vedle Luny","Cycle beside the Moon"],["dream","Ranní sny","Morning dreams"],["dice","Kostka a ohlédnutí","Decision ritual and review"]].map(([id,cs,en])=><label className="sky-check" key={id}><input type="checkbox" checked={draft.modules[id]} onChange={e=>field("modules",id,e.target.checked)}/><span>{L(cs,en)}</span></label>)}</section>
      <section className="sky-setting"><SkyHeading id="S12" onOpen={onOpen} lang={lang}>{L("Zápisy a připomínky","Records and reminders")}</SkyHeading><p>{L("Zápisy Oblohy zůstávají u tvého účtu v tomto prohlížeči. Připomínku ohlédnutí uvidíš při otevření aplikace.","Sky records stay with your account in this browser. Review reminders appear when you open the app.")}</p><label className="sky-check"><input type="checkbox" checked={draft.notifications} onChange={e=>{if(e.target.checked)requestNotifications();else setDraft(d=>({...d,notifications:false}));}}/><span>{L("Upozornit na ohlédnutí, když je aplikace otevřená","Notify me about reviews while the app is open")}</span></label></section>
      <div className="sky-actions"><button type="submit" className="sky-primary">{L("Uložit nastavení Oblohy","Save Sky settings")}</button>{conflict&&<button type="button" onClick={reload}>{L("Načíst uložené nastavení","Load saved settings")}</button>}</div><p role="status" className="sky-status">{message}</p>
    </fieldset></form>
    <section className="sky-setting"><SkyHeading id="S11" onOpen={onOpen} lang={lang}>{L("Jazyk","Language")}</SkyHeading><div className="sky-actions">{[["cs","Česky"],["en","English"]].map(([value,title])=><button type="button" key={value} aria-pressed={lang===value} onClick={()=>window.dispatchEvent(new CustomEvent("tm-set-language",{detail:{lang:value}}))}>{title}</button>)}</div></section>
    <section className="sky-setting"><SkyHeading id="S14" onOpen={onOpen} lang={lang}>{L("Společný kalendář","Shared calendar")}</SkyHeading><button type="button" onClick={()=>window.dispatchEvent(new CustomEvent("tm-open-personal-settings",{detail:{section:"calendar"}}))}>{L("Nastavit Google kalendář","Set up Google Calendar")}</button></section>
    <section className="sky-setting"><SkyHeading id="S13" onOpen={onOpen} lang={lang}>{L("Zdroje","Sources")}</SkyHeading><button type="button" onClick={()=>openAppSources("obloha")}>{L("Otevřít zdroje a výpočty","Open sources and methods")}</button></section>
  </>;
}
