import React,{useMemo,useState} from "react";
import {TIBETAN_INTRO,TIBETAN_PILLARS,TIBETAN_CALENDAR_NOTE,TIBETAN_OBSERVATIONS} from "../product/skyTibetan.js";
import {astrologyAt,dateForAstrology} from "../product/togetherAstrology.js";
import {addSkyDays} from "../product/skyJournal.js";
import {MOON_NAMES} from "../product/togetherMoon.js";
import {SkyMoon} from "./skyNebe.jsx";
import {SkyExplore,SkyNote} from "./skyExplore.jsx";
import {skyTime} from "./skyUi.jsx";
import {openAppSources} from "./personalProfile.jsx";

export function SkyTibetan({sky,day,journal,update,ready,lang="cs",period=false,onDay}){
  const L=(cs,en)=>lang==="en"?en:cs,zone=journal.settings.location.timeZone;
  const [selectedPillar,setSelectedPillar]=useState(TIBETAN_PILLARS[0].id),[selectedObservation,setSelectedObservation]=useState(TIBETAN_OBSERVATIONS[0].id);
  const pillar=TIBETAN_PILLARS.find(item=>item.id===selectedPillar),observation=TIBETAN_OBSERVATIONS.find(item=>item.id===selectedObservation);
  const observations=Object.entries(journal.intentions).filter(([k,v])=>k.startsWith("tibetan:")&&(typeof v==="string"?v:v.text)).sort(([a],[b])=>b.localeCompare(a));
  const days=useMemo(()=>period?Array.from({length:7},(_,i)=>{const d=addSkyDays(day,i);if(d>"2100-12-31")return {day:d,moon:null};try{const instant=dateForAstrology(d,12,zone);return {day:d,moon:instant?astrologyAt(instant,"western",{skipNextPhase:true}).moon:null};}catch{return {day:d,moon:null};}}):[],[day,zone,period]);
  const stamp=d=>new Date(`${d}T12:00:00Z`).toLocaleDateString(lang==="en"?"en-GB":"cs-CZ",{timeZone:"UTC",day:"numeric",month:"short"});
  const now=<>
    {period?<><h3>{L("Sedm dnů Luny","Seven days of the Moon")}</h3><div className="sky-tibetan-days">{days.map(d=><button type="button" key={d.day} disabled={!d.moon} onClick={()=>onDay(d.day)} aria-label={`${stamp(d.day)}${d.moon?`, ${L(...MOON_NAMES[d.moon.index])}`:""}`}><span>{stamp(d.day)}</span>{d.moon&&<SkyMoon phase={d.moon.phase} light={d.moon.light} label={L(...MOON_NAMES[d.moon.index])}/>}</button>)}</div><p className="sky-small">{L("Astronomické fáze v místní poledne. Výběr dne otevře podrobnosti a vlastní pozorování.","Astronomical phases at local noon. Choose a day for its details and your own observation.")}</p></>:<div className="sky-tibetan-moon"><SkyMoon phase={sky.moon.phase} light={sky.moon.light} label={L(...MOON_NAMES[sky.moon.index])}/><div><span className="sky-label">{L("Luna ve vybraném čase","Moon at the selected time")}</span><h3>{L(...MOON_NAMES[sky.moon.index])}</h3><p className="sky-small">{sky.moon.light} % {L("osvětleného viditelného disku","of the visible disc illuminated")}</p></div></div>}
    <p className="sky-small">{L("Astronomická Luna · tibetské datum zde zatím nepočítáme.","Astronomical Moon · Tibetan dates are not calculated here.")}</p>
    {sky.moon.next&&<div className="sky-change-single"><span className="sky-label">{L("Další hlavní fáze","Next principal phase")}</span><h3>{L(...MOON_NAMES[sky.moon.nextIndex])}</h3><p className="sky-small">{skyTime(sky.moon.next,lang,zone,true)}</p><button type="button" className="sky-quiet" onClick={()=>onDay(sky.moon.next)}>{L("Přejít k této fázi","Go to this phase")} →</button></div>}
    <details className="sky-unfold"><summary>{L("Jak číst tento kalendář","How to read this calendar")}</summary><p>{L(...TIBETAN_CALENDAR_NOTE)}</p></details>
  </>;
  const tradition=<><p>{L(...TIBETAN_INTRO)}</p><div className="sky-tibetan-choices" aria-label={L("Části tibetské tradice","Parts of the Tibetan tradition")}>{TIBETAN_PILLARS.map(item=><button type="button" key={item.id} aria-pressed={pillar.id===item.id} onClick={()=>setSelectedPillar(item.id)}>{L(...item.title)}</button>)}</div><div className="sky-tibetan-focus" key={pillar.id}><h3>{L(...pillar.title)}</h3><p>{L(...pillar.text)}</p><details><summary>{L("Co z toho dál poznat","Explore further")}</summary>{pillar.help[lang==="en"?"en":"cs"].map((text,i)=><p key={i}>{text}</p>)}</details></div><div className="sky-links"><button type="button" onClick={()=>openAppSources("obloha")}>{L("Zdroje a tradiční kalendáře","Sources and traditional calendars")} →</button></div></>;
  const step=<><p className="sky-small">{L("Autorské podněty aplikace pro vlastní pozorování.","The app's original prompts for your own observation.")}</p><div className="sky-tibetan-observations" aria-label={L("Vybrat jednu chvíli pozornosti","Choose a moment of attention")}>{TIBETAN_OBSERVATIONS.map(item=><button type="button" key={item.id} aria-pressed={observation.id===item.id} onClick={()=>setSelectedObservation(item.id)}>{L(...item.title)}</button>)}</div><div className="sky-tibetan-focus" key={observation.id}><h3>{L(...observation.title)}</h3><p className="sky-step-text">{L(...observation.text)}</p></div><SkyNote storageKey={`tibetan:${day}`} title={L("Čeho si dnes všímám","What I notice today")} journal={journal} update={update} ready={ready} lang={lang} saveLabel={L("Uložit pozorování","Save observation")} placeholder={L("Jeden postřeh stačí…","One observation is enough…")}/>
    {observations.length>0&&<details className="sky-tibetan-history"><summary>{L("Moje pozorování","My observations")} · {observations.length}</summary>{observations.slice(0,14).map(([k,row])=><button type="button" key={k} onClick={()=>onDay(k.slice(8))}><span className="sky-small">{stamp(k.slice(8))}</span><p>{typeof row==="string"?row:row.text}</p></button>)}</details>}
  </>;
  return <section className="sky-tibetan" aria-label={L("Tibetský pohled","Tibetan perspective")}><style>{TIBETAN_CSS}</style><h2>{L("Tibetský pohled","Tibetan perspective")}</h2><SkyExplore lang={lang} panels={[{id:"now",title:L("Luna","Moon"),content:now},{id:"tradition",title:L("Tradice","Tradition"),content:tradition},{id:"step",title:L("Jeden krok","One step"),content:step}]}/></section>;
}
const TIBETAN_CSS=`
.tg-astrology .sky-tibetan h2{font:32px/1.2 var(--tm-font-display);margin:20px 0}.tg-astrology .sky-tibetan-moon{display:flex;align-items:center;gap:24px;margin:26px 0}.tg-astrology .sky-tibetan-moon>svg{flex:0 0 112px;margin:0!important}.tg-astrology .sky-tibetan-moon h3{margin:4px 0;font-size:25px}.tg-astrology .sky-tibetan-moon p{margin:6px 0}.tg-astrology .sky-tibetan-days{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:4px;margin:20px 0}.tg-astrology .sky-tibetan-days button{padding:10px 2px;border:0;border-bottom:1px solid var(--astro-line);border-radius:0}.tg-astrology .sky-tibetan-days svg{width:44px;height:44px;margin:5px auto!important}.tg-astrology .sky-tibetan-choices{display:grid;grid-template-columns:1fr 1fr;gap:4px 20px;margin:24px 0}.tg-astrology .sky-tibetan-choices button,.tg-astrology .sky-tibetan-observations button{border:0;border-bottom:1px solid var(--astro-line);border-radius:0;text-align:left;padding:12px 0;font:19px/1.35 var(--tm-font-display)}.tg-astrology .sky-tibetan-choices button[aria-pressed=true],.tg-astrology .sky-tibetan-observations button[aria-pressed=true]{border-bottom-color:var(--astro-ink)}.tg-astrology .sky-tibetan-observations{display:flex;gap:15px;margin:14px 0 26px}.tg-astrology .sky-tibetan-observations button{flex:1;font-size:17px}.tg-astrology .sky-tibetan-focus{animation:sky-layer-in .2s ease-out;min-height:170px;margin:24px 0}.tg-astrology .sky-tibetan-history p{white-space:pre-wrap}.tg-astrology .sky-tibetan-history button{text-align:left;width:100%;border:0;border-top:1px solid var(--astro-line);border-radius:0}.tg-astrology .sky-change-single{margin:30px 0}.tg-astrology .sky-change-single h3{margin:8px 0}.tg-astrology .sky-change-single .sky-quiet{padding-inline:0}
@media(min-width:600px){.tg-astrology .sky-tibetan-days{grid-template-columns:repeat(7,minmax(0,1fr))}}
`;
