import React,{useId,useMemo,useState} from "react";
import {TIBETAN_INTRO,TIBETAN_PILLARS,TIBETAN_CALENDAR_NOTE,TIBETAN_OBSERVATIONS} from "../product/skyTibetan.js";
import {astrologyAt,dateForAstrology} from "../product/togetherAstrology.js";
import {addSkyDays} from "../product/skyJournal.js";
import {MOON_NAMES} from "../product/togetherMoon.js";
import {SkyMoon} from "./skyNebe.jsx";
import {skyTime} from "./skyUi.jsx";
import {openAppSources} from "./personalProfile.jsx";

export function SkyTibetan({sky,day,journal,update,ready,lang="cs",period=false,onDay}){
  const L=(cs,en)=>lang==="en"?en:cs,id=useId(),zone=journal.settings.location.timeZone;
  const [drafts,setDrafts]=useState({}),[messages,setMessages]=useState({});
  const key=`tibetan:${day}`,saved=journal.intentions[key]?.text||"",draft=drafts[key],value=draft?.text??saved;
  const observations=Object.entries(journal.intentions).filter(([k,v])=>k.startsWith("tibetan:")&&v.text).sort(([a],[b])=>b.localeCompare(a));
  const days=useMemo(()=>period?Array.from({length:7},(_,i)=>{const d=addSkyDays(day,i),instant=dateForAstrology(d,12,zone);return {day:d,moon:instant?astrologyAt(instant,"western",{skipNextPhase:true}).moon:null};}):[],[day,zone,period]);
  const stamp=d=>new Date(`${d}T12:00:00Z`).toLocaleDateString(lang==="en"?"en-GB":"cs-CZ",{timeZone:"UTC",day:"numeric",month:"short"});
  const save=()=>{
    if(draft&&draft.base!==saved){setMessages(m=>({...m,[key]:L("Zápis se změnil v jiné kartě. Porovnej ho s rozepsaným textem před uložením.","This note changed in another tab. Compare it with your draft before saving.")}));return;}
    const text=value.trim();
    if(update(doc=>({...doc,intentions:{...doc.intentions,[key]:{text,time:Date.now()}}}))){setDrafts(d=>({...d,[key]:{text,base:text}}));setMessages(m=>({...m,[key]:L("Pozorování uložené.","Observation saved.")}));}
    else setMessages(m=>({...m,[key]:L("Uložení se nepodařilo. Rozepsaný text zůstává tady.","Saving failed. Your draft remains here.")}));
  };
  return <section className="sky-tibetan" aria-label={L("Tibetský pohled","Tibetan perspective")}>
    <style>{`.tg-astrology .sky-tibetan h2{font:32px/1.2 var(--tm-font-display)}.tg-astrology .sky-tibetan-moon{display:flex;align-items:center;gap:24px;margin:26px 0}.tg-astrology .sky-tibetan-moon>svg{flex:0 0 112px;margin:0!important}.tg-astrology .sky-tibetan-moon h3{margin:0;font-size:25px}.tg-astrology .sky-tibetan-moon p{margin:6px 0}.tg-astrology .sky-tibetan-path{margin:24px 0}.tg-astrology .sky-tibetan-path details{padding:12px 0;border-top:1px solid var(--astro-line)}.tg-astrology .sky-tibetan-path summary{font:22px/1.35 var(--tm-font-display);padding:6px 0}.tg-astrology .sky-tibetan-days{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:4px;margin:20px 0}.tg-astrology .sky-tibetan-days button{padding:10px 2px;border:0;border-bottom:1px solid var(--astro-line);border-radius:0}.tg-astrology .sky-tibetan-days svg{width:44px;height:44px;margin:5px auto!important}.tg-astrology .sky-tibetan-note{margin:30px 0}.tg-astrology .sky-tibetan-note label{font:24px var(--tm-font-display)}.tg-astrology .sky-tibetan-note textarea{margin:12px 0}.tg-astrology .sky-tibetan-note details p{white-space:pre-wrap}.tg-astrology .sky-tibetan-history p{white-space:pre-wrap}.tg-astrology .sky-tibetan-history button{text-align:left;width:100%;border:0;border-top:1px solid var(--astro-line);border-radius:0}@media(min-width:600px){.tg-astrology .sky-tibetan-days{grid-template-columns:repeat(7,minmax(0,1fr))}}`}</style>
    <h2>{L("Tibetský pohled","Tibetan perspective")}</h2><p>{L(...TIBETAN_INTRO)}</p>
    {period?<><h3>{L("Sedm dnů Luny","Seven days of the Moon")}</h3><p className="sky-small">{L("Astronomické fáze od vybraného dne. Dotkni se dne a otevři vlastní pozorování.","Astronomical phases from the selected day. Choose a day to open your observation.")}</p><div className="sky-tibetan-days">{days.map(d=><button type="button" key={d.day} disabled={!d.moon} onClick={()=>onDay(d.day)} aria-label={`${stamp(d.day)}${d.moon?`, ${L(...MOON_NAMES[d.moon.index])}`:""}`}><span>{stamp(d.day)}</span>{d.moon&&<SkyMoon phase={d.moon.phase} light={d.moon.light} label={L(...MOON_NAMES[d.moon.index])}/>}</button>)}</div></>:<><div className="sky-tibetan-moon"><SkyMoon phase={sky.moon.phase} light={sky.moon.light} label={L(...MOON_NAMES[sky.moon.index])}/><div><span className="sky-label">{L("Dnešní Luna","Today's Moon")}</span><h3>{L(...MOON_NAMES[sky.moon.index])}</h3><p className="sky-small">{sky.moon.light} % {L("osvětleného viditelného disku","of the visible disc illuminated")}</p></div></div><p className="sky-small">{L("Další hlavní fáze","Next principal phase")}: {L(...MOON_NAMES[sky.moon.nextIndex])} · {skyTime(sky.moon.next,lang,zone,true)}</p></>}
    <details><summary>{L("Jak číst kalendář","How to read the calendar")}</summary><p>{L(...TIBETAN_CALENDAR_NOTE)}</p></details>
    <div className="sky-tibetan-path"><h3>{L("Zorientovat se v tradici","Find your way through the tradition")}</h3>{TIBETAN_PILLARS.map((pillar,i)=><details key={pillar.id}><summary>{i+1}. {L(...pillar.title)}</summary><p>{L(...pillar.text)}</p>{pillar.help[lang==="en"?"en":"cs"].map((text,j)=><p className="sky-small" key={j}>{text}</p>)}</details>)}</div>
    {!period&&<><h3>{L("Jedna chvíle pozornosti","A moment of attention")}</h3><p className="sky-small">{L("Podněty aplikace pro vlastní pozorování.","The app's prompts for your own observation.")}</p>{TIBETAN_OBSERVATIONS.map(item=><details key={item.id}><summary>{L(...item.title)}</summary><p>{L(...item.text)}</p></details>)}<div className="sky-tibetan-note"><label htmlFor={id}>{L("Čeho si dnes všímám","What I notice today")}</label><textarea id={id} rows={3} maxLength={2000} disabled={!ready} value={value} placeholder={L("Jeden postřeh stačí…","One observation is enough…")} onChange={e=>{setDrafts(d=>({...d,[key]:{text:e.target.value,base:d[key]?.base??saved}}));setMessages(m=>({...m,[key]:""}));}}/><button type="button" disabled={!ready||value===saved} onClick={save}>{L("Uložit pozorování","Save observation")}</button>{draft&&draft.base!==saved&&<details><summary>{L("Porovnat uložený zápis","Compare the saved note")}</summary><p>{saved}</p><button type="button" onClick={()=>setDrafts(d=>({...d,[key]:{...d[key],base:saved}}))}>{L("Použít můj rozepsaný text","Use my draft")}</button></details>}<p role="status" className="sky-status">{messages[key]}</p></div></>}
    {observations.length>0&&<details className="sky-tibetan-history"><summary>{L("Moje pozorování","My observations")} · {observations.length}</summary>{observations.slice(0,14).map(([k,row])=><button type="button" key={k} onClick={()=>onDay(k.slice(8))}><span className="sky-small">{stamp(k.slice(8))}</span><p>{row.text}</p></button>)}</details>}
    <div className="sky-links"><button type="button" onClick={()=>openAppSources("obloha")}>{L("Zdroje a tradiční kalendáře","Sources and traditional calendars")} →</button></div>
  </section>;
}
