import React,{useEffect,useRef,useState} from 'react';
import {lookupSource,metadataPatch,safeSourceUrl,sourceSearchLink} from '../product/sourceLookup.js';
export function SourceLinks({entry,onUpdate,theme:t,L,readOnly=false}) {
  const [busy,setBusy]=useState(false),[results,setResults]=useState([]),[status,setStatus]=useState('');
  const [key,setKey]=useState(()=>{try{return localStorage.getItem('tm-omdb-key')||''}catch{return ''}});
  const request=useRef(null);useEffect(()=>()=>request.current?.abort(),[]);
  const link=sourceSearchLink(entry),meta=entry.externalMeta,online=typeof navigator==='undefined'||navigator.onLine;
  const style={fontFamily:'var(--tm-font-body)',fontSize:13,color:t.text,background:'transparent',border:'1px solid '+t.border,borderRadius:8,padding:'8px 10px',minHeight:40};
  async function find(){request.current?.abort();const ctrl=new AbortController();request.current=ctrl;const timeout=setTimeout(()=>ctrl.abort(),8000);setBusy(true);setStatus('');setResults([]);try{const found=await lookupSource(entry,{omdbKey:key,online,signal:ctrl.signal});if(request.current!==ctrl)return;setResults(found);if(!found.length)setStatus(L('Zatím bez výsledku. Údaje můžeš nechat tak, jak jsou.','No result for now. Your information stays as it is.'));}finally{clearTimeout(timeout);if(request.current===ctrl)setBusy(false);}}
  return <section aria-label={L('Odkazy a informace','Links and information')} style={{margin:'14px 0',fontFamily:'var(--tm-font-body)',fontSize:13}}>
    <div style={{display:'flex',gap:8,flexWrap:'wrap'}}>
      {(entry.type==='Book'||entry.type==='Movie')&&<a href={link.url} target="_blank" rel="noopener noreferrer" style={{...style,textDecoration:'none',display:'inline-flex',alignItems:'center'}}>{L('Najít na ','Find on ')}{link.label}</a>}
      {!readOnly&&['Book','Movie'].includes(entry.type)&&<button type="button" disabled={busy||!online||(entry.type==='Movie'&&!key)} onClick={find} style={{...style,cursor:'pointer',opacity:(!online||(entry.type==='Movie'&&!key))?.5:1}}>{busy?L('Hledám…','Searching…'):L('Doplnit údaje','Find details')}</button>}
    </div>
    {!readOnly&&<label style={{display:'block',marginTop:12}}>{L('Odkaz na titul, rozhovor nebo video','Link to title, interview or video')}<div style={{display:'flex',gap:8,marginTop:5}}><input type="url" aria-label={L('Odkaz na obsah','Content link')} value={entry.url||''} onChange={e=>onUpdate({url:e.target.value})} placeholder="https://…" style={{...style,minWidth:0,width:'100%'}}/>{safeSourceUrl(entry.url)&&<a style={{...style,textDecoration:'none'}} target="_blank" rel="noopener noreferrer" href={safeSourceUrl(entry.url)}>{L('Otevřít','Open')}</a>}</div></label>}
    {readOnly&&safeSourceUrl(entry.url)&&<a href={safeSourceUrl(entry.url)} target="_blank" rel="noopener noreferrer">{L('Otevřít obsah','Open content')}</a>}
    {results.length>0&&<div style={{marginTop:10}}><p>{L('Vyber správný titul. Doplní se jen chybějící údaje.','Choose the matching title. Only missing information is filled.')}</p>{results.map((r,i)=><button key={r.url||i} style={{...style,display:'block',width:'100%',textAlign:'left',marginTop:5,cursor:'pointer'}} onClick={()=>{onUpdate(metadataPatch(entry,r));setResults([]);setStatus(L('Údaje doplněny.','Details added.'));}}><strong>{r.title}</strong><br/>{[r.author,r.year].filter(Boolean).join(' · ')}</button>)}</div>}
    {status&&<p role="status" style={{color:t.textSec,fontSize:12}}>{status}</p>}
    {meta&&<div style={{marginTop:10,lineHeight:1.6,color:t.textSec}}><a href={safeSourceUrl(meta.url)} target="_blank" rel="noopener noreferrer" style={{color:'inherit'}}>{meta.provider}</a>{meta.rating!=null&&meta.rating!==''?' · '+meta.rating+' / '+meta.scale:''}{meta.year?' · '+meta.year:''}{meta.duration?' · '+meta.duration:''}{meta.description&&<p>{meta.description}</p>}<div style={{fontSize:11}}>{L('Načteno ','Retrieved ')}{new Date(meta.fetchedAt).toLocaleDateString(L('cs-CZ','en-GB'))}</div></div>}
    {!readOnly&&entry.type==='Movie'&&<details style={{marginTop:10,color:t.textSec}}><summary style={{cursor:'pointer'}}>{L('Připojení filmových údajů','Movie data connection')}</summary><p>{L('IMDb hodnocení načítá OMDb. Klíč se ukládá pouze v tomto prohlížeči.','IMDb ratings come through OMDb. The key is stored only in this browser.')}</p><a href="https://www.omdbapi.com/apikey.aspx" target="_blank" rel="noopener noreferrer" style={{color:t.text}}>OMDb API</a><input type="password" aria-label="OMDb API key" autoComplete="off" value={key} onChange={e=>{setKey(e.target.value);try{localStorage.setItem('tm-omdb-key',e.target.value)}catch{}}} style={{...style,display:'block',width:'100%',marginTop:8}}/></details>}
    {entry.type==='Book'&&<small style={{display:'block',marginTop:8,color:t.textSec}}>{L('Doplnění údajů: Open Library. Goodreads otevře vyhledávání.','Metadata: Open Library. Goodreads opens search.')}</small>}
  </section>;
}
