import React,{useState,useEffect,useRef} from "react";
import {cyclePhase} from "../product/togetherGuidance.js";
import {PhaseGuide,MoonCompanion} from "./togetherGuidance.jsx";
import {TogetherInspiration,FaceToFacePrompts} from "./togetherInspiration.jsx";
import {TogetherPractice} from "./togetherPractice.jsx";
import {TogetherText,TogetherFold} from "./togetherElements.jsx";
import {togetherTheme,togetherStyles} from "./togetherStyles.js";
import {TogetherCalendar} from "./togetherCalendar.jsx";
import {TmIcon} from "./icons.jsx";
import {TogetherJournal} from "./togetherJournal.jsx";
import {PartnerPages} from "./togetherPages.jsx";
import {dateKey,cycleSummary,addDays,emptyTogether} from "../product/together.js";
import {questionFor} from "../product/togetherJournal.js";
import {TOGETHER_RITUALS,getTogetherRitualText} from "../product/togetherRituals.js";
import {readTogetherResponse} from "../product/togetherResponse.js";

export function TogetherIcon({size=24}) {return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.1" strokeLinecap="round"><path d="M12 20C7 16 3 13 3 8a4 4 0 0 1 9-1 4 4 0 0 1 9 1c0 5-4 8-9 12Z"/><path d="M8 7c-2 0-3 2-2 4"/></svg>;}
// Original line illustration: two stems sharing space, without a medical/lunar prediction claim.
export function TogetherArt(){return <svg viewBox="0 0 180 140" fill="none" stroke="currentColor" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M34 123C57 120 75 98 80 71S81 25 59 18M151 124C120 117 97 96 96 64s11-45 28-50M73 93C49 86 46 65 37 64c21-3 35 6 40 20M99 88c25-2 38-21 44-31-27 0-39 11-44 21M80 63C61 57 55 43 52 36c20 1 27 11 29 20M98 55c18-7 25-20 30-29-22 4-26 12-28 23M70 104c6 11 11 18 20 25 10-8 18-18 22-27M39 117c28-6 47-3 52 7 12-9 34-9 51-4"/><path d="M58 18c8 1 16 4 20 10M59 18c4 7 7 13 6 21M124 14c-4 9-8 14-15 18M124 14c-8 1-15 5-18 10M40 69l34 18M140 63l-36 18M55 39l22 18M126 30l-25 19"/><path d="M29 103c-9-23-6-48 7-66M150 37c12 18 15 43 6 66" strokeDasharray="1 5"/><circle cx="89" cy="17" r="6"/><path d="M86 12c-5 6-2 10 5 10M83 130h17M17 120l4-4m-2 0v7m140-10 5 3m-5 1 5-4"/></svg>;}
const errors={"question-changed":["Otázka se mezitím změnila. Rozepsaná odpověď zůstává. Obnov přehled a zkontroluj, k jaké otázce patří.","The question changed. Your draft remains. Refresh the page and check which question it answers."],"owner-not-configured":["Spolu ještě nemá na serveru nastaveného vlastníka aplikace. Je potřeba dokončit nastavení hostingu; opakované přihlášení nepomůže.","Together has no application owner configured on the server. Hosting setup must be completed; signing in again will not fix this."],"sign-in-required":["Přihlášení vypršelo. Přihlas se znovu a obnov přehled.","Your session expired. Sign in again and refresh."],"invalid-server-response":["Server místo údajů Spolu vrátil webovou stránku. Zkus obnovit aplikaci; pokud chyba trvá, je potřeba opravit směrování na serveru.","The server returned a web page instead of Together data. Refresh the app; if it persists, server routing needs repair."],conflict:["Mezitím se údaje změnily. Rozepsaný text zůstává tady. Obnov přehled a zkontroluj ho před uložením.","Data changed elsewhere. Your draft is still here. Refresh and review it before saving."],"invalid-invite":["Kód už neplatí nebo byl použit. Partnerka může vytvořit nový.","This code expired or was used. Your partner can create a new one."],"not-connected":["Pro tuto akci nejdřív potvrďte propojení.","Confirm the connection first."],"connection-exists":["Nejdřív ukonči současné propojení.","Disconnect the existing connection first."],"invalid period dates":["Zkontroluj data menstruace. Zápisy mají být skutečné, ne budoucí odhady.","Check period dates. Record actual dates, not future estimates."],"overlapping periods":["Záznamy menstruace se překrývají. Oprav jejich začátek nebo konec.","Period records overlap. Correct their start or end."],"invalid-plan":["Vyplň název, datum, čas a délku alespoň 10 minut.","Enter a title, date, time and duration of at least 10 minutes."]};
export function TogetherPage({t,lang="cs",Header,Sheet,getPages,role="coach"}) {
  const L=(cs,en)=>lang==="en"?en:cs;
  const [tab,setTab]=useState("today"),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [day,setDay]=useState(dateKey()),[entry,setEntry]=useState({}),[dirty,setDirty]=useState(false),[baseRev,setBaseRev]=useState(0);
  const [period,setPeriod]=useState({start:dateKey(),end:""}),[code,setCode]=useState(""),[invite,setInvite]=useState(""),[scopes,setScopes]=useState([]),[answer,setAnswer]=useState("");
  const [answerContext,setAnswerContext]=useState(null);
  const [dateOpen,setDateOpen]=useState(false),[periodOpen,setPeriodOpen]=useState(false),[practiceOpen,setPracticeOpen]=useState(false);
  const [plan,setPlan]=useState(null),[mode,setMode]=useState("observe"),[length,setLength]=useState(28);
  const pageRef=useRef(null),planHeadingRef=useRef(null),periodSummaryRef=useRef(null),[focusRequest,setFocusRequest]=useState(null);
  const journalDirty=useRef(false),[journalReset,setJournalReset]=useState(0);
  const generation=useRef(0),mounted=useRef(true),editing=useRef(false),snapshot=useRef(null),dayRef=useRef(day),answerDirty=useRef(false),cycleDirty=useRef(false),scopesDirty=useRef(false),scopeRevision=useRef(null);
  dayRef.current=day;
  editing.current=dirty;
  const fetchSnapshot=async()=>{
    const current=++generation.current;
    try{const r=await fetch(`/api/together?date=${dateKey()}`,{cache:"no-store"});const d=await readTogetherResponse(r);
      if(!mounted.current||current!==generation.current)return;
      snapshot.current=d;setData(d);setError("");if(!scopesDirty.current){setScopes(d.link?.scopes||[]);scopeRevision.current=d.link?.revision;}
      if(!editing.current){setEntry(d.self.doc.days[dayRef.current]||{});setBaseRev(d.self.revision);}
      if(!cycleDirty.current){setMode(d.self.doc.mode);setLength(d.self.doc.usualLength);}
      if(!answerDirty.current){setAnswer(d.answer.mine);setAnswerContext({question:d.question,day:d.today,linkId:d.link?.id,linkRevision:d.link?.revision});}
    }catch(e){if(mounted.current&&current===generation.current){snapshot.current=null;setData(null);setError(errors[e.message]?L(...errors[e.message]):L("Přehled se nepodařilo načíst. Připoj se a zkus to znovu; změny zatím nejsou uložené.","Could not load the page. Reconnect and retry; changes have not been saved."));}}
  };
  useEffect(()=>{mounted.current=true;fetchSnapshot();const focus=()=>{if(document.visibilityState==="visible")fetchSnapshot();else{generation.current++;setData(null);snapshot.current=null;}};const offline=()=>{generation.current++;snapshot.current=null;setData(null);setError(L("Jsi offline. Připoj se pro načtení a uložení.","You are offline. Reconnect to load and save."));};window.addEventListener("offline",offline);const timer=setInterval(()=>{if(document.visibilityState==="visible")fetchSnapshot();},30000);document.addEventListener("visibilitychange",focus);window.addEventListener("focus",focus);window.addEventListener("online",focus);return()=>{mounted.current=false;generation.current++;clearInterval(timer);document.removeEventListener("visibilitychange",focus);window.removeEventListener("focus",focus);window.removeEventListener("online",focus);window.removeEventListener("offline",offline);};},[]);
  const save=async(path,body,kind)=>{
    if(busy)return false;setBusy(true);setError("");setNotice("");
    try{const r=await fetch(`/api/together/${path}?date=${dateKey()}`,{method:["invite","claim","disconnect"].includes(path)?"POST":"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),cache:"no-store"});const d=await readTogetherResponse(r);
      if(path==="invite")setInvite(d.code);if(path==="self"&&kind!=="entry"&&baseRev===body.revision)setBaseRev(d.revision);if(kind==="entry"){editing.current=false;setDirty(false);}if(kind==="cycle")cycleDirty.current=false;if(path==="answer")answerDirty.current=false;if(path==="sharing")scopesDirty.current=false;if(path==="disconnect"){setInvite("");setCode("");setPlan(null);setAnswer("");answerDirty.current=false;scopesDirty.current=false;}setNotice(L("Uloženo.","Saved."));await fetchSnapshot();return true;
    }catch(e){setError(errors[e.message]?L(...errors[e.message]):L("Nepodařilo se uložit. Text zůstává rozepsaný, zkus to znovu.","Could not save. Your draft is retained; try again."));return false;}finally{setBusy(false);}
  };
  const own=data?.self.doc||emptyTogether(), canTrack=role==="client",active=data?.link?.status==="active";
  const summary=canTrack?cycleSummary(own):data?.partner?.cycle;
  const phase=canTrack?cyclePhase(own,summary,dateKey()):data?.partner?.phase;
  const dateLabel=d=>new Date(d+"T12:00:00").toLocaleDateString(lang==="en"?"en-GB":"cs-CZ",{day:"numeric",month:"long"});
  const today=dateKey(), question=(answerDirty.current?answerContext?.question?.text:data?.question?.text)||questionFor(today);
  const staleAnswer=answerDirty.current&&(answerContext?.question?.id!==data?.question?.id||answerContext?.day!==data?.today||answerContext?.linkId!==data?.link?.id||answerContext?.linkRevision!==data?.link?.revision);
  const answerBody=value=>({answer:value,questionId:answerContext?.question?.id,questionDay:answerContext?.day,linkId:answerContext?.linkId,linkRevision:answerContext?.linkRevision});
  const upcoming=(data?.plans||[]).filter(p=>p.status==="planned"&&p.date>=today).toSorted((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))[0];
  const navigateTo=(next,target="view")=>{setTab(next);setFocusRequest({tab:next,target});};
  const propose=(p,{afterOverlay=false}={})=>{setPlan(p);setTab("plans");setFocusRequest({tab:"plans",target:"plan",afterOverlay});};
  useEffect(()=>{
    if(!focusRequest||focusRequest.tab!==tab)return;
    let frame,timer;
    const focusTarget=()=>{
      const root=pageRef.current;
      const navigationTarget=root?.querySelector(`[data-tg-nav="${tab}"]`);
      const target=focusRequest.target==="period"?periodSummaryRef.current:focusRequest.target==="practice"?root?.querySelector(".tg-practice>summary"):focusRequest.target==="plan"?planHeadingRef.current:focusRequest.target==="tab"?navigationTarget:root?.querySelector(`[data-tg-view="${tab}"] > h2`)||navigationTarget;
      if(!target)return;
      target.focus({preventScroll:true});
      target.scrollIntoView({behavior:"auto",block:"start"});
      setFocusRequest(null);
    };
    const schedule=()=>{clearTimeout(timer);cancelAnimationFrame(frame);frame=requestAnimationFrame(focusTarget);};
    // Sheets consume their history entry on close. Wait for its scroll restoration
    // before focusing a new plan, otherwise the browser can move the form offscreen.
    if(focusRequest.afterOverlay){window.addEventListener("popstate",schedule,{once:true});timer=setTimeout(schedule,300);}
    else schedule();
    return()=>{cancelAnimationFrame(frame);clearTimeout(timer);window.removeEventListener("popstate",schedule);};
  },[focusRequest,tab,plan,data]);
  const fmtSummary=summary?.next?`${dateLabel(summary.next.from)} – ${dateLabel(summary.next.to)}`:L("Bez odhadu další menstruace","No estimate for the next period");
  const setField=(key,value)=>{setEntry(e=>({...e,[key]:value}));setDirty(true);};
  const selectDay=next=>{if(!next||next>today)return;if(dirty&&!window.confirm(L("Opustit neuložený zápis?","Discard the unsaved check-in?")))return;setDay(next);setEntry(own.days[next]||{});setBaseRev(data.self.revision);setDirty(false);setDateOpen(false);};
  const updateDoc=patch=>save("self",{revision:patch.days?baseRev:data.self.revision,doc:{...own,...patch}},patch.days?"entry":patch.mode?"cycle":"period");
  const refresh=()=>{if((editing.current||answerDirty.current||cycleDirty.current||scopesDirty.current||journalDirty.current||plan)&&!window.confirm(L("Zahodit neuložené úpravy a načíst aktuální stav?","Discard unsaved edits and load the current version?")))return;editing.current=false;setDirty(false);answerDirty.current=false;cycleDirty.current=false;scopesDirty.current=false;setJournalReset(n=>n+1);setPlan(null);fetchSnapshot();};
  const section=(title,children,headingRef=null)=><section className="tm-together-section" data-tg-view={tab}><h2 ref={headingRef} tabIndex={-1}>{title}</h2>{children}</section>;
  const button=(label,fn,primary=false,disabled=false)=><button type="button" className={primary?"primary":""} onClick={fn} disabled={busy||disabled}>{label}</button>;
  return <div ref={pageRef} className="tm-together" style={togetherTheme(t)}>
    <style>{togetherStyles}</style>
    <div className="tg-header"><div>{Header?<Header pageKey="spolu" icon={<TogetherIcon size={38}/>}>{L("Spolu","Together")}</Header>:<h1>{L("Spolu","Together")}</h1>}</div><MoonCompanion lang={lang} Sheet={Sheet} t={t} onPlan={active?p=>propose({...p,date:today,time:"18:00"},{afterOverlay:true}):null}/><p className="tg-intro">{L("Chvíle pro vás dva. Taková, na kterou dnes máte prostor.","A moment for the two of you. Whatever you have room for today.")}</p></div>
    <nav className="tabs" aria-label={L("Přehled Spolu","Together views")}>{[["today","Dnes","Today"],["conversations","Rozhovory","Conversations"],["plans","Plány","Plans"],["cycle","Cyklus","Cycle"]].map(([id,cs,en])=><button key={id} type="button" data-tg-nav={id} aria-pressed={tab===id} onClick={()=>navigateTo(id,"tab")}>{L(cs,en)}</button>)}</nav>
    <div className="tg-settings-row"><button className="tg-text-button" type="button" aria-expanded={tab==="sharing"||tab==="pages"} onClick={()=>navigateTo(tab==="sharing"||tab==="pages"?"today":"sharing","tab")}>{L("Propojení a sdílení","Connection and sharing")}</button></div>
    {(tab==="sharing"||tab==="pages")&&<nav className="row tg-settings-nav" aria-label={L("Nastavení Spolu","Together settings")}><button type="button" data-tg-nav="sharing" aria-pressed={tab==="sharing"} onClick={()=>navigateTo("sharing","tab")}>{L("Naše propojení","Our connection")}</button><button type="button" data-tg-nav="pages" aria-pressed={tab==="pages"} onClick={()=>navigateTo("pages","tab")}>{L("Sdílené stránky","Shared pages")}</button></nav>}
    {error&&<div role="alert" className="error"><p>{error}</p>{button(L("Obnovit přehled","Refresh"),refresh)}</div>}
    {notice&&<div className="notice" role="status">{notice}</div>}
    {!data&&!error&&<p role="status">{L("Načítám váš prostor…","Loading your space…")}</p>}
    {!data&&error&&<p>{L("Spolu používá dva oddělené přihlášené účty. Partnerka spravuje svůj cyklus ve své aplikaci a sama potvrzuje, co sdílí.","Together uses two separate signed-in accounts. Your partner manages her cycle in her own app and chooses what to share.")}</p>}
    {data&&tab==="today"&&<>

      {!active&&<section className="tm-together-section"><h2>{L("Váš prostor může začít tady","Your space can begin here")}</h2><p>{L("Zápis si můžeš udělat už teď. Propojení vám otevře společné plány a rozhovory.","You can check in already. Connecting opens up shared plans and conversations.")}</p>{button(L("Propojit naše účty","Connect our accounts"),()=>navigateTo("sharing"))}</section>}
      {active&&<section className="tm-together-section tg-partner"><h2>{L("Od druhého z nás","From your partner")}</h2>{data.partner?.support?.text?<p className="tg-personal">{data.partner.support.text}</p>:<p>{L("Dnes tu zatím není žádné přání. I obyčejné „Jak ti je?“ může otevřít prostor.","No wish has been shared today. A simple ‘How are you?’ can open a little space.")}</p>}{data.partner?.wellbeing&&<p className="hint">{data.partner.wellbeing.mood}{data.partner.wellbeing.energy?` · ${L("energie","energy")} ${data.partner.wellbeing.energy}/5`:""}</p>}</section>}
      {section(L("Co by ti dnes udělalo dobře?","What would feel good today?"),<>
        <p>{L("Klidně jen jedna věta. Nemusíš mít všechno pojmenované.","A single sentence is enough. You do not need to have it all figured out.")}</p>
      <div className="tg-date-row"><button type="button" aria-label={L("Předchozí den","Previous day")} onClick={()=>selectDay(addDays(day,-1))}><TmIcon id="back" size={14}/></button><button type="button" className="tg-date" aria-expanded={dateOpen} aria-controls="tg-date-chooser" onClick={()=>setDateOpen(v=>!v)}>{new Date(day+"T12:00:00").toLocaleDateString(lang==="en"?"en-GB":"cs-CZ")}</button><button type="button" aria-label={L("Další den","Next day")} disabled={day>=today} onClick={()=>selectDay(addDays(day,1))}><TmIcon id="forward" size={14}/></button><button type="button" className="tg-date-today" onClick={()=>selectDay(today)}>{L("Dnes","Today")}</button></div>
      <div className="tg-date-chooser" id="tg-date-chooser" hidden={!dateOpen}><label htmlFor="tg-day">{L("Datum zápisu","Check-in date")}</label><input id="tg-day" type="date" value={day} max={today} onChange={e=>selectDay(e.target.value)}/></div>
        <label htmlFor="tg-mood">{L("Jak mi je","How I feel")}</label><input id="tg-mood" maxLength={80} value={entry.mood||""} onChange={e=>setField("mood",e.target.value)} placeholder={L("Třeba: je mi hezky, jen jsem trochu unavený/á…","For example: feeling good, just a little tired…")}/>
        <label htmlFor="tg-support">{L("Co by mi od tebe pomohlo","What would help from you")}</label>
        <div className="tg-needs" role="group" aria-label={L("Náměty podpory","Support ideas")}>{[["Chvíle spolu","Time together","Dnes by mi udělala dobře chvíle s tebou.","I would enjoy some time with you today."],["Vyslechnout","Listen","Pomohlo by mi, kdybys mě jen vyslechl/a.","It would help if you could simply listen."],["S něčím pomoct","A hand","Ocením dnes s něčím pomoct. Domluvíme se?","I could use a hand today. Can we talk about it?"],["Trochu prostoru","Some space","Potřebuji dnes trochu času pro sebe.","I need a little time to myself today."]].map(([cs,en,textCs,textEn])=><button key={cs} type="button" aria-pressed={entry.support===L(textCs,textEn)} onClick={()=>setField("support",entry.support===L(textCs,textEn)?"":L(textCs,textEn))}>{L(cs,en)}</button>)}</div>
        <TogetherText id="tg-support" rows={2} maxLength={300} value={entry.support||""} onChange={e=>setField("support",e.target.value)} placeholder={L("Nebo to řekni po svém…","Or say it in your own words…")}/>
        <details className="tg-optional"><summary>{L("Další údaje · energie a poznámka","More details · energy and note")}</summary>
          <label>{L("Kolik mám energie","My energy")}</label><div className="row" role="group" aria-label={L("Energie","Energy")}>{[1,2,3,4,5].map(n=><button key={n} aria-pressed={entry.energy===n} style={{background:entry.energy===n?t.callout:"transparent"}} onClick={()=>setField("energy",entry.energy===n?null:n)}>{n}</button>)}</div><p className="hint">{L("1 · spíš odpočívat, 5 · energie mám dost. Můžeš nechat prázdné.","1 · could use rest, 5 · plenty of energy. You can leave this blank.")}</p>
          {canTrack&&<div className="fields"><label>{L("Krvácení · jen pro mě","Bleeding · only for me")}<select value={entry.flow||"none"} onChange={e=>setField("flow",e.target.value)}>{[["none","Žádné","None"],["spotting","Špinění","Spotting"],["light","Slabé","Light"],["medium","Střední","Medium"],["heavy","Silné","Heavy"]].map(([v,cs,en])=><option key={v} value={v}>{L(cs,en)}</option>)}</select></label><label>{L("Bolest · jen pro mě","Pain · only for me")}<select value={entry.pain||"none"} onChange={e=>setField("pain",e.target.value)}>{[["none","Žádná","None"],["mild","Mírná","Mild"],["moderate","Střední","Moderate"],["strong","Silná","Strong"]].map(([v,cs,en])=><option key={v} value={v}>{L(cs,en)}</option>)}</select></label></div>}
          <label htmlFor="tg-note">{L("Co si chci nechat jen pro sebe","What I want to keep to myself")}</label><TogetherText id="tg-note" maxLength={1500} value={entry.note||""} onChange={e=>setField("note",e.target.value)} placeholder={L("Tahle poznámka zůstane jen tvoje.","This note stays yours alone.")}/>
        </details>
        {day!==today&&<p className="hint">{L("Upravuješ zápis z","Editing your check-in from")} {dateLabel(day)}.</p>}
        <p className="hint">{!active?(canTrack?L("Zápis zatím vidíš jen ty. Po propojení se dnešní pocit, energie a přání řídí tvými volbami sdílení. Poznámka zůstává soukromá.","Only you can see this for now. Once connected, today's feelings, energy and wishes follow your sharing choices. Your note stays private."):L("Zápis zatím vidíš jen ty. Po propojení partnerka uvidí tvůj uložený dnešní pocit, energii a přání. Poznámka zůstane soukromá.","Only you can see this for now. Once connected, your partner sees your saved feelings, energy and wishes for today. Your note stays private.")):canTrack?L("Pocit, energii a přání partner uvidí jen podle tvých voleb v Propojení a sdílení. Poznámka, bolest a krvácení zůstávají soukromé.","Your partner sees feelings, energy and wishes only as chosen in Connection and sharing. Your note, pain and bleeding remain private."):L("Uložený dnešní pocit, energii a přání uvidí partnerka. Soukromá poznámka zůstane jen tvoje.","Your partner can see your saved feelings, energy and wishes for today. Your private note stays yours alone.")}</p>
        {button(L("Uložit můj zápis","Save my check-in"),()=>updateDoc({days:{...own.days,[day]:entry}}),true,!dirty)}
        {dirty&&<p className="hint" role="status">{L("Rozepsáno. Ještě neuloženo ani sdíleno.","Draft. Not saved or shared yet.")}</p>}
      </>)}
      {active&&<section className="tm-together-section"><h2>{L("Na co máme prostor","What we have room for")}</h2>{upcoming?<><p className="tg-personal">{upcoming.title}</p><p>{dateLabel(upcoming.date)} · {upcoming.time} · {upcoming.approved.owner&&upcoming.approved.partner?L("Domluveno","Agreed"):L("Zatím návrh","Still a proposal")}</p></>:<p>{L("Společný čaj, procházka nebo pár minut bez spěchu. Co by bylo příjemné vám oběma?","Tea together, a walk, or a few unhurried minutes. What would feel good to both of you?")}</p>}<div className="row tg-actions">{upcoming?button(L("Otevřít domluvu","Open our plan"),()=>navigateTo("plans")):button(L("Domluvit chvíli","Make a little time"),()=>propose({title:"",date:today,time:"18:00",minutes:30,note:""}))}{button(L("Otevřít rozhovory","Open conversations"),()=>navigateTo("conversations"))}</div></section>}
    </>}
    {data&&tab==="conversations"&&<>
      <div className="overview"><strong>{L("Místo, kde se můžeme slyšet","Room to hear each other")}</strong><p>{L("Někdy stačí naslouchat. Vyberte si, na co právě máte chuť, a zbytek nechte být.","Sometimes listening is enough. Choose what feels right and leave the rest.")}</p></div>
      {active?section(L("Jedna otázka pro dnešek","One question for today"),<><p className="tg-personal">{L(...question)}</p><p className="hint">{L("Každý odpovězte za sebe. Odpovědi se vám navzájem ukážou, až je odešlete oba. Můžete si také jen popovídat bez zápisu.","Answer in your own words. You see each other's answers after both have shared. You can also simply talk without writing anything down.")}</p><details className="tg-optional"><summary>{L("Zapsat nebo přečíst odpovědi","Write or read our answers")}</summary><label htmlFor="tg-answer">{L("Co mi k tomu přichází","What comes to mind")}</label><TogetherText id="tg-answer" value={answer} maxLength={1500} onChange={e=>{setAnswer(e.target.value);answerDirty.current=true;}} placeholder={L("Nemusí to být dokonalá odpověď…","It does not need to be a perfect answer…")}/><div className="row">{button(L("Sdílet moji odpověď","Share my answer"),()=>save("answer",answerBody(answer)),true,!answer.trim()||staleAnswer)}{data.answer.mine&&button(L("Odebrat moji odpověď","Remove my answer"),async()=>{if(staleAnswer)return;if(!window.confirm(L("Odebrat svou odpověď z rozhovoru? Rozepsané úpravy se také zahodí.","Remove your answer from this conversation? Any unsaved edits will also be discarded.")))return;if(await save("answer",answerBody(""))){setAnswer("");answerDirty.current=false;}})}</div>{staleAnswer&&<div role="alert"><p>{L("Otázka nebo propojení se mezitím změnily. Rozepsanou odpověď teď nelze sdílet. Než začneš znovu, můžeš si svůj text zkopírovat.","The question or connection changed. This draft cannot be shared. You can copy your words before starting again.")}</p>{button(L("Načíst aktuální rozhovor","Load the current conversation"),refresh)}</div>}{answerDirty.current&&<p className="hint">{L("Rozepsáno, ještě nesdíleno.","Draft, not shared yet.")}</p>}{data.answer.partner?<div className="tg-partner-answer"><h3>{L("Druhý z nás","Your partner")}</h3><p>{data.answer.partner}</p></div>:<p className="hint">{L("Zatím tu nejsou obě odpovědi. Není kam spěchat.","Both answers are not here yet. There is no hurry.")}</p>}</details><FaceToFacePrompts lang={lang}/></>):section(L("Otázka nemusí čekat na propojení","A question can come before connecting"),<><p>{L("Náměty níže můžete zkusit rovnou. Pro ukládání a vzájemné sdílení odpovědí nejdřív propojte účty.","You can try the invitations below straight away. Connect accounts to save and share your answers.")}</p>{button(L("Propojit účty","Connect accounts"),()=>navigateTo("sharing"))}</>)}
    </>}
    {data&&tab==="cycle"&&<>
      {section(canTrack?L("Můj cyklus","My cycle"):L("Sdílený přehled","Shared overview"),<><strong style={{fontFamily:"'EB Garamond',serif",fontSize:32}}>{summary?.day?`${L("Den","Day")} ${summary.day}`:L("Zatím bez záznamu","No record yet")}</strong><p>{fmtSummary}</p><p className="hint">{L("Odhad je rozsah podle zapsaných cyklů, ne potvrzená ovulace. Neslouží jako antikoncepce ani k určování plodných dnů.","Estimates are ranges based on recorded cycles, not confirmed ovulation. They are not contraception or fertile-day predictions.")}</p>{summary?.reason==="variable"&&<p>{L("Délky cyklů se výrazně liší. Zobrazujeme skutečné zápisy bez předpovědi.","Cycle lengths vary. Showing actual records without a prediction.")}</p>}{summary?.reason==="outdated"&&<p>{L("Předchozí odhad už uplynul. Přidej skutečný začátek, až nastane.","The previous estimate has passed. Record the actual start when it happens.")}</p>}{!canTrack&&!summary&&<p>{L("Partnerka zatím přehled cyklu nesdílí. Společné plány můžete používat i bez něj.","Your partner is not sharing a cycle overview. You can plan together without it.")}</p>}</>)}
      {(canTrack||summary)&&<TogetherCalendar periods={canTrack?own.periods:[]} summary={summary} plans={data.plans} lang={lang} t={t}/>}
      <TogetherFold title={L("Jak si být oporou","How to support each other")}>
      <PhaseGuide embedded phase={phase} lang={lang} onPlan={active?title=>propose({title,date:today,time:"18:00",minutes:30,note:""}):null}/>
      </TogetherFold>
      {canTrack&&<><TogetherFold title={L("Zaznamenat menstruaci","Record a period")} summaryRef={periodSummaryRef} open={periodOpen} onToggle={e=>setPeriodOpen(e.currentTarget.open)}><div className="fields"><label>{L("První den","First day")}<input type="date" max={today} value={period.start} onChange={e=>setPeriod(p=>({...p,start:e.target.value}))}/></label><label>{L("Poslední den · nepovinný","Last day · optional")}<input type="date" min={period.start} max={today} value={period.end} onChange={e=>setPeriod(p=>({...p,end:e.target.value}))}/></label></div>{button(L("Uložit menstruaci","Save period"),async()=>{const next=[...own.periods.filter(p=>p.start!==(period.originalStart||period.start)),{start:period.start,end:period.end||null}];if(await updateDoc({periods:next})){setPeriod({start:today,end:""});setPeriodOpen(false);}},true)}<p className="hint">{L("Záznam upravíš výběrem jeho data níže. Začátek je první den menstruace, ne špinění.","Choose a record below to edit it. Start means the first period day, not spotting.")}</p></TogetherFold>
        <TogetherFold title={L("Historie cyklu","Cycle history")}>{own.periods.length?own.periods.toReversed().map(p=><div className="item row" key={p.start}><span style={{flex:1}}>{dateLabel(p.start)}{p.end?` – ${dateLabel(p.end)}`:""}</span>{button(L("Upravit","Edit"),()=>{setPeriod({start:p.start,end:p.end||"",originalStart:p.start});setPeriodOpen(true);navigateTo("cycle","period");})}{button(L("Odebrat","Remove"),()=>{if(window.confirm(L("Odebrat tento záznam menstruace?","Remove this period record?")))updateDoc({periods:own.periods.filter(x=>x.start!==p.start)});})}</div>):<p>{L("Tvoje historie začne prvním skutečným zápisem.","Your history starts with your first actual record.")}</p>}</TogetherFold>
        <TogetherFold title={L("Jak se orientovat v mém cyklu","How to read my cycle")}><label>{L("Režim cyklu","Cycle mode")}<select value={mode} onChange={e=>{setMode(e.target.value);cycleDirty.current=true;}}><option value="observe">{L("Jen záznamy, bez odhadů","Records only, no estimates")}</option><option value="estimate">{L("Orientační odhad menstruace","Approximate period estimate")}</option><option value="paused">{L("Pauza v odhadech","Pause estimates")}</option></select></label><label>{L("Moje obvyklá délka cyklu ve dnech","My usual cycle length in days")}<input type="number" min="15" max="90" value={length} onChange={e=>{setLength(Number(e.target.value));cycleDirty.current=true;}}/></label><p className="hint">{L("Bez historie se použije tato délka. Pro antikoncepci, těhotenství, období po porodu či nepravidelný cyklus zvol jen záznamy nebo pauzu.","Without history, this length is used. For hormonal contraception, pregnancy, postpartum or irregular cycles, use records only or pause.")}</p>{button(L("Uložit nastavení cyklu","Save cycle settings"),()=>updateDoc({mode,usualLength:length}),true)}</TogetherFold>
        <p className="hint">{L("Při neobvyklé nebo silné bolesti a změně krvácení se obrať na gynekologa.","Speak to a clinician about unusual or severe pain or changes in bleeding.")} <a href="https://www.nhs.uk/conditions/periods/" target="_blank" rel="noreferrer" style={{color:t.accentInk}}>{L("O cyklu a odhadech","About cycles and estimates")}</a></p>
      </>}
    </>}
    {data&&tab==="plans"&&<>
      {section(L("Náš společný čas","Our time together"),<><p>{L("Na něco se těšit je hezké. Z návrhu bude domluva, až vám oběma sedne čas i chuť.","It is good to have something to look forward to. A proposal becomes a plan when it works for both of you.")}</p>{!active?button(L("Nejdřív se propojit","Connect first"),()=>navigateTo("sharing")):button(L("Domluvit chvíli","Make a little time"),()=>propose({title:"",date:today,time:"18:00",minutes:30,note:""}),true)}</>)}
      {active&&plan&&section(plan.id?L("Upravit návrh","Edit proposal"):L("Naše příští chvíle","Our next moment"),<><label>{L("Co podnikneme","What shall we do")}<input value={plan.title} maxLength={120} onChange={e=>setPlan(p=>({...p,title:e.target.value}))}/></label><div className="fields"><label>{L("Datum","Date")}<input type="date" value={plan.date} onChange={e=>setPlan(p=>({...p,date:e.target.value}))}/></label><label>{L("Čas","Time")}<input type="time" value={plan.time} onChange={e=>setPlan(p=>({...p,time:e.target.value}))}/></label></div><label>{L("Délka v minutách","Duration in minutes")}<input type="number" min="10" max="1440" value={plan.minutes} onChange={e=>setPlan(p=>({...p,minutes:Number(e.target.value)}))}/></label><label>{L("Poznámka pro oba","Note for both")}<TogetherText value={plan.note} maxLength={600} onChange={e=>setPlan(p=>({...p,note:e.target.value}))}/></label><div className="row">{button(L("Poslat návrh","Send proposal"),async()=>{if(await save("plan",plan))setPlan(null);},true)}{button(L("Zrušit úpravu","Cancel editing"),()=>setPlan(null))}</div></>,planHeadingRef)}
      {active&&section(L("Na čem se domlouváme","What we are planning"),data.plans.some(p=>p.status==="planned")?data.plans.filter(p=>p.status==="planned").toSorted((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(p=><details className="tg-plan-row" key={p.id}><summary><span>{p.title}<small>{dateLabel(p.date)} · {p.time} · {p.minutes} min<br/>{p.status==="done"?L("Proběhlo","Completed"):p.approved.owner&&p.approved.partner?L("Potvrzeno oběma","Confirmed by both"):L("Zatím návrh · druhý ho může potvrdit","A proposal · your partner can confirm it")}</small></span></summary>{p.note&&<p>{p.note}</p>}{p.status!=="done"&&<div className="row">{!p.approved[canTrack?"owner":"partner"]&&button(L("Potvrdit","Confirm"),()=>save("plan",{id:p.id,revision:p.revision,action:"confirm"}),true)}{button(L("Upravit","Edit"),()=>propose(p))}{p.approved.owner&&p.approved.partner&&button(L("Proběhlo","Complete"),()=>save("plan",{id:p.id,revision:p.revision,action:"done"}))}{button(L("Zrušit plán","Cancel plan"),()=>save("plan",{id:p.id,revision:p.revision,action:"cancel"}))}</div>}</details>):<p>{L("Zatím nic domluveného. Klidně začněte něčím malým, na co se těšíte oba.","Nothing agreed yet. Start with something small you can both look forward to.")}</p>)}
      {active&&<TogetherFold title={L("Kalendář společných plánů","Our plans calendar")}><TogetherCalendar showCycle={false} plans={data.plans} lang={lang} t={t}/></TogetherFold>}
      {active&&<TogetherInspiration lang={lang} onPlan={propose}/>}
      {active&&<TogetherPractice open={practiceOpen} onToggle={e=>setPracticeOpen(e.currentTarget.open)} data={data} canTrack={canTrack} getPages={getPages} lang={lang} onPlan={propose} onSharing={()=>navigateTo("pages")} onOpenPractice={()=>{if((editing.current||answerDirty.current||journalDirty.current||plan)&&!window.confirm(L("Otevřít Praxi? Neuložené zápisy ve Spolu se zahodí.","Open Practice? Unsaved Together drafts will be discarded.")))return;window.location.assign("?open=praxe");}}/>}
    </>}
    {data&&tab==="conversations"&&<TogetherRituals lang={lang} onPlan={active?propose:null}/>}
    <TogetherJournal Sheet={Sheet} t={t} data={data} lang={lang} save={save} busy={busy} view={tab} onPlan={propose} onDirty={v=>{journalDirty.current=v;}} reset={journalReset} onPractice={()=>{setPracticeOpen(true);navigateTo("plans","practice");}}/>
    {data&&tab==="sharing"&&<>
      {section(L("Dva účty, vaše rozhodnutí","Two accounts, your choice"),<><p>{L("Partnerka otevře Spolu ve své přihlášené klientské aplikaci (Nastavení → Stránky a navigace) a vytvoří kód. Ty ho zadáš u sebe. Teprve jejím potvrzením se propojení zapne. Cyklus zůstává oddělený od trenérského sdílení.","Your partner opens Together in her signed-in client app (Settings → Pages and navigation) and creates a code. You enter it in yours. The connection starts only after she confirms. Cycle information is separate from coach sharing.")}</p><p><strong>{L("Stav","Status")}: {data.link?({invited:L("Kód čeká na použití","Code awaits use"),pending:L("Čeká na potvrzení partnerky","Awaiting your partner's confirmation"),active:L("Propojeno","Connected")}[data.link.status]):L("Nepřipojeno","Not connected")}</strong></p>
        {canTrack&&(!data.link||data.link.status==="invited")&&<>{button(L("Vytvořit nový kód","Create a new code"),()=>save("invite",{}),true)}{invite&&<><label>{L("Kód platí 24 hodin. Předej ho jen partnerovi.","Valid for 24 hours. Give it only to your partner.")}<input value={invite} readOnly onFocus={e=>e.target.select()}/></label>{button(L("Kopírovat kód","Copy code"),async()=>{try{await navigator.clipboard.writeText(invite);setNotice(L("Kód zkopírován.","Code copied."));}catch{setNotice(L("Označ kód a zkopíruj ho ručně.","Select and copy the code manually."));}})}</>}</>}
        {!canTrack&&!data.link&&<><label>{L("Kód od partnerky","Code from your partner")}<input autoComplete="off" value={code} onChange={e=>setCode(e.target.value.trim())}/></label>{button(L("Požádat o propojení","Request connection"),()=>save("claim",{code}),true,!code)}</>}
        {canTrack&&["pending","active"].includes(data.link?.status)&&<><p>{L("Propojení s trenérským účtem Tanmay. Vyber, co smí vidět:","Connection with the Tanmay account. Choose what may be seen:")}</p>{[["cycle","Den cyklu a odhad menstruace","Cycle day and period estimate"],["wellbeing","Dnešní energie a pocit","Today's energy and mood"],["support","Dnešní přání podpory","Today's support wish"],["phase","Fáze cyklu · záznam nebo odhad","Cycle phase · recorded or estimated"]].map(([id,cs,en])=><label className="consent" key={id}><input type="checkbox" checked={scopes.includes(id)} onChange={e=>{scopesDirty.current=true;setScopes(v=>e.target.checked?[...v,id]:v.filter(x=>x!==id));}}/>{L(cs,en)}</label>)}<p className="hint">{L("Soukromé poznámky, bolest a podrobnosti o krvácení se nesdílí. Všechny přepínače můžeš nechat vypnuté a používat jen společné plány.","Private notes, pain and bleeding details are never shared. Leave every switch off to use only shared plans.")}</p>{button(data.link.status==="pending"?L("Potvrdit propojení a volby","Confirm connection and choices"):L("Uložit sdílení","Save sharing"),()=>save("sharing",{scopes,revision:scopeRevision.current}),true)}</>}
        {!canTrack&&active&&<p>{L("Partnerka sdílí:","Your partner shares:")} {data.link.scopes.length?data.link.scopes.map(s=>({cycle:L("přehled cyklu","cycle overview"),wellbeing:L("dnešní pocity","today's feelings"),support:L("přání podpory","support wishes"),phase:L("fázi cyklu","cycle phase")}[s])).join(", "):L("zatím jen společné plány","shared plans only")}</p>}
        {data.link&&<div style={{marginTop:22}}>{button(L("Ukončit propojení","Disconnect"),()=>{if(window.confirm(L("Ukončit sdílení? Druhá strana ztratí přístup k přehledu a společným plánům.","Disconnect? The other person will lose access to the overview and shared plans.")))save("disconnect",{revision:data.link.revision});})}</div>}
      </>)}
      <p className="hint">{L("Sdílený přehled se ověřuje při otevření a průběžně online. Při ztrátě spojení se schová. To, co už druhý člověk viděl nebo si uložil, nejde zpětně odvolat.","Shared information is checked on opening and regularly online. It is hidden when the connection fails. Information already seen or copied cannot be recalled.")}</p>
    </>}
    {data&&tab==="pages"&&(active?<PartnerPages data={data} canTrack={canTrack} lang={lang} save={save} getPages={getPages} busy={busy}/>:<section className="tm-together-section"><p>{L("Pro čtení stránek se nejdřív propojte.","Connect first to read shared pages.")}</p>{button(L("Nastavit propojení","Set up connection"),()=>navigateTo("sharing"))}</section>)}
  </div>;
}

function TogetherRituals({lang,onPlan}) {
  const L=(cs,en)=>lang==="en"?en:cs;
  return <TogetherFold title={L("Chvíle podle vás","A moment your way")}><p>{L("Bez správných odpovědí a bez povinnosti něco vyplnit. Vyberte si jednu maličkost.","No right answers and nothing you have to fill in. Choose one small thing.")}</p>
    {TOGETHER_RITUALS.map(item=>{const r=getTogetherRitualText(item,lang);return <details className="tg-ritual" key={r.id}><summary><span>{r.title}<small>{r.category} · {r.minutes} {L("min","minutes")}</small></span></summary><p>{r.intro}</p><p className="tg-personal">{r.question}</p><ol>{r.steps.map((step,i)=><li key={i}>{step}</li>)}</ol>{onPlan&&r.minutes>=10&&<button type="button" onClick={()=>onPlan({title:r.title,date:dateKey(),time:"18:00",minutes:r.minutes,note:r.question})}>{L("Navrhnout společnou chvíli","Propose a time together")}</button>}</details>;})}
  </TogetherFold>;
}
