import React,{useState,useEffect,useRef,useId,useMemo} from "react";
import {cycleViewForDate,CYCLE_GUIDE} from "../product/togetherGuidance.js";
import {usePersonalProfile,isPersonalProfileVerified,refreshPersonalProfile} from "./personalProfile.jsx";
import {PhaseGuide,MoonCompanion} from "./togetherGuidance.jsx";
import {TogetherInspiration,FaceToFacePrompts} from "./togetherInspiration.jsx";
import {TogetherPractice} from "./togetherPractice.jsx";
import {TogetherText,TogetherFold} from "./togetherElements.jsx";
import {togetherTheme,togetherStyles} from "./togetherStyles.js";
import {TogetherCalendar} from "./togetherCalendar.jsx";
import {TogetherDayWindow} from "./togetherDayWindow.jsx";
import {TogetherConversationMap} from "./togetherConversationMap.jsx";
import {TogetherMaintenance} from "./togetherMaintenance.jsx";
import {TmIcon} from "./icons.jsx";
import {ROOM_ART} from "./roomArt.js";
import {TogetherJournal} from "./togetherJournal.jsx";
import {PartnerPages} from "./togetherPages.jsx";
import {dateKey,addDays,emptyTogether} from "../product/together.js";
import {questionFor} from "../product/togetherJournal.js";
import {TOGETHER_RITUALS,getTogetherRitualText} from "../product/togetherRituals.js";
import {createTogetherAccountRequest} from "../product/togetherAccountClient.js";

export function TogetherIcon({size=24}) {return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.1" strokeLinecap="round"><path d="M12 20C7 16 3 13 3 8a4 4 0 0 1 9-1 4 4 0 0 1 9 1c0 5-4 8-9 12Z"/><path d="M8 7c-2 0-3 2-2 4"/></svg>;}
function PartnerWishArt({label}) {
  const id=`partner-wish-${useId().replace(/:/g,"")}`;
  return <svg className="tg-partner-hand" viewBox="80 280 1140 840" preserveAspectRatio="xMidYMid meet" role="img" aria-label={label}>
    <defs><mask id={id} x="80" y="280" width="1140" height="840" maskUnits="userSpaceOnUse" maskContentUnits="userSpaceOnUse" style={{maskType:"alpha"}}><image href={`/media/icons/${ROOM_ART.klienti}`} x="0" y="0" width="1254" height="1254"/></mask></defs>
    <rect x="80" y="280" width="1140" height="840" fill="currentColor" mask={`url(#${id})`}/>
  </svg>;
}
// Original line illustration: two stems sharing space, without a medical/lunar prediction claim.
export function TogetherArt(){return <svg viewBox="0 0 180 140" fill="none" stroke="currentColor" strokeWidth="1" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M34 123C57 120 75 98 80 71S81 25 59 18M151 124C120 117 97 96 96 64s11-45 28-50M73 93C49 86 46 65 37 64c21-3 35 6 40 20M99 88c25-2 38-21 44-31-27 0-39 11-44 21M80 63C61 57 55 43 52 36c20 1 27 11 29 20M98 55c18-7 25-20 30-29-22 4-26 12-28 23M70 104c6 11 11 18 20 25 10-8 18-18 22-27M39 117c28-6 47-3 52 7 12-9 34-9 51-4"/><path d="M58 18c8 1 16 4 20 10M59 18c4 7 7 13 6 21M124 14c-4 9-8 14-15 18M124 14c-8 1-15 5-18 10M40 69l34 18M140 63l-36 18M55 39l22 18M126 30l-25 19"/><path d="M29 103c-9-23-6-48 7-66M150 37c12 18 15 43 6 66" strokeDasharray="1 5"/><circle cx="89" cy="17" r="6"/><path d="M86 12c-5 6-2 10 5 10M83 130h17M17 120l4-4m-2 0v7m140-10 5 3m-5 1 5-4"/></svg>;}
const errors={"question-answered":["K této otázce už patří uložená odpověď. Vyberte jinou pro rozhovor naživo; zapsaný rozhovor zůstane u původní otázky.","This question already has a saved answer. Choose another for a live conversation; the saved conversation keeps its original question."],"question-changed":["Otázka se mezitím změnila. Rozepsaná odpověď zůstává. Obnov přehled a zkontroluj, k jaké otázce patří.","The question changed. Your draft remains. Refresh the page and check which question it answers."],"owner-not-configured":["Spolu ještě nemá na serveru nastaveného vlastníka aplikace. Je potřeba dokončit nastavení hostingu; opakované přihlášení nepomůže.","Together has no application owner configured on the server. Hosting setup must be completed; signing in again will not fix this."],"sign-in-required":["Přihlášení vypršelo. Přihlas se znovu a obnov přehled.","Your session expired. Sign in again and refresh."],"invalid-server-response":["Server místo údajů Spolu vrátil webovou stránku. Zkus obnovit aplikaci; pokud chyba trvá, je potřeba opravit směrování na serveru.","The server returned a web page instead of Together data. Refresh the app; if it persists, server routing needs repair."],conflict:["Mezitím se údaje změnily. Rozepsaný text zůstává tady. Obnov přehled a zkontroluj ho před uložením.","Data changed elsewhere. Your draft is still here. Refresh and review it before saving."],"invalid-invite":["Kód už neplatí nebo byl použit. Nový kód vytvoří druhý člověk.","This code expired or was used. Your partner can create a new one."],"not-connected":["Pro tuto akci nejdřív potvrďte propojení.","Confirm the connection first."],"connection-exists":["Nejdřív ukonči současné propojení.","Disconnect the existing connection first."],"invalid period dates":["Zkontroluj data menstruace. Zápisy mají být skutečné, ne budoucí odhady.","Check period dates. Record actual dates, not future estimates."],"overlapping periods":["Záznamy menstruace se překrývají. Oprav jejich začátek nebo konec.","Period records overlap. Correct their start or end."],"invalid-plan":["Vyplň název, datum, čas a délku alespoň 10 minut.","Enter a title, date, time and duration of at least 10 minutes."]};
export function TogetherPage(props) {
  const account=usePersonalProfile();
  return <TogetherWorkspace key={account.accountKey||"unverified"} {...props} account={account}/>;
}
function TogetherWorkspace({t,lang="cs",Header,Sheet,getPages,role="coach",account}) {
  const L=(cs,en)=>lang==="en"?en:cs;
  const {profile,accountKey}=account;
  const request=useMemo(()=>createTogetherAccountRequest({accountKey,verified:isPersonalProfileVerified,refresh:refreshPersonalProfile}),[accountKey]);
  const [tab,setTab]=useState("today"),[data,setData]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [day,setDay]=useState(dateKey()),[cycleDay,setCycleDay]=useState(dateKey()),[entry,setEntry]=useState({}),[dirty,setDirty]=useState(false),[baseRev,setBaseRev]=useState(0);
  const [period,setPeriod]=useState({start:dateKey(),end:""}),[code,setCode]=useState(""),[invite,setInvite]=useState(""),[scopes,setScopes]=useState([]),[answer,setAnswer]=useState("");
  const [cycleSelection,setCycleSelection]=useState(0);
  const selectCycleDay=value=>{setCycleDay(value);setCycleSelection(v=>v+1);};
  const [answerContext,setAnswerContext]=useState(null);
  const [dateOpen,setDateOpen]=useState(false),[dayWindow,setDayWindow]=useState(null),[practiceOpen,setPracticeOpen]=useState(false);
  const [plan,setPlan]=useState(null),[mode,setMode]=useState("observe"),[length,setLength]=useState(28);
  const pageRef=useRef(null),planHeadingRef=useRef(null),[focusRequest,setFocusRequest]=useState(null);
  const periodDirty=useRef(false),journalDirty=useRef(false),[journalReset,setJournalReset]=useState(0);
  const generation=useRef(0),mounted=useRef(true),editing=useRef(false),snapshot=useRef(null),dayRef=useRef(day),answerDirty=useRef(false),cycleDirty=useRef(false),scopesDirty=useRef(false),scopeRevision=useRef(null);
  dayRef.current=day;
  const cycleDayRef=useRef(cycleDay);cycleDayRef.current=cycleDay;
  editing.current=dirty;
  const fetchSnapshot=async()=>{
    const current=++generation.current;
    try{const d=await request(`/api/together?date=${dateKey()}&viewDate=${cycleDayRef.current}`);
      if(!mounted.current||current!==generation.current)return;
      snapshot.current=d;setData(d);setError("");if(!scopesDirty.current){setScopes(d.link?.myScopes||d.link?.scopes||[]);scopeRevision.current=d.link?.revision;}
      if(!editing.current){setEntry(d.self.doc.days[dayRef.current]||{});setBaseRev(d.self.revision);}
      if(!cycleDirty.current){setMode(d.self.doc.mode);setLength(d.self.doc.usualLength);}
      if(!answerDirty.current){setAnswer(d.answer.mine);setAnswerContext({question:d.question,day:d.today,linkId:d.link?.id,linkRevision:d.link?.revision});}
    }catch(e){if(mounted.current&&current===generation.current){snapshot.current=null;setData(null);setError(errors[e.message]?L(...errors[e.message]):L("Přehled se nepodařilo načíst. Připoj se a zkus to znovu; změny zatím nejsou uložené.","Could not load the page. Reconnect and retry; changes have not been saved."));}}
  };
  useEffect(()=>{if(data)fetchSnapshot();},[cycleDay]);
  useEffect(()=>{mounted.current=true;fetchSnapshot();const focus=()=>{if(document.visibilityState==="visible")fetchSnapshot();else{generation.current++;setData(null);snapshot.current=null;}};const offline=()=>{generation.current++;snapshot.current=null;setData(null);setError(L("Jsi offline. Připoj se pro načtení a uložení.","You are offline. Reconnect to load and save."));};window.addEventListener("offline",offline);const timer=setInterval(()=>{if(document.visibilityState==="visible")fetchSnapshot();},30000);document.addEventListener("visibilitychange",focus);window.addEventListener("focus",focus);window.addEventListener("online",focus);window.addEventListener("tm-personal-profile-changed",focus);return()=>{mounted.current=false;generation.current++;clearInterval(timer);document.removeEventListener("visibilitychange",focus);window.removeEventListener("focus",focus);window.removeEventListener("online",focus);window.removeEventListener("offline",offline);window.removeEventListener("tm-personal-profile-changed",focus);};},[]);
  const save=async(path,body,kind)=>{
    if(busy)return false;setBusy(true);setError("");setNotice("");
    try{const d=await request(`/api/together/${path}?date=${dateKey()}`,{method:["invite","claim","disconnect"].includes(path)?"POST":"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});
      if(!mounted.current)return false;
      if(path==="invite")setInvite(d.code);if(path==="self"&&kind!=="entry"&&baseRev===body.revision)setBaseRev(d.revision);if(kind==="entry"){editing.current=false;setDirty(false);}if(kind==="cycle")cycleDirty.current=false;if(path==="answer")answerDirty.current=false;if(path==="sharing")scopesDirty.current=false;if(path==="disconnect"){setInvite("");setCode("");setPlan(null);setAnswer("");answerDirty.current=false;scopesDirty.current=false;}setNotice(L("Uloženo.","Saved."));await fetchSnapshot();return true;
    }catch(e){setError(errors[e.message]?L(...errors[e.message]):L("Nepodařilo se uložit. Text zůstává rozepsaný, zkus to znovu.","Could not save. Your draft is retained; try again."));return false;}finally{setBusy(false);}
  };
  const own=data?.self.doc||emptyTogether(), canTrack=data?.canTrack===true,cycleOwner=data?.cycleOwner===true,active=data?.link?.status==="active";
  const hasPartnerWellbeing=Boolean(data?.partner?.wellbeing?.mood||data?.partner?.wellbeing?.energy);
  const cycleView=canTrack?cycleViewForDate(own,cycleDay,dateKey()):(data?.cycleView?.date===cycleDay?data.cycleView:null);
  const summary=cycleView?.cycle,phase=cycleView?.phase;
  const skyDay=tab==="cycle"?cycleDay:day;
  const skyCycle=canTrack?cycleViewForDate(own,skyDay,dateKey()):cycleView?.date===skyDay?cycleView:null;
  const cycleDetails=canTrack?{cycleNote:{text:own.days[cycleDay]?.cycleNote||""},pain:{value:own.days[cycleDay]?.pain},flow:{value:own.days[cycleDay]?.flow}}:cycleView;
  const dateLabel=d=>new Date(d+"T12:00:00").toLocaleDateString(lang==="en"?"en-GB":"cs-CZ",{day:"numeric",month:"long"});
  const today=dateKey(), question=(answerDirty.current?answerContext?.question?.text:data?.question?.text)||questionFor(today);
  const staleAnswer=answerDirty.current&&(answerContext?.question?.id!==data?.question?.id||answerContext?.day!==data?.today||answerContext?.linkId!==data?.link?.id||answerContext?.linkRevision!==data?.link?.revision);
  const answerBody=value=>({answer:value,questionId:answerContext?.question?.id,questionDay:answerContext?.day,linkId:answerContext?.linkId,linkRevision:answerContext?.linkRevision});
  const chooseQuestion=async questionId=>{
    if(answerDirty.current){setError(L("Nejdřív dokonči rozepsanou odpověď. Změna otázky ji nesmaže.","Finish your draft first. Changing the question will not discard it."));return false;}
    return save("question",{questionId,questionDay:data.today,previousQuestionId:data.question?.id,linkId:data.link?.id,linkRevision:data.link?.revision});
  };
  const upcoming=(data?.plans||[]).filter(p=>p.status==="planned"&&p.date>=today).toSorted((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))[0];
  const navigateTo=(next,target="view")=>{setTab(next);setFocusRequest({tab:next,target});};
  const propose=(p,{afterOverlay=false}={})=>{setPlan(p);setTab("plans");setFocusRequest({tab:"plans",target:"plan",afterOverlay});};
  useEffect(()=>{
    if(!focusRequest||focusRequest.tab!==tab)return;
    let frame,timer;
    const focusTarget=()=>{
      const root=pageRef.current;
      const navigationTarget=root?.querySelector(`[data-tg-nav="${tab}"]`);
      const target=focusRequest.target==="practice"?root?.querySelector(".tg-practice>summary"):focusRequest.target==="plan"?planHeadingRef.current:focusRequest.target==="tab"?navigationTarget:root?.querySelector(`[data-tg-view="${tab}"] > h2`)||navigationTarget;
      if(!target)return;
      target.focus({preventScroll:true});
      target.scrollIntoView({behavior:"auto",block:"start"});
      setFocusRequest(null);
    };
    const schedule=()=>{clearTimeout(timer);cancelAnimationFrame(frame);frame=requestAnimationFrame(focusTarget);};
    // Sheets consume their history entry on close. Wait for its scroll restoration
    // before focusing a new plan, otherwise the browser can move the form offscreen.
    if(focusRequest.afterOverlay){window.addEventListener("popstate",schedule,{once:true});timer=setTimeout(schedule,300);}
    else schedule();
    return()=>{cancelAnimationFrame(frame);clearTimeout(timer);window.removeEventListener("popstate",schedule);};
  },[focusRequest,tab,plan,data]);
  const fmtSummary=summary?.next?`${dateLabel(summary.next.from)} – ${dateLabel(summary.next.to)}`:L("Bez odhadu další menstruace","No estimate for the next period");
  const setField=(key,value)=>{setEntry(e=>({...e,[key]:value}));setDirty(true);};
  const selectDay=next=>{if(!next)return false;if(next===day)return true;if(dirty&&!window.confirm(L("Opustit neuložený zápis?","Discard the unsaved check-in?")))return false;setDay(next);setEntry(own.days[next]||{});setBaseRev(data.self.revision);setDirty(false);setDateOpen(false);return true;};
  const updateDoc=patch=>save("self",{revision:patch.days?baseRev:data.self.revision,doc:{...own,...patch}},patch.days?"entry":patch.mode?"cycle":"period");
  const refresh=()=>{if((editing.current||answerDirty.current||cycleDirty.current||scopesDirty.current||journalDirty.current||periodDirty.current||plan)&&!window.confirm(L("Zahodit neuložené úpravy a načíst aktuální stav?","Discard unsaved edits and load the current version?")))return;editing.current=false;setDirty(false);answerDirty.current=false;cycleDirty.current=false;scopesDirty.current=false;periodDirty.current=false;setPeriod({start:day<=today?day:today,end:""});setJournalReset(n=>n+1);setPlan(null);fetchSnapshot();};
  const section=(title,children,headingRef=null)=><section className="tm-together-section" data-tg-view={tab}><h2 ref={headingRef} tabIndex={-1}>{title}</h2>{children}</section>;
  const button=(label,fn,primary=false,disabled=false)=><button type="button" className={primary?"primary":""} onClick={fn} disabled={busy||disabled}>{label}</button>;
  const openDayWindow=selected=>{if(!selectDay(selected))return;setCycleDay(selected);setDayWindow("entry");if(!periodDirty.current&&!period.originalStart)setPeriod({start:selected<=today?selected:today,end:""});};
  const dayEntry=<><fieldset className="tg-entry-fields" disabled={day>today||busy}>
        <label htmlFor="tg-mood">{L("Jak mi je","How I feel")}</label><input id="tg-mood" className="tm-navod" maxLength={80} value={entry.mood||""} onChange={e=>setField("mood",e.target.value)} placeholder={L(profile.wording==="male"?"Je mi dobře, jen jsem trochu unavený…":profile.wording==="female"?"Je mi dobře, jen jsem trochu unavená…":"Jak se dnes cítím…","How I feel today…")}/>
        <label htmlFor="tg-support">{L("Co by mi od tebe pomohlo","What would help from you")}</label>
        <div className="tg-needs" role="group" aria-label={L("Náměty podpory","Support ideas")}>{[["Chvíle spolu","Time together","Dnes by mi udělala dobře chvíle s tebou.","I would enjoy some time with you today."],["Vyslechnout","Listen","Pomohlo by mi, kdyby tu byl prostor mě jen vyslechnout.","It would help if you could simply listen."],["S něčím pomoct","A hand","Ocením dnes s něčím pomoct. Domluvíme se?","I could use a hand today. Can we talk about it?"],["Trochu prostoru","Some space","Potřebuji dnes trochu času pro sebe.","I need a little time to myself today."]].map(([cs,en,textCs,textEn])=><button key={cs} type="button" aria-pressed={entry.support===L(textCs,textEn)} onClick={()=>setField("support",entry.support===L(textCs,textEn)?"":L(textCs,textEn))}>{L(cs,en)}</button>)}</div>
        <TogetherText id="tg-support" rows={1} maxLength={300} value={entry.support||""} onChange={e=>setField("support",e.target.value)} placeholder={L("Nebo to řekni po svém…","Or say it in your own words…")}/>
        <details className="tg-optional"><summary>{L("Další údaje · energie a poznámka","More details · energy and note")}</summary>
          <label>{L("Kolik mám energie","My energy")}</label><div className="row" role="group" aria-label={L("Energie","Energy")}>{[1,2,3,4,5].map(n=><button key={n} aria-pressed={entry.energy===n} style={{background:entry.energy===n?t.callout:"transparent"}} onClick={()=>setField("energy",entry.energy===n?null:n)}>{n}</button>)}</div><p className="hint">{L("1 · spíš odpočívat, 5 · energie mám dost. Můžeš nechat prázdné.","1 · could use rest, 5 · plenty of energy. You can leave this blank.")}</p>
          {canTrack&&<div className="fields"><label>{L("Krvácení","Bleeding")}<select value={entry.flow||"none"} onChange={e=>setField("flow",e.target.value)}>{[["none","Žádné","None"],["spotting","Špinění","Spotting"],["light","Slabé","Light"],["medium","Střední","Medium"],["heavy","Silné","Heavy"]].map(([v,cs,en])=><option key={v} value={v}>{L(cs,en)}</option>)}</select></label><label>{L("Bolest","Pain")}<select value={entry.pain||"none"} onChange={e=>setField("pain",e.target.value)}>{[["none","Žádná","None"],["mild","Mírná","Mild"],["moderate","Střední","Moderate"],["strong","Silná","Strong"]].map(([v,cs,en])=><option key={v} value={v}>{L(cs,en)}</option>)}</select></label></div>}
          <label htmlFor="tg-note">{canTrack?L("Poznámka k mému cyklu","A note on my cycle"):L("Moje soukromá poznámka","My private note")}</label><TogetherText id="tg-note" placeholder={L("Co dnes vnímám v těle a v sobě…","What I notice in my body and myself today…")} maxLength={1500} value={(canTrack?entry.cycleNote:entry.note)||""} onChange={e=>setField(canTrack?"cycleNote":"note",e.target.value)}/>{canTrack&&entry.note&&<TogetherFold title={L("Starší soukromá poznámka","Earlier private note")}><TogetherText aria-label={L("Starší soukromá poznámka","Earlier private note")} placeholder={L("Moje slova, jen pro mě…","My words, just for me…")} value={entry.note} maxLength={1500} onChange={e=>setField("note",e.target.value)}/><p className="hint">{L("Tento dřívější zápis se nesdílí.","This earlier entry is never shared.")}</p></TogetherFold>}
        </details>
        {day!==today&&<p className="hint">{L("Upravuješ zápis z","Editing your check-in from")} {dateLabel(day)}.</p>}
        <p className="hint">{!active?L("Zápis zatím vidíš jen ty. Po propojení zvolíš, co chceš sdílet.","Only you can see this for now. Choose what to share after connecting."):L("Pocit, energii a přání druhý uvidí podle tvých voleb v Propojení a sdílení. Soukromá poznámka zůstane tvoje; údaje o cyklu mají samostatné volby.","The other person sees feelings, energy and wishes according to your Connection and sharing choices. Private notes stay yours; cycle details have separate choices.")}</p>
        {button(L("Uložit můj zápis","Save my check-in"),()=>updateDoc({days:{...own.days,[day]:entry}}),true,!dirty||day>today)}
        {dirty&&<p className="hint" role="status">{L("Rozepsáno. Ještě neuloženo ani sdíleno.","Draft. Not saved or shared yet.")}</p>}</fieldset>{day>today&&<p className="hint">{L("Zápis otevřeme, až tento den přijde. Jeho astrologii už můžeš prozkoumat přes kresbu nahoře.","Check in when this day arrives. You can already explore its astrology using the illustration above.")}</p>}</>;
  const periodEditor=canTrack?<><div className="fields"><label>{L("První den","First day")}<input type="date" max={today} value={period.start} onInput={e=>{periodDirty.current=true;setPeriod(p=>({...p,start:e.target.value}));}}/></label><label>{L("Poslední den · nepovinný","Last day · optional")}<input type="date" min={period.start} max={today} value={period.end} onInput={e=>{periodDirty.current=true;setPeriod(p=>({...p,end:e.target.value}));}}/></label></div>{button(L("Uložit menstruaci","Save period"),async()=>{const next=[...own.periods.filter(p=>p.start!==(period.originalStart||period.start)),{start:period.start,end:period.end||null}];if(await updateDoc({periods:next})){periodDirty.current=false;setPeriod({start:day<=today?day:today,end:""});}},true)}<p className="hint">{L("Záznam upravíš výběrem jeho data níže. Začátek je první den menstruace, ne špinění.","Choose a record below to edit it. Start means the first period day, not spotting.")}</p><h3>{L("Zapsané menstruace","Recorded periods")}</h3>{own.periods.length?own.periods.toReversed().map(p=><div className="item row" key={p.start}><span style={{flex:1}}>{dateLabel(p.start)}{p.end?` – ${dateLabel(p.end)}`:""}</span>{button(L("Upravit","Edit"),()=>{if(periodDirty.current&&!window.confirm(L("Nahradit rozepsaný záznam menstruace?","Replace the unsaved period record?")))return;periodDirty.current=true;setPeriod({start:p.start,end:p.end||"",originalStart:p.start});setDayWindow("period");})}{button(L("Odebrat","Remove"),()=>{if(window.confirm(L("Odebrat tento záznam menstruace?","Remove this period record?")))updateDoc({periods:own.periods.filter(x=>x.start!==p.start)});})}</div>):<p>{L("Tvoje historie začne prvním skutečným zápisem.","Your history starts with your first actual record.")}</p>}</>:null;
  const cycleSettings=canTrack?<><label>{L("Režim cyklu","Cycle mode")}<select value={mode} onChange={e=>{setMode(e.target.value);cycleDirty.current=true;}}><option value="observe">{L("Jen záznamy, bez odhadů","Records only, no estimates")}</option><option value="estimate">{L("Orientační odhad menstruace","Approximate period estimate")}</option><option value="paused">{L("Pauza v odhadech","Pause estimates")}</option></select></label><label>{L("Moje obvyklá délka cyklu ve dnech","My usual cycle length in days")}<input type="number" min="15" max="90" value={length} onChange={e=>{setLength(Number(e.target.value));cycleDirty.current=true;}}/></label><p className="hint">{L("Bez historie se použije tato délka. Pro antikoncepci, těhotenství, období po porodu či nepravidelný cyklus zvol jen záznamy nebo pauzu.","Without history, this length is used. For hormonal contraception, pregnancy, postpartum or irregular cycles, use records only or pause.")}</p>{button(L("Uložit nastavení cyklu","Save cycle settings"),()=>updateDoc({mode,usualLength:length}),true)}</>:null;
  const sharedDay=!canTrack?<section><h3>{L("Co druhý z vás sdílí k tomuto dni","What your partner shares for this day")}</h3>
        {cycleDetails?.cycleNote?.text&&<p className="tg-personal">{cycleDetails.cycleNote.text}</p>}
        {cycleDetails?.pain?.value&&<p>{L("Bolest","Pain")}: {L(...({none:["žádná","none"],mild:["mírná","mild"],moderate:["střední","moderate"],strong:["silná","strong"]}[cycleDetails.pain.value]||["nezapsáno","not recorded"]))}</p>}
        {cycleDetails?.flow?.value&&<p>{L("Krvácení","Bleeding")}: {L(...({none:["žádné","none"],spotting:["špinění","spotting"],light:["slabé","light"],medium:["střední","medium"],heavy:["silné","heavy"]}[cycleDetails.flow.value]||["nezapsáno","not recorded"]))}</p>}{!cycleDetails?.cycleNote?.text&&!cycleDetails?.pain?.value&&!cycleDetails?.flow?.value&&<p className="hint">{L("K tomuto dni nejsou sdílené další údaje.","No further details are shared for this day.")}</p>}</section>:null;
  const conversationDaily=data?(active?<><p className="tg-personal">{L(...question)}</p><p className="hint">{L("Každý odpovězte za sebe. Odpovědi se vám navzájem ukážou, až je odešlete oba. Můžete si také jen popovídat bez zápisu.","Answer in your own words. You see each other's answers after both have shared. You can also simply talk without writing anything down.")}</p><label htmlFor="tg-answer">{L("Co mi k tomu přichází","What comes to mind")}</label><TogetherText id="tg-answer" value={answer} maxLength={1500} onChange={e=>{setAnswer(e.target.value);answerDirty.current=true;}} placeholder={L("Nemusí to být dokonalá odpověď…","It does not need to be a perfect answer…")}/><div className="row">{button(L("Sdílet moji odpověď","Share my answer"),()=>save("answer",answerBody(answer)),true,!answer.trim()||staleAnswer)}{data.answer.mine&&button(L("Odebrat moji odpověď","Remove my answer"),async()=>{if(staleAnswer)return;if(!window.confirm(L("Odebrat svou odpověď z rozhovoru? Rozepsané úpravy se také zahodí.","Remove your answer from this conversation? Any unsaved edits will also be discarded.")))return;if(await save("answer",answerBody(""))){setAnswer("");answerDirty.current=false;}})}</div>{staleAnswer&&<div role="alert"><p>{L("Otázka nebo propojení se mezitím změnily. Rozepsanou odpověď teď nelze sdílet. Než začneš znovu, můžeš si svůj text zkopírovat.","The question or connection changed. This draft cannot be shared. You can copy your words before starting again.")}</p>{button(L("Načíst aktuální rozhovor","Load the current conversation"),refresh)}</div>}{answerDirty.current&&<p className="hint">{L("Rozepsáno, ještě nesdíleno.","Draft, not shared yet.")}</p>}{data.answer.partner?<div className="tg-partner-answer"><h3>{L("Druhý z nás","Your partner")}</h3><p>{data.answer.partner}</p></div>:<p className="hint">{L("Zatím tu nejsou obě odpovědi. Není kam spěchat.","Both answers are not here yet. There is no hurry.")}</p>}</>:<><p>{L("Náměty níže můžete zkusit rovnou. Pro ukládání a vzájemné sdílení odpovědí nejdřív propojte účty.","You can try the invitations below straight away. Connect accounts to save and share your answers.")}</p>{button(L("Propojit účty","Connect accounts"),()=>navigateTo("sharing"))}</>):null;
  if(account.status!=="ready")return <div className="tm-together" style={togetherTheme(t)}><style>{togetherStyles}</style>{Header?<Header pageKey="spolu" icon={<TogetherIcon size={38}/>}>{L("Spolu","Together")}</Header>:<h1>{L("Spolu","Together")}</h1>}<p role="status">{L("Ověřuji účet pro váš společný prostor…","Verifying the account for your shared space…")}</p>{!["loading","checking"].includes(account.status)&&<button type="button" onClick={account.refresh}>{L("Ověřit účet","Verify account")}</button>}</div>;
  return <div ref={pageRef} className="tm-together" style={togetherTheme(t)}>
    <style>{togetherStyles}</style>
    <div className="tg-header"><div>{Header?<Header pageKey="spolu" icon={<TogetherIcon size={38}/>}>{L("Spolu","Together")}</Header>:<h1>{L("Spolu","Together")}</h1>}</div><MoonCompanion ownCycle={canTrack} cycle={skyCycle} day={skyDay} lang={lang} Sheet={Sheet} t={t} onPlan={active?p=>propose({...p,date:p.date||(tab==="cycle"?cycleDay:day),time:p.time||"18:00"},{afterOverlay:true}):null}/><div className="tg-intro-row"><p className="tg-intro">{L("Chvíle pro vás dva. Taková, na kterou dnes máte prostor.","A moment for the two of you. Whatever you have room for today.")}</p><button data-guide="spolu.connection" className="tg-text-button tg-sharing-trigger" type="button" aria-expanded={tab==="sharing"||tab==="pages"} onClick={()=>navigateTo(tab==="sharing"||tab==="pages"?"today":"sharing","tab")}>{L("Propojení a sdílení","Connection and sharing")}</button></div></div>
    <nav data-guide="spolu.tabs" className="tabs" aria-label={L("Přehled Spolu","Together views")}>{[["today","Dnes","Today"],["conversations","Rozhovory","Conversations"],["plans","Plány","Plans"],["cycle","Cyklus","Cycle"]].map(([id,cs,en])=><button key={id} type="button" data-tg-nav={id} aria-pressed={tab===id} onClick={()=>navigateTo(id,"tab")}>{L(cs,en)}</button>)}</nav>
    {(tab==="sharing"||tab==="pages")&&<nav className="row tg-settings-nav" aria-label={L("Nastavení Spolu","Together settings")}><button type="button" data-tg-nav="sharing" aria-pressed={tab==="sharing"} onClick={()=>navigateTo("sharing","tab")}>{L("Naše propojení","Our connection")}</button><button type="button" data-tg-nav="pages" aria-pressed={tab==="pages"} onClick={()=>navigateTo("pages","tab")}>{L("Sdílené stránky","Shared pages")}</button></nav>}
    {error&&<div role="alert" className="error"><p>{error}</p>{button(L("Obnovit přehled","Refresh"),refresh)}</div>}
    {notice&&<div className="notice" role="status">{notice}</div>}
    {!data&&!error&&<p role="status">{L("Načítám váš prostor…","Loading your space…")}</p>}
    {!data&&error&&<p>{L("Spolu používá dva oddělené přihlášené účty. Každý spravuje své údaje a potvrzuje své sdílení.","Together uses two separate signed-in accounts. Each person manages their own details and chooses what to share.")}</p>}
    {data&&tab==="today"&&<>

      {!active&&<section className="tm-together-section"><h2>{L("Váš prostor může začít tady","Your space can begin here")}</h2><p>{L("Zápis si můžeš udělat už teď. Propojení vám otevře společné plány a rozhovory.","You can check in already. Connecting opens up shared plans and conversations.")}</p>{button(L("Propojit naše účty","Connect our accounts"),()=>navigateTo("sharing"))}</section>}
      {active&&<section className="tm-together-section tg-partner">{data.partner?.support?.text||hasPartnerWellbeing?<><h2>{L("Od druhého z nás","From your partner")}</h2>{data.partner?.support?.text&&<p className="tg-personal">{data.partner.support.text}</p>}{hasPartnerWellbeing&&<p className="hint">{data.partner.wellbeing.mood}{data.partner.wellbeing.energy?` · ${L("energie","energy")} ${data.partner.wellbeing.energy}/5`:""}</p>}</>:<PartnerWishArt label={L("Dnes tu zatím není žádné přání od druhého z nás.","No wish has been shared by your partner today.")}/>}</section>}
      {section(L("Co by ti dnes udělalo dobře?","What would feel good today?"),<>
        <p>{L("Klidně jen jedna věta. Nemusíš mít všechno pojmenované.","A single sentence is enough. You do not need to have it all figured out.")}</p>
      <div className="tg-date-row"><button type="button" aria-label={L("Předchozí den","Previous day")} onClick={()=>selectDay(addDays(day,-1))}><TmIcon id="back" size={14}/></button><button type="button" className="tg-date" aria-expanded={dateOpen} aria-controls="tg-date-chooser" onClick={()=>setDateOpen(v=>!v)}>{new Date(day+"T12:00:00").toLocaleDateString(lang==="en"?"en-GB":"cs-CZ")}</button><button type="button" aria-label={L("Další den","Next day")} onClick={()=>selectDay(addDays(day,1))}><TmIcon id="forward" size={14}/></button><button type="button" className="tg-date-today" onClick={()=>selectDay(today)}>{L("Dnes","Today")}</button></div>
      <div className="tg-date-chooser" id="tg-date-chooser" hidden={!dateOpen}><TogetherCalendar picker showCycle={false} selectedDate={day} onDateChange={selectDay} recordDates={Object.keys(own.days)} showDetails={false} lang={lang} t={t}/></div>{dayEntry}
      </>)}
      {active&&<section className="tm-together-section"><h2>{L("Na co máme prostor","What we have room for")}</h2>{upcoming?<><p className="tg-personal">{upcoming.title}</p><p>{dateLabel(upcoming.date)} · {upcoming.time} · {upcoming.approved.owner&&upcoming.approved.partner?L("Domluveno","Agreed"):L("Zatím návrh","Still a proposal")}</p></>:<p>{L("Společný čaj, procházka nebo pár minut bez spěchu. Co by bylo příjemné vám oběma?","Tea together, a walk, or a few unhurried minutes. What would feel good to both of you?")}</p>}<div className="row tg-actions">{upcoming?button(L("Otevřít domluvu","Open our plan"),()=>navigateTo("plans")):button(L("Domluvit chvíli","Make a little time"),()=>propose({title:"",date:today,time:"18:00",minutes:30,note:""}))}{button(L("Otevřít rozhovory","Open conversations"),()=>navigateTo("conversations"))}</div></section>}
    </>}
    {data&&tab==="conversations"&&<>
      <div className="overview"><strong>{L("Místo, kde se můžeme slyšet","Room to hear each other")}</strong><p>{L("Někdy stačí naslouchat. Vyberte si, na co právě máte chuť, a zbytek nechte být.","Sometimes listening is enough. Choose what feels right and leave the rest.")}</p></div>
    </>}
    {data&&tab==="cycle"&&<>
      {section(canTrack?L("Můj cyklus","My cycle"):L("Sdílený cyklus","Your partner’s cycle"),<>
        <p className="hint">{dateLabel(cycleDay)}</p>
        <strong className="tg-cycle-phase">{phase?.id?L(...CYCLE_GUIDE[phase.id].name):L("Fáze zatím neurčená","Phase not determined")}</strong>
        <p>{summary?.day?`${L("Den","Day")} ${summary.day}`:""}{phase?.basis==="estimated"?L(" · odhad podle kalendáře"," · calendar estimate"):phase?.basis==="recorded"?L(" · podle zápisu"," · recorded"):""}</p>
        {summary?.next&&<p className="hint">{L("Další menstruace přibližně","Next period approximately")}: {fmtSummary}</p>}
        {!canTrack&&!summary&&!phase&&<p>{L("Druhý z vás zatím fázi cyklu nesdílí.","Your partner is not sharing her cycle phase.")}</p>}
      </>)}
      {(canTrack||(data.link?.receivedScopes||data.link?.scopes)?.some(s=>["cycle","phase","cycle-note","pain","flow"].includes(s)))&&<TogetherCalendar periods={canTrack?own.periods:[]} summary={summary} phase={phase} plans={data.plans} selectedDate={cycleDay} onDateChange={selectCycleDay} onOpenDay={openDayWindow} lang={lang} t={t}/>}
      <section className="tm-together-section tg-cycle-atlas-section">
        <PhaseGuide key={`${cycleDay}:${cycleSelection}`} embedded phase={phase} role={canTrack?"client":"coach"} wording={profile.wording} date={cycleDay} lang={lang} onPlan={active?title=>propose({title,date:cycleDay,time:"18:00",minutes:30,note:""}):null}/>
      </section>

    </>}
    {data&&tab==="plans"&&<>
      {section(L("Náš společný čas","Our time together"),<><p>{L("Na něco se těšit je hezké. Z návrhu bude domluva, až vám oběma sedne čas i chuť.","It is good to have something to look forward to. A proposal becomes a plan when it works for both of you.")}</p>{!active?button(L("Nejdřív se propojit","Connect first"),()=>navigateTo("sharing")):button(L("Domluvit chvíli","Make a little time"),()=>propose({title:"",date:today,time:"18:00",minutes:30,note:""}),true)}</>)}
      {active&&plan&&section(plan.id?L("Upravit návrh","Edit proposal"):L("Naše příští chvíle","Our next moment"),<><label>{L("Co podnikneme","What shall we do")}<input className="tm-navod" placeholder={L("Na co se spolu těšíme…","What we look forward to together…")} value={plan.title} maxLength={120} onChange={e=>setPlan(p=>({...p,title:e.target.value}))}/></label><div className="fields"><label>{L("Datum","Date")}<input type="date" value={plan.date} onChange={e=>setPlan(p=>({...p,date:e.target.value}))}/></label><label>{L("Čas","Time")}<input type="time" value={plan.time} onChange={e=>setPlan(p=>({...p,time:e.target.value}))}/></label></div><label>{L("Délka v minutách","Duration in minutes")}<input type="number" min="10" max="1440" value={plan.minutes} onChange={e=>setPlan(p=>({...p,minutes:Number(e.target.value)}))}/></label><label>{L("Poznámka pro oba","Note for both")}<TogetherText placeholder={L("Místo, přání nebo malá domluva…","A place, a wish or a small agreement…")} value={plan.note} maxLength={600} onChange={e=>setPlan(p=>({...p,note:e.target.value}))}/></label><div className="row">{button(L("Poslat návrh","Send proposal"),async()=>{if(await save("plan",plan))setPlan(null);},true)}{button(L("Zrušit úpravu","Cancel editing"),()=>setPlan(null))}</div></>,planHeadingRef)}
      {active&&section(L("Na čem se domlouváme","What we are planning"),data.plans.some(p=>p.status==="planned")?data.plans.filter(p=>p.status==="planned").toSorted((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(p=><details className="tg-plan-row" key={p.id}><summary><span>{p.title}<small>{dateLabel(p.date)} · {p.time} · {p.minutes} min<br/>{p.status==="done"?L("Proběhlo","Completed"):p.approved.owner&&p.approved.partner?L("Potvrzeno oběma","Confirmed by both"):L("Zatím návrh · druhý ho může potvrdit","A proposal · your partner can confirm it")}</small></span></summary>{p.note&&<p>{p.note}</p>}{p.status!=="done"&&<div className="row">{!p.approved[cycleOwner?"owner":"partner"]&&button(L("Potvrdit","Confirm"),()=>save("plan",{id:p.id,revision:p.revision,action:"confirm"}),true)}{button(L("Upravit","Edit"),()=>propose(p))}{p.approved.owner&&p.approved.partner&&button(L("Proběhlo","Complete"),()=>save("plan",{id:p.id,revision:p.revision,action:"done"}))}{button(L("Zrušit plán","Cancel plan"),()=>save("plan",{id:p.id,revision:p.revision,action:"cancel"}))}</div>}</details>):<p>{L("Zatím nic domluveného. Klidně začněte něčím malým, na co se těšíte oba.","Nothing agreed yet. Start with something small you can both look forward to.")}</p>)}
      {active&&<TogetherFold title={L("Kalendář společných plánů","Our plans calendar")}><TogetherCalendar showCycle={false} plans={data.plans} onOpenDay={openDayWindow} lang={lang} t={t}/></TogetherFold>}
      {active&&<TogetherInspiration lang={lang} onPlan={propose} Sheet={Sheet} t={t}/>}
      {active&&<TogetherPractice open={practiceOpen} onToggle={e=>setPracticeOpen(e.currentTarget.open)} data={data} canTrack={role==="client"} getPages={getPages} lang={lang} onPlan={propose} onSharing={()=>navigateTo("pages")} onOpenPractice={()=>{if((editing.current||answerDirty.current||journalDirty.current||plan)&&!window.confirm(L("Otevřít Praxi? Neuložené zápisy ve Spolu se zahodí.","Open Practice? Unsaved Together drafts will be discarded.")))return;window.location.assign("?open=praxe");}}/>}
    </>}
    <TogetherJournal embedded renderWeekly={weekly=><TogetherConversationMap lang={lang} slots={{daily:conversationDaily,questions:<FaceToFacePrompts embedded lang={lang} question={data?.question} onQuestionSelect={active?chooseQuestion:null} busy={busy} locked={Boolean(data?.answer?.mine||data?.answer?.partner)} draftPending={answerDirty.current}/>,moments:<TogetherRituals lang={lang} onPlan={active?propose:null}/>,weekly}}/>} unlinkedWeekly={<><p>{L("Pro společné ukládání ohlédnutí nejdřív propojte účty.","Connect your accounts to save reflections together.")}</p>{button(L("Propojit účty","Connect accounts"),()=>navigateTo("sharing"))}</>} Sheet={Sheet} t={t} data={data} lang={lang} save={save} busy={busy} view={tab} onPlan={propose} onDirty={v=>{journalDirty.current=v;}} reset={journalReset} onPractice={()=>{setPracticeOpen(true);navigateTo("plans","practice");}}/>
    {dayWindow&&Sheet&&<TogetherDayWindow Sheet={Sheet} t={t} lang={lang} day={day} panel={dayWindow} onPanel={setDayWindow} onClose={()=>setDayWindow(null)} canTrack={canTrack} available={!!data} error={error} notice={notice} onRefresh={refresh} entry={<>{sharedDay}{dayEntry}</>} period={periodEditor} orientation={cycleSettings}/>}
    {data&&tab==="sharing"&&<>
      {section(L("Dva účty, vaše rozhodnutí","Two accounts, your choice"),<><p>{L("Jeden z vás vytvoří kód, druhý jej zadá ve své aplikaci. Propojení začne až potvrzením toho, kdo kód vytvořil. Vlastní cyklus zapneš ve svém profilu; sdílení vždy volíš zvlášť.","One of you creates a code and the other enters it in their app. The connection starts only after the person who created the code confirms. Enable your own cycle in your profile; sharing remains a separate choice.")}</p><p><strong>{L("Stav","Status")}: {data.link?({invited:L("Kód čeká na použití","Code awaits use"),pending:L("Čeká na potvrzení","Awaiting your partner's confirmation"),active:L("Propojeno","Connected")}[data.link.status]):L("Nepřipojeno","Not connected")}</strong></p>
        {(!data.link||data.link.status==="invited")&&<>{button(L("Vytvořit nový kód","Create a new code"),()=>save("invite",{}),true)}{invite&&<><label>{L("Kód platí 24 hodin. Předej ho jen partnerovi.","Valid for 24 hours. Give it only to your partner.")}<input value={invite} readOnly onFocus={e=>e.target.select()}/></label>{button(L("Kopírovat kód","Copy code"),async()=>{try{await navigator.clipboard.writeText(invite);setNotice(L("Kód zkopírován.","Code copied."));}catch{setNotice(L("Označ kód a zkopíruj ho ručně.","Select and copy the code manually."));}})}</>}</>}
        {!data.link&&<><label>{L("Kód od druhého z vás","Code from your partner")}<input autoComplete="off" value={code} onChange={e=>setCode(e.target.value.trim())}/></label>{button(L("Požádat o propojení","Request connection"),()=>save("claim",{code}),true,!code)}</>}
        {(data.link?.status==="active"||(cycleOwner&&data.link?.status==="pending"))&&<><p>{L("Vyber, co smí druhý z vás vidět:","Choose what the other person may see:")}</p>{[["cycle","Den cyklu a odhad menstruace","Cycle day and period estimate"],["wellbeing","Dnešní energie a pocit","Today's energy and mood"],["support","Dnešní přání podpory","Today's support wish"],["phase","Fáze cyklu · záznam nebo odhad","Cycle phase · recorded or estimated"],["cycle-note","Poznámky k cyklu","Cycle notes"],["pain","Zapsaná bolest","Recorded pain"],["flow","Zapsané krvácení","Recorded bleeding"]].filter(([id])=>canTrack||["wellbeing","support"].includes(id)).map(([id,cs,en])=><label className="consent" key={id}><input type="checkbox" checked={scopes.includes(id)} onChange={e=>{scopesDirty.current=true;setScopes(v=>e.target.checked?[...v,id]:v.filter(x=>x!==id));}}/>{L(cs,en)}</label>)}<p className="hint">{L("Nové volby jsou vypnuté, dokud je nevybereš a neuložíš. Platí i pro prohlížení minulých dnů. Starší soukromé poznámky se nikdy nesdílí.","New choices stay off until you select and save them. They also apply when browsing past days. Earlier private notes are never shared.")}</p>{button(data.link.status==="pending"?L("Potvrdit propojení a volby","Confirm connection and choices"):L("Uložit sdílení","Save sharing"),()=>save("sharing",{scopes,revision:scopeRevision.current}),true)}</>}
        {active&&<p>{L("Druhý z vás sdílí:","Your partner shares:")} {(data.link.receivedScopes||data.link.scopes).length?(data.link.receivedScopes||data.link.scopes).map(s=>({cycle:L("přehled cyklu","cycle overview"),wellbeing:L("dnešní pocity","today's feelings"),support:L("přání podpory","support wishes"),phase:L("fázi cyklu","cycle phase"),"cycle-note":L("poznámky k cyklu","cycle notes"),pain:L("zapsanou bolest","recorded pain"),flow:L("zapsané krvácení","recorded bleeding")}[s])).join(", "):L("zatím jen společné plány","shared plans only")}</p>}
        {data.link&&<div style={{marginTop:22}}>{button(L("Ukončit propojení","Disconnect"),()=>{if(window.confirm(L("Ukončit sdílení? Druhá strana ztratí přístup k přehledu a společným plánům.","Disconnect? The other person will lose access to the overview and shared plans.")))save("disconnect",{revision:data.link.revision});})}</div>}
      </>)}
      <p className="hint">{L("Sdílený přehled se ověřuje při otevření a průběžně online. Při ztrátě spojení se schová. To, co už druhý člověk viděl nebo si uložil, nejde zpětně odvolat.","Shared information is checked on opening and regularly online. It is hidden when the connection fails. Information already seen or copied cannot be recalled.")}</p>
    </>}
    {data&&tab==="sharing"&&<TogetherMaintenance doc={own} canTrack={canTrack} lang={lang} busy={busy} onApply={async doc=>{const result=await save("self",{revision:data.self.revision,doc},"entry");if(result){cycleDirty.current=false;setMode(doc.mode);setLength(doc.usualLength);}return result;}}/>}
    {data&&tab==="pages"&&(active?<PartnerPages data={data} canTrack={role==="client"} lang={lang} save={save} getPages={getPages} busy={busy}/>:<section className="tm-together-section"><p>{L("Pro čtení stránek se nejdřív propojte.","Connect first to read shared pages.")}</p>{button(L("Nastavit propojení","Set up connection"),()=>navigateTo("sharing"))}</section>)}
  </div>;
}

function TogetherRituals({lang,onPlan}) {
  const L=(cs,en)=>lang==="en"?en:cs;
  const [index,setIndex]=useState(0);
  const r=getTogetherRitualText(TOGETHER_RITUALS[index],lang);
  return <div className="tg-ritual-scene">
    <p>{L("Vyberte jednu maličkost, na kterou máte chuť oba.","Choose one small thing you both feel like doing.")}</p>
    <label htmlFor="tg-ritual-choice">{L("Naše společná chvíle","Our moment together")}</label>
    <select id="tg-ritual-choice" value={index} onChange={e=>setIndex(Number(e.target.value))}>{TOGETHER_RITUALS.map((item,i)=><option value={i} key={item.id}>{getTogetherRitualText(item,lang).title}</option>)}</select>
    <div key={r.id} className="tg-ritual-reading"><p className="hint">{r.category} · {r.minutes} {L("min","minutes")}</p><p>{r.intro}</p><p className="tg-personal">{r.question}</p><ol>{r.steps.map((step,i)=><li key={i}>{step}</li>)}</ol></div>
    <div className="row"><button type="button" onClick={()=>setIndex(i=>(i+TOGETHER_RITUALS.length-1)%TOGETHER_RITUALS.length)}>{L("Předchozí chvíle","Previous moment")}</button><button type="button" onClick={()=>setIndex(i=>(i+1)%TOGETHER_RITUALS.length)}>{L("Jiná chvíle","Another moment")}</button></div>
    {onPlan&&r.minutes>=10&&<button type="button" className="primary" style={{marginTop:16}} onClick={()=>onPlan({title:r.title,date:dateKey(),time:"18:00",minutes:r.minutes,note:r.question})}>{L("Navrhnout společnou chvíli","Propose a time together")}</button>}
  </div>;
}
