import {test} from 'node:test';import assert from 'node:assert/strict';
import {safeSourceUrl,metadataPatch,lookupSource,sourceSearchLink} from '../src/shared/product/sourceLookup.js';
import {EDITOR_CHOICES,editorInk} from '../src/shared/ui/editorPalette.js';
test('source links reject active schemes and credentials',()=>{for(const x of ['javascript:alert(1)','data:text/html,x','https://user:pass@example.org'])assert.equal(safeSourceUrl(x),'');assert.equal(safeSourceUrl('https://example.org/video'),'https://example.org/video');assert.match(sourceSearchLink({title:'A & B',type:'Movie'}).url,/A%20%26%20B/)});
test('metadata never overwrites personal score, notes or existing cover',()=>{const p=metadataPatch({author:'Own',score:9,text:'Mine',icon:'own.png'},{author:'External',rating:4,cover:'https://example.org/cover.jpg',year:'2000'});assert.equal(p.author,undefined);assert.equal(p.score,undefined);assert.equal(p.text,undefined);assert.equal(p.icon,undefined);assert.equal(p.year,'2000');assert.equal(p.externalMeta.rating,4)});
test('book lookup labels rating with its real source and scale',async()=>{const r=await lookupSource({type:'Book',title:'Example'},{fetcher:async()=>({ok:true,json:async()=>({docs:[{key:'/works/OL1W',title:'Example',author_name:['A'],cover_i:12,ratings_average:4.234,first_publish_year:2020}]})})});assert.equal(r[0].provider,'Open Library');assert.equal(r[0].scale,5);assert.equal(r[0].rating,4.23);assert.match(r[0].cover,/12-M.jpg$/)});
test('lookup fails quietly offline, on timeout and missing movie key',async()=>{let calls=0;const fetcher=async()=>{calls++;throw Error('network')};assert.deepEqual(await lookupSource({type:'Book',title:'X'},{online:false,fetcher}),[]);assert.deepEqual(await lookupSource({type:'Movie',title:'X'},{fetcher}),[]);assert.equal(calls,0);assert.deepEqual(await lookupSource({type:'Book',title:'X'},{fetcher}),[])});
test('movie ratings stay distinct from own score',async()=>{const [r]=await lookupSource({type:'Movie',title:'X'},{omdbKey:'test',fetcher:async()=>({ok:true,json:async()=>({Response:'True',Title:'X',imdbID:'tt1234567',imdbRating:'7.6',Director:'A',Year:'2020'})})});assert.equal(r.rating,'7.6');assert.equal(r.provider,'IMDb · OMDb');assert.equal(r.scale,10)});
test('four new inks remain distinct and legacy inks still render',()=>{assert.equal(EDITOR_CHOICES.length,4);for(const mode of ['light','dark']){const t={mode,material:'landscape'};assert.equal(new Set(EDITOR_CHOICES.map(x=>editorInk(x,t))).size,4);for(const x of ['sage','sand',...EDITOR_CHOICES])assert.match(editorInk(x,t),/^#[a-f\d]{6}$/i)}});
