export {SKY_HELP} from "./skyHelp.js";
export const SKY_SOURCES=[
  {id:"calculation",title:["Obloha a výpočet","Sky and calculation"],text:["Obloha používá Swiss Ephemeris 2.10.03 a její vestavěný výpočet Moshier přes @swisseph/browser 1.4.0. Polohy jsou geocentrické, zdánlivé a vztažené k vybranému okamžiku. Tropický a siderický rámec mají stejný výpočetní základ; siderický používá skutečnou ájanámšu Lahiri. Rozsah je 1900 až 2100 podle zvoleného místního data. Pravý nebo střední uzel je shodně použitý pro natál i tranzity; Ketu leží o 180° proti Rahu. Výpočty zůstávají v prohlížeči a neposílají údaje narození na cizí server.","The sky uses Swiss Ephemeris 2.10.03 and its built-in Moshier calculation through @swisseph/browser 1.4.0. Positions are geocentric, apparent and relative to the selected instant. Tropical and sidereal frames share one engine; sidereal positions use the actual Lahiri ayanamsa. The supported range is 1900 to 2100 by selected local date. The chosen true or mean node applies to both natal and current positions; Ketu is opposite Rahu by 180 degrees. Calculations stay in the browser and do not send birth details to an external server."],links:[["Swiss Ephemeris: programming", "https://www.astro.com/swisseph/swephprg.htm"],["Swiss Ephemeris: Moshier", "https://www.astro.com/swisseph/swisseph.htm"],["@swisseph/browser", "https://github.com/swisseph-js/swisseph/tree/main/packages/browser"]]},
  {id:"ephemeris-license",title:["Efemerida a licence","Ephemeris and licence"],text:["Swiss Ephemeris: Copyright © 1997–2021 Astrodienst AG, Switzerland. Výpočetní knihovna i použitá webová vazba jsou dostupné za podmínek AGPL-3.0. Swiss Ephemeris nabízí také profesionální licenci; ta není automaticky licencí jiné webové vazby. Původní podmínky a zdrojový kód knihoven jsou dostupné v odkazech níže.","Swiss Ephemeris: Copyright © 1997–2021 Astrodienst AG, Switzerland. The calculation library and the web binding used here are available under AGPL-3.0. Swiss Ephemeris also offers a professional licence; that does not automatically license a separate web binding. The original conditions and library source code are linked below."],links:[["Swiss Ephemeris: original licence", "https://github.com/aloistr/swisseph/blob/master/LICENSE"],["Web binding: AGPL-3.0", "https://github.com/swisseph-js/swisseph/blob/main/LICENSE"],["Swiss Ephemeris: source", "https://github.com/aloistr/swisseph"],["Web binding: source", "https://github.com/swisseph-js/swisseph"]]},
  {id:"horizon",title:["Východ a planetární hodiny","Sunrise and planetary hours"],text:["Běžný východ a západ používá horní okraj slunečního kotouče, standardní refrakci 34 úhlových minut a ideální obzor bez terénních překážek. Pančánga při východu používá samostatně geocentrický střed Slunce bez refrakce. Tyto okamžiky se mohou o několik minut lišit. Planetární hodiny dělí den a noc na dvanáct úseků v pořadí Saturn, Jupiter, Mars, Slunce, Venuše, Merkur a Luna. První hodinu po běžném východu řídí planeta dne; před ním pokračuje předchozí noc. Polární podmínky se nezastupují vymyšleným časem.","Ordinary sunrise and sunset use the Sun's upper limb, standard refraction of 34 arcminutes and an ideal horizon without terrain obstructions. Sunrise panchanga separately uses the geocentric solar centre without refraction. Those instants can differ by several minutes. Planetary hours divide daylight and night into twelve intervals in the order Saturn, Jupiter, Mars, Sun, Venus, Mercury and Moon. The day ruler starts the first hour after ordinary sunrise; before it the previous night continues. Polar conditions are not replaced with invented times."],links:[["US Naval Observatory", "https://aa.usno.navy.mil/faq/RST_defs"],["Swiss Ephemeris: Hindu rising", "https://www.astro.com/swisseph/swephprg.htm"],["Agrippa, book II, chapter 34", "https://www.alchemy-texts.com/book/three-books-of-occult-philosophy/"]]},
  {id:"panchanga",title:["Pět částí dne","The five parts of the day"],text:["Tithi dělí úhel Luna minus Slunce na třicet úseků po 12°. Karana je jeho polovina po 6° a používá sedm opakovaných a čtyři pevné názvy. Nakšatra dělí siderickou dráhu Luny na 27 úseků, každý se čtyřmi pádami. Jóga dělí součet siderických délek Slunce a Luny na 27 úseků. Vára je planeta dne počítaného od hinduistického východu Slunce. Konec úseku se hledá na skutečných vypočtených polohách, nikoli lineárním odhadem; údaj při východu a údaj v právě zvoleném čase jsou oddělené.","Tithi divides the Moon-minus-Sun angle into thirty sectors of 12 degrees. Karana halves it into 6-degree sectors, with seven recurring and four fixed names. Nakshatra divides the Moon's sidereal path into twenty-seven sectors, each with four padas. Yoga divides the sum of sidereal Sun and Moon longitudes into twenty-seven sectors. Vara is the ruler of the day beginning at Hindu sunrise. Sector endings are found from calculated positions rather than linear extrapolation; the sunrise value and selected-instant value are distinct."],links:[["Swiss Ephemeris: coordinates and sunrise", "https://www.astro.com/swisseph/swephprg.htm"],["Surya Siddhanta, chapter XIV", "https://www.swaveda.com/texts/surya-siddhanta/14/"]]},
  {id:"kalachakra",title:["Kálačakra a tělesná mapa","Kalachakra and the body map"],text:["Vnější, vnitřní a jiná rovina inspirovaly pořadí Nebe, Tělo a Praxe. Vazby Rahu, Saturnu, Ketu, světel a snových prostředí vycházejí z podání Kršnavadžrova učení, které dodal Tanmay. Silueta, větry a 21 600 dechů jsou tradiční modely, ne fyziologická měření. Přiřazení znamení vnitřním úsekům, celá mapa deseti větrů a denní la-bod zatím nemají ověřené pravidlo v aplikaci.","Outer, inner and alternative Kalachakra inspired Sky, Body and Practice. Rahu, Saturn, Ketu, the luminaries and dream settings follow Tanmay's account of Krshnavajra's teaching. Channels, winds and 21,600 breaths are traditional models, not physiological measurements. Internal sign assignments, the full ten-wind map and daily la location have no verified rule in this app yet."],links:[["Dalai Lama: Kalachakra", "https://www.dalailama.com/teachings/kalachakra-initiations"],["Tsenshap Serkong Rinpoche", "https://studybuddhism.com/en/advanced-studies/prayers-rituals/tantric-practices/explanation-of-the-kalachakra-practices-tsenshap-serkong-rinpoche/kalachakra-sadhana-the-actual-practice-of-the-two-stages"],["Internal Kalachakra", "https://studybuddhism.com/en/advanced-studies/vajrayana/kalachakra-advanced/internal-kalachakra"]]},
  {id:"calendar",title:["Lunární dny praxe","Lunar practice days"],text:["Číslo tithi je přesný úhlový krok Luny vůči Slunci. V první verzi slouží jako orientační podklad dnů praxe. Tibetský kalendář má vynechané a zdvojené dny a odlišné školy, proto jej prosté tithi nenahrazuje. Dny a noci praxe lze vybrat podle vlastní linie; význam zatmění je náboženský výklad.","Tithi is an exact angular step of the Moon relative to the Sun. It supplies an approximate practice calendar here. Tibetan calendars have omitted and repeated days and different schools, so tithi does not replace them. Choose practice days and nights for your lineage; the spiritual significance of eclipses is a religious reading."],links:[["FPMT: Dharma dates", "https://fpmt.org/media/resources/dharma-dates/dates-explained/"],["Tibetan calendar", "https://studybuddhism.com/en/advanced-studies/history-culture/tibetan-astrology/details-of-tibetan-astrology-8-the-tibetan-calendar"],["Hevajra tsok", "https://www.drikungtranslation.com/drikungtranslation/wp-content/uploads/2022/12/2022_11_25-a4-en-Hevajra-Tsok.pdf"]]},
  {id:"swara",title:["Švarodaja a vlastní pozorování","Swara and observation"],text:["Levá, pravá a oboustranná průchodnost mají tradiční lunární, solární a centrální výklad. Volitelná třídenní tabulka očekávání je model převzatý ze zadání; přesné vydání jejího pravidla zůstává k ověření. Shoda s tabulkou ani pocit obou otevřených dírek nejsou měřením kanálů. Kostka používá uživatelovo aktuální potvrzení obou dírek a příjemného pocitu, s ohlédnutím za 21 dní.","Left, right and balanced nostril flow have traditional lunar, solar and central readings. The optional three-day expectation table is a model supplied in the brief whose exact textual rule remains to be verified. Agreement with it is not a measurement of channels. The decision ritual uses a fresh balanced and comfortable self-report, followed by a review after twenty-one days."],links:[["Bihar School of Yoga, December 2024", "https://www.biharyoga.net/pdfs/english/2024/december-2024-yoga.pdf"]]},
  {id:"personal",title:["Osobní období a tradiční klíče","Personal periods and traditional keys"],text:["Sekta vychází ze skutečné výšky Slunce při narození; do 0,1° od obzoru ji označujeme jako nejistou. Profekce postupuje po tropických znameních od ascendentu o dokončený rok a mění se v místní den narozenin. Denní Los Štěstí je ASC + Luna − Slunce, noční opačně; Los Ducha používá obrácený vzorec. Vimšóttarí začíná siderickou nakšatrou Luny, používá úhlový zbytek prvního období a rok o 365,2425 dne. Neznámý čas se nenahrazuje polednem. Nejednoznačný čas při změně letního času, neexistující čas nebo neurčitý ascendent na přesném zeměpisném pólu osobní výpočet nezpřístupní.","Sect uses the Sun's actual birth altitude; within 0.1 degree of the horizon it is marked uncertain. Profections move through tropical signs from the ascendant by completed age, changing on the local civil birthday. Daytime Fortune is ASC + Moon − Sun, reversed at night; Spirit uses the opposite formula. Vimshottari starts from the sidereal lunar mansion and uses the angular remainder of the first period and a 365.2425-day year. Unknown time is not replaced with noon. An ambiguous daylight-saving clock time, nonexistent time or undefined ascendant at an exact geographic pole does not enable the personal calculation."],links:[["Chris Brennan: sect", "https://theastrologypodcast.com/transcripts/ep-274-transcript-sect-in-astrology-day-and-night-charts/"],["Annual profections", "https://theastrologypodcast.com/transcripts/ep-153-annual-profections-an-ancient-time-lord-technique/"],["Brihat Parashara Hora Shastra, chapter 46", "https://vedic-astro.s3.amazonaws.com/books/bhrihat_parasara_hora_shastra.pdf"]]},
  {id:"editorial",title:["Výklad a učitelovy věty","Interpretation and teaching sentences"],text:["Výklady planet, aspektů a znamení jsou současná autorská kontemplace. Neurčují identitu ani osud. Osm anglických vět a konkrétní podání učitelových pravidel poskytl Tanmay; věty zůstávají v dodaném znění. Zápisy dechu, snu, rozhodnutí a praxe zůstávají v tomto prohlížeči odděleně pro každý přihlášený účet.","Planet, aspect and sign readings are contemporary authored contemplations, not identities or destinies. Tanmay supplied the eight English sentences and the account of his teacher's practice rules; the wording is preserved. Breath, dream, decision and practice records stay in this browser, separately for each authenticated account."],links:[]},
];
export const SKY_ELEMENTS=[
  {id:"earth",name:["Země","Earth"],text:["Tvar, který unese život. Opři chodidla o zem a dovol dnešku získat jednoduchý řád.","Form that can hold life. Feel your feet on the ground and give the day a simple shape."]},
  {id:"water",name:["Voda","Water"],text:["Spojení a přizpůsobení. Všimni si, kde může pevný záměr dostat měkčí podobu.","Connection and adaptation. Notice where a firm intention could take a softer form."]},
  {id:"fire",name:["Oheň","Fire"],text:["Proměna a jas. Věnuj pozornost jedné věci, kterou dnes chceš skutečně dokončit.","Transformation and clarity. Give attention to one thing you want to complete today."]},
  {id:"wind",name:["Vítr","Wind"],text:["Pohyb, který nelze zadržet. Nech přirozený dech přijít a odejít a pozoruj jeho proměnu.","Movement that cannot be held. Let the natural breath arrive and leave and observe its change."]},
  {id:"space",name:["Prostor","Space"],text:["Místo pro všechny tvary. Udělej chvíli prostoru mezi podnětem a odpovědí.","Room for every form. Leave a little space between a stimulus and your response."]},
  {id:"wisdom",name:["Moudrost","Wisdom"],text:["Jasnost, která nemusí nic přidávat. Všimni si právě této zkušenosti, ještě před jejím pojmenováním.","Clarity that needs to add nothing. Notice this experience before giving it a name."]},
];
export const SKY_BODY_POINTS=[
  {id:"Rahu",help:"T02",name:["Rahu · touha","Rahu · desire"],x:150,y:156,text:["Touha ukáže směr, kterým odchází tvoje pozornost. V učitelově mapě ji nemusíš vyhnat: přiveď ji do středu a pohlédni, co v ní skutečně hledáš.","Desire shows where attention is moving. In your teacher's map you can bring it into the centre and look at what it truly seeks."]},
  {id:"Saturn",help:"T03",name:["Saturn · karmický vítr","Saturn · karmic wind"],x:150,y:231,text:["To, co se vrací jako překážka, může vstoupit na stezku. Dnes si vyber jednu opakovanou reakci a chvíli pozoruj tento okamžik, než ji znovu vykonáš.","What returns as an obstacle can enter the path. Choose one recurring reaction and stay present before repeating it."]},
  {id:"Ketu",help:"T04",name:["Ketu · oheň","Ketu · fire"],x:150,y:303,text:["Oheň v této mapě proměňuje to, čeho se vítr držel. Pojmenuj jeden příběh, který dnes nemusíš dál dokazovat, a nech jeho sevření povolit.","Fire in this map transforms what the wind held onto. Name one story you do not need to prove today and let its grip soften."]},
  {id:"lights",help:"T05",name:["Slunce a Luna · rovnováha","Sun and Moon · balance"],x:196,y:197,text:["Solární a lunární proud se navzájem potřebují. Dej dnes činnosti jasný směr a odpočinku skutečné místo; pak si všimni, jak se v těle setkávají.","Solar and lunar currents need one another. Give action a direction and rest a real place, then notice how they meet in experience."]},
];
export const SKY_PRACTICES={
  guru:{name:["Guru jóga","Guru yoga"],text:["Vrať pozornost ke své vlastní předané formě guru jógy.","Return attention to your own received form of guru yoga."]},
  dzambhala:{name:["Dzambhala","Dzambhala"],text:["Připomeň si hojnost jako prostor pro štědrost a svou vlastní praxi Dzambhaly.","Recall abundance as room for generosity and your own Dzambhala practice."]},
  protector:{name:["Ochránce","Protector practice"],text:["Uzavři den svou vlastní formou praxe ochránce.","Close the day with your own form of protector practice."]},
  sadhana:{name:["Celá sádhana","Full sadhana"],text:["Vyhraď si nerušený čas pro celou svou sádhanu.","Set aside uninterrupted time for your full sadhana."]},
  tara:{name:["Tára a Medicínský Buddha","Tara and Medicine Buddha"],text:["Osmý lunární den připomíná tyto formy praxe, pokud patří k tvé linii.","The eighth lunar day recalls these forms when they belong to your lineage."]},
  guruDay:{name:["Den Guru Rinpočheho","Guru Rinpoche day"],text:["Desátý lunární den můžeš věnovat své praxi Guru Rinpočheho.","You can dedicate the tenth lunar day to your Guru Rinpoche practice."]},
  dakini:{name:["Den dákiní","Dakini day"],text:["Věnuj pozornost své vlastní praxi dákiní nebo společnému tsoku podle své linie.","Make room for your own dakini practice or a tsok in your lineage."]},
  hevajra:{name:["Noc jóginí","Night of the yoginis"],text:["Ubývající Luna otevírá noc, kterou zadání spojuje s Hévadžrovou praxí.","The waning Moon marks a night associated with Hevajra practice in your teaching."]},
  moon:{name:["Chvíle pod Lunou","A moment with the Moon"],text:["Na chvíli vyjdi ven a věnuj pozornost skutečné obloze.","Step outside for a while and attend to the actual sky."]},
  mercury:{name:["Vrátit se a dokončit","Return and complete"],text:["Merkur se vrací. Podle zvoleného učitelova pravidla dej dnes přednost revizi a dokončení před vydáním nové práce.","Mercury is retrograde. Under your chosen teaching rule, give revision and completion priority over publishing new work today."]},
  eclipse:{name:["Prostor pro praxi","Room for practice"],text:["Dnešní zatmění je ve zvoleném tradičním čtení příležitostí věnovat více prostoru praxi.","Today's eclipse is an invitation to give practice more room in the traditional reading you selected."]},
  vajrayogini:{name:["Vadžrajóginí","Vajrayogini"],text:["Vlastní zapsaná menstruace připomíná tuto formu podle zvoleného učitelova podání.","Your recorded menstruation recalls this form under your chosen teaching rule."]},
};
export function skyPracticeInvitations({tithi,dayPlanet,retrogradeMercury=false,eclipse=false,menstruation=false,settings}){
  const result=[],add=(key,reason)=>{if(settings.practices[key]===false)return;if(!result.some(p=>p.key===key))result.push({key,reason,...SKY_PRACTICES[key]});};
  if(settings.practices.eclipses&&eclipse)add("eclipse",["Zatmění dnes","Eclipse today"]);
  if(settings.practiceDays.includes(tithi)){
    const reason=[`${tithi}. tithi · orientační den praxe`,`${tithi}th tithi · approximate practice day`];
    if(tithi===8)add("tara",reason);if(tithi===10)add("guruDay",reason);if([15,30].includes(tithi))add("moon",reason);
    if(tithi===25)add("dakini",reason);if(tithi===29)add("protector",reason);if([23,29].includes(tithi))add("hevajra",reason);
  }
  if(dayPlanet==="Venus")add("dakini",["Pátek · Venuše","Friday · Venus"]);
  if(settings.practices.mercury&&retrogradeMercury)add("mercury",["Merkur retrográdní","Mercury retrograde"]);
  if(settings.practices.vajrayogini&&menstruation)add("vajrayogini",["Tvůj záznam cyklu","Your cycle record"]);
  if(!result.length)add(["guru","dzambhala","protector"].find(key=>settings.practices[key])||"moon",["Vlastní rytmus dne","Your daily rhythm"]);
  return result;
}
