// Generated by Shared/scripts/export-source-covers.mjs. No user records or external requests.
export const SOURCE_COVER_ART = Object.freeze({
  "Philosophy": "/media/source-covers/philosophy-v2.webp",
  "Psychology": "/media/source-covers/psychology-v2.webp",
  "Spirituality": "/media/source-covers/spirituality-v2.webp",
  "Novel": "/media/source-covers/novel-v2.webp",
  "Movement": "/media/source-covers/movement-v2.webp",
  "Science": "/media/source-covers/science-v2.webp",
  "Self-help": "/media/source-covers/self-help-v2.webp",
  "Biography": "/media/source-covers/biography-v2.webp",
  "Business": "/media/source-covers/business-v2.webp",
  "Poetry": "/media/source-covers/poetry-v2.webp",
  "Documentary": "/media/source-covers/documentary-v2.webp",
  "Drama": "/media/source-covers/drama-v2.webp",
  "Sci-fi": "/media/source-covers/sci-fi-v2.webp",
  "Thriller": "/media/source-covers/thriller-v2.webp",
  "Comedy": "/media/source-covers/comedy-v2.webp",
  "Animation": "/media/source-covers/animation-v2.webp",
  "Interview": "/media/source-covers/interview-v2.webp",
  "Education": "/media/source-covers/education-v2.webp",
  "Storytelling": "/media/source-covers/storytelling-v2.webp"
});
export const SOURCE_COVER_HASHES = Object.freeze({
  "philosophy-v2.webp": "58d028548bc0ab45547ccdbfa46407354bf6296181f22cbef6c53997a92841fe",
  "psychology-v2.webp": "b9547ab126c047df640764a414efa434be6c8501699f0c6486cda52a4f3280bd",
  "spirituality-v2.webp": "54e3ead4e010edeed9a9f302928ba2ad9b435ea9709a5b0f7fd25d1e224d7b5e",
  "novel-v2.webp": "fdbf3171f95623d85aad2c2f72118d7ddfcf894237b65c0fa8af2c939ff07cba",
  "movement-v2.webp": "6f01d533633be79b31e953546730db92b13f85ccf505dbba6a44639fe8e3a0b0",
  "science-v2.webp": "2afd9a3075321295471e49197b07329587a29e2678aeacba862f489d2bdee245",
  "self-help-v2.webp": "25e277f1333717d510494a918da0caad5a5d7dd8e942d2c80df8ba9165b40581",
  "biography-v2.webp": "7218628a1ff619626b90e391982953168e15f787fa330b539baf840b92726e7f",
  "business-v2.webp": "a35862551a9a7caaf0ec2317d45f61a7c933f72aab2dfc53c90b6efff35c8a78",
  "poetry-v2.webp": "c5ff642a9de86b0764deefee7965e0ea54763762b684538cf5b074116d651d04",
  "documentary-v2.webp": "d970d24fb596cb4348628f2748d730c6008d396cb84dd1f614361b41960b1b75",
  "drama-v2.webp": "e2d99be158f5985b68611a9dfa083e7e11153ecfdcb13cc990ab336ab7c66048",
  "sci-fi-v2.webp": "5038537f872eb5d2ea26fa3bb54f3b4a7890693b8a983024271e00af2005fb8a",
  "thriller-v2.webp": "9d70c311b4c61a8a2d6354f9a638ef901315043d360f2bda34e01e16d123d3f4",
  "comedy-v2.webp": "1cd8e1809385b904b2243a7e1b833ded4259680074e902b0eb15956654b86a80",
  "animation-v2.webp": "01c2799e34ea0c6812dccc9483161814c4b0e8b5e8871a73fe9e123442b71184",
  "interview-v2.webp": "f4658f1a6ec83484fdb2f7a59f47d4e6dbd1ab7dc9daf1fdf9c85384c336a01d",
  "education-v2.webp": "bac94a01836d10b6764520ab25b7e0fc59236329c22e35ad3b342a34f62e05c4",
  "storytelling-v2.webp": "d9b375d8a4a9746535cc6f19f262231ad74d00ec57d42c9ac46b98adeeb8955e"
});

/** Use only the saved category. Unknown categories keep their media glyph. */
export function sourceCoverArt(category) {
  return typeof category === "string" && Object.hasOwn(SOURCE_COVER_ART, category) ? SOURCE_COVER_ART[category] : null;
}
