import {MoonPhase,Illumination,Body,EclipticGeoMoon,SearchMoonPhase} from "astronomy-engine";
export const MOON_NAMES=[["Nov","New moon"],["Dorůstající srpek","Waxing crescent"],["První čtvrť","First quarter"],["Dorůstající Měsíc","Waxing gibbous"],["Úplněk","Full moon"],["Ubývající Měsíc","Waning gibbous"],["Poslední čtvrť","Last quarter"],["Ubývající srpek","Waning crescent"]];
export const ZODIAC=[["Beran","Aries"],["Býk","Taurus"],["Blíženci","Gemini"],["Rak","Cancer"],["Lev","Leo"],["Panna","Virgo"],["Váhy","Libra"],["Štír","Scorpio"],["Střelec","Sagittarius"],["Kozoroh","Capricorn"],["Vodnář","Aquarius"],["Ryby","Pisces"]];
export function moonToday(date=new Date()) {
  const angle=MoonPhase(date),phase=angle/360,index=Math.round(phase*8)%8;
  const nextAngle=(Math.floor(angle/90)+1)*90%360;
  return {phase,index,light:Math.round(Illumination(Body.Moon,date).phase_fraction*100),sign:Math.floor(EclipticGeoMoon(date).lon/30)%12,quarter:Math.floor(angle/90),nextIndex:nextAngle/45,next:SearchMoonPhase(nextAngle,date,10)?.date.toISOString()||null};
}
// A named historical tradition, not a causal health claim or a Vedic horoscope.
export const LUNAR_REFLECTIONS=[
  {quality:["Vláha · od novu k první čtvrti","Moisture · new moon to first quarter"],text:["Ptolemaios v Tetrabiblos I.8 přiřazuje této části růstu Měsíce vláhu. V jeho dobové astrologii jde o kvalitativní jazyk přírody, nikoli o naměřený účinek na člověka.","In Tetrabiblos I.8, Ptolemy associates this part of the waxing Moon with moisture. This is the qualitative language of historical astrology, not a measured effect on people."],prompt:["Čemu chceš dát prostor vyrůst? Vyber jeden malý záměr pro další dny.","What would you like to give room to grow? Choose one small intention for the coming days."]},
  {quality:["Teplo · od první čtvrti k úplňku","Warmth · first quarter to full moon"],text:["V Ptolemaiově astrologické tradici je tato část dorůstání spojována s teplem. Může posloužit jako symbol pro péči o to, co už začalo, ne jako předpověď tvé energie.","Ptolemy's astrological tradition associates this waxing interval with warmth. It can serve as a symbol for tending what has begun, not a prediction of your energy."],prompt:["Který rozdělaný záměr si zaslouží jeden konkrétní krok? Domluvte se na něm spolu.","Which intention deserves one concrete step? Agree on it together."]},
  {quality:["Sucho · od úplňku k poslední čtvrti","Dryness · full moon to last quarter"],text:["Od úplňku k poslední čtvrti uvádí Tetrabiblos symbolickou kvalitu sucha. Pro osobní reflexi ji zde čteme jako příležitost rozlišit, co si ponechat. Tento výklad je naše současná inspirace.","Tetrabiblos assigns the symbolic quality of dryness to this interval. We use it as a prompt to consider what to retain. That reflective reading is our contemporary interpretation."],prompt:["Co se v posledních dnech podařilo a co už nepotřebujete nést dál? Poděkujte si za jednu věc.","What went well recently, and what no longer needs carrying? Thank each other for one thing."]},
  {quality:["Chlad · od poslední čtvrti k novu","Coolness · last quarter to new moon"],text:["Poslední část ubývání Ptolemaios spojuje s chladem. Jako symbolický námět může připomenout ztišení a dokončování. Neznamená to, že dnes musíš odpočívat nebo odkládat rozhodnutí.","Ptolemy associates the final waning interval with coolness. As a symbolic prompt it can suggest quiet and completion; it does not mean you must rest or postpone decisions."],prompt:["Co může dnes zůstat jednoduché? Dopřejte si pět minut společného ticha.","What can stay simple today? Take five quiet minutes together."]}
];
export const LUNAR_SOURCES={ptolemy:"https://penelope.uchicago.edu/thayer/e/roman/texts/ptolemy/tetrabiblos/1b%2A.html#8",uposatha:"https://www.accesstoinsight.org/ptf/dhamma/sila/uposatha.html",nasa:"https://science.nasa.gov/moon/moon-phases/",calculation:"https://github.com/cosinekitty/astronomy"};
