// Original meal ideas. Sources support nutrition context, not tested phase-specific recipes.
// The phase is a browsing cue; individual hunger, preferences and tolerance take priority.
const pair = (cs, en) => [cs, en];

export const CYCLE_FOOD_SOURCES = [
  {id:'food-iron',title:'NIH ODS · Iron',url:'https://ods.od.nih.gov/factsheets/Iron-HealthProfessional/',note:pair('Krvácení zvyšuje ztráty železa. Luštěniny a tofu přispívají k jeho příjmu. Jedno jídlo neřeší nedostatek železa.','Bleeding increases iron losses. Pulses and tofu contribute dietary iron. A single meal does not treat iron deficiency.')},
  {id:'food-vitamin-c',title:'NIH ODS · Vitamin C',url:'https://ods.od.nih.gov/factsheets/VitaminC-HealthProfessional/',note:pair('Vitamin C pomáhá vstřebávání rostlinného železa. Čerstvá paprika, citrusy a brokolice jsou jednou z možností, jak jej přidat k jídlu.','Vitamin C helps the absorption of plant iron. Fresh peppers, citrus fruit and broccoli are ways to include it with a meal.')},
  {id:'food-plate',title:'Harvard The Nutrition Source · Healthy Eating Plate',url:'https://nutritionsource.hsph.harvard.edu/healthy-eating-plate/',note:pair('Opora pro pestrou skladbu jídla ze zeleniny, obilovin a zdroje bílkovin. Nejde o jídelníček podle hormonální fáze.','A basis for varied meals combining vegetables, grains and a protein source. It is not a diet matched to hormonal phases.')},
  {id:'food-protein',title:'Harvard The Nutrition Source · Protein',url:'https://nutritionsource.hsph.harvard.edu/what-should-you-eat/protein/',note:pair('Luštěniny, tofu, tempeh, ořechy a semena pomáhají střídat rostlinné zdroje bílkovin.','Pulses, tofu, tempeh, nuts and seeds provide a variety of plant protein sources.')},
  {id:'food-vegan',title:'NHS · The vegan diet',url:'https://www.nhs.uk/live-well/eat-well/how-to-eat-a-balanced-diet/the-vegan-diet/',note:pair('Celková skladba veganské stravy včetně obohacených potravin. Výživové potřeby se neomezují na konkrétní den cyklu.','Overall vegan nutrition, including fortified foods. Nutritional needs are not confined to a particular cycle day.')},
  {id:'food-calcium',title:'NIH ODS · Calcium',url:'https://ods.od.nih.gov/factsheets/Calcium-HealthProfessional/',note:pair('Vápník může doplnit obohacený sójový nápoj nebo tofu srážené vápenatou solí. Obsah se liší podle výrobku.','Fortified soy drinks or tofu set with calcium salts can contribute calcium. The amount varies by product.')},
  {id:'food-pms',title:'ACOG · Premenstrual Syndrome',url:'https://www.acog.org/womens-health/faqs/premenstrual-syndrome',note:pair('Odborná doporučení pro předmenstruační obtíže zahrnují celozrnné potraviny a zdroje vápníku. Neprokazují léčebný účinek našich receptů.','Professional guidance for premenstrual symptoms includes whole grains and calcium sources. It does not establish a treatment effect for our recipes.')},
  {id:'food-biocy',title:'Gorczyca et al. · BioCycle dietary study (2016)',url:'https://pubmed.ncbi.nlm.nih.gov/26043860/',note:pair('Pozorování 259 žen našlo větší hlášený hlad a chutě v pozdní luteální fázi. Nešlo o zkoušku jídelníčku.','Observations in 259 women found higher reported appetite and cravings in the late luteal phase. This was not a diet trial.')},
  {id:'food-appetite-study',title:'Smith et al. · Appetite across cycle phases (2026)',url:'https://pubmed.ncbi.nlm.nih.gov/41005066/',note:pair('Studie 18 účastnic nenašla významný rozdíl v hladu ani příjmu energie mezi dvěma sledovanými fázemi. Průběh nelze předpokládat u každého.','A study of 18 participants found no significant difference in appetite or energy intake between the two phases studied. A pattern cannot be assumed for everyone.')},
  {id:'food-intake-review',title:'Tucker et al. · Menstrual cycle and energy intake (2024/2025)',url:'https://pmc.ncbi.nlm.nih.gov/articles/PMC11819481/',note:pair('Metaanalýza našla v průměru vyšší příjem energie v luteální fázi. Výsledky studií se výrazně lišily; nejde o předepsanou porci navíc.','A meta-analysis found higher average energy intake in the luteal phase. Study results varied considerably; this is not a prescribed extra portion.')},
];

export const CYCLE_FOOD = {
  menstrual: [
    {
      id:'food-menstrual-red-lentil-soup',
      title:pair('Červená čočka s mrkví a paprikou','Red lentil, carrot and pepper soup'),
      text:pair('Červenou čočku uvař s mrkví, rajčaty a trochou římského kmínu. Část rozmixuj, přidej citron a podávej s chlebem a čerstvou červenou paprikou.','Simmer red lentils with carrots, tomatoes and a little cumin. Blend part of the soup, add lemon and serve with bread and fresh red pepper.'),
      why:pair('Během krvácení můžeš dát prostor železu z čočky. Paprika přidá vitamin C a příprava vystačí s jedním hrncem.','During bleeding, lentils offer a way to include iron. Pepper adds vitamin C, and you only need one pot.'),
      partnerWhy:pair("V době krvácení můžeš nabídnout polévku s železem z čočky a vitaminem C z papriky.","During bleeding, offer soup with iron from lentils and vitamin C from peppers."),
      sourceIds:['food-iron','food-vitamin-c'],
    },
    {
      id:'food-menstrual-white-bean-toast',
      title:pair('Fazolová pomazánka s citronem','Lemony white bean toast'),
      text:pair('Uvařené nebo konzervované bílé fazole propláchni a rozmačkej s olivovým olejem a citronem. Namaž na celozrnný chléb. Přidej nakrájenou papriku a pažitku.','Rinse cooked or canned white beans and mash them with olive oil and lemon. Spread over wholegrain bread and add sliced pepper and chives.'),
      why:pair('Když při menstruaci nechceš vařit, fazole přinesou železo i bílkoviny v několika minutách.','When cooking feels too much during your period, beans bring iron and protein to a meal that takes minutes.'),
      partnerWhy:pair("Když při menstruaci nezbývá chuť vařit, nachystej fazolový chléb; železo i bílkoviny tak budou součástí rychlého jídla.","When cooking feels too much during a period, prepare bean toast for a quick meal that includes iron and protein."),
      sourceIds:['food-iron','food-protein'],
    },
    {
      id:'food-menstrual-tofu-scramble',
      title:pair('Míchané tofu s rajčaty','Tofu scramble with tomatoes'),
      text:pair('Na pánvi prohřej rozdrobené tofu s rajčaty a hrstí špenátu. Dochuť uzenou paprikou. Přidej toast a k jídlu pomeranč.','Warm crumbled tofu in a pan with tomatoes and a handful of spinach. Season with smoked paprika. Serve with toast and an orange.'),
      why:pair('Tofu doplní železo do snídaně v době krvácení. Pomeranč přidá vitamin C, který pomáhá jeho vstřebávání.','Tofu adds iron to breakfast during bleeding. The orange provides vitamin C to help its absorption.'),
      partnerWhy:pair("Snídaně s tofu a pomerančem nabídne v době krvácení rostlinné železo spolu s vitaminem C.","A breakfast of tofu and orange offers plant iron alongside vitamin C during bleeding."),
      sourceIds:['food-iron','food-vitamin-c'],
    },
    {
      id:'food-menstrual-chickpea-stew',
      title:pair('Cizrna s rajčaty a rýží','Chickpea and tomato stew with rice'),
      text:pair('Na cibuli krátce prohřej mletou papriku. Přidej rajčata, uvařenou cizrnu a trochu vody. Povař a podávej s rýží a čerstvou paprikou.','Briefly warm ground paprika with sautéed onion. Add tomatoes, cooked chickpeas and a little water. Simmer and serve with rice and fresh pepper.'),
      why:pair('Při krvácení se hodí myslet na pravidelné jídlo i železo. Cizrna s rýží dá obojímu místo na talíři.','During bleeding, regular meals and dietary iron deserve attention. Chickpeas and rice make room for both.'),
      partnerWhy:pair("Při menstruaci můžeš převzít přípravu oběda a nabídnout cizrnu s rýží jako běžné jídlo se zdrojem železa.","During a period, take care of lunch and offer chickpeas with rice as an ordinary meal that includes iron."),
      sourceIds:['food-iron','food-plate'],
    },
    {
      id:'food-menstrual-beluga-buckwheat',
      title:pair('Pohanka s čočkou a pečenou řepou','Buckwheat with lentils and roasted beetroot'),
      text:pair('Smíchej uvařenou pohanku a černou čočku s pečenou řepou. Přidej dílky pomeranče, petržel a dýňová semínka. Dochuť olejem a citronem.','Combine cooked buckwheat and black lentils with roasted beetroot. Add orange segments, parsley and pumpkin seeds. Dress with oil and lemon.'),
      why:pair('Pro dny menstruace tu železo přináší hlavně čočka. Misku můžeš nachystat předem, pokud potřebuješ víc odpočinku.','Lentils are the main iron contribution here for period days. Prepare the bowl ahead if you need more rest.'),
      partnerWhy:pair("Pokud je při menstruaci potřeba víc odpočinku, připrav misku předem; čočka do ní přidá železo.","If more rest is needed during a period, prepare the bowl ahead; lentils contribute iron."),
      sourceIds:['food-iron','food-vitamin-c'],
    },
    {
      id:'food-menstrual-bean-potato',
      title:pair('Pečený brambor s fazolemi','Baked potato with kidney beans'),
      text:pair('Upeč větší brambor ve slupce. Rozkroj ho a naplň uvařenými červenými fazolemi s rajčatovou omáčkou. Vedle dej salát z čerstvé papriky a zelí.','Bake a large potato in its skin. Split it and fill with cooked kidney beans in tomato sauce. Add a fresh pepper and cabbage salad.'),
      why:pair('Když během krvácení přijde větší hlad, brambor přidá přílohu a fazole rostlinné železo.','If you feel hungrier during bleeding, the potato provides a starchy base and the beans contribute plant iron.'),
      partnerWhy:pair("Při větším hladu v době krvácení nabídni brambor s fazolemi a nech velikost porce na druhém člověku.","For stronger hunger during bleeding, offer a potato with beans and let the other person choose the portion."),
      sourceIds:['food-iron','food-vegan'],
    },
    {
      id:'food-menstrual-lentil-pasta',
      title:pair('Těstoviny s čočkovou omáčkou','Pasta with lentil sauce'),
      text:pair('Podus cibuli, mrkev a rajčata s uvařenou hnědou čočkou. Smíchej s celozrnnými těstovinami. K jídlu přidej křupavou papriku nebo brokolici krátce vařenou v páře.','Simmer onion, carrot and tomatoes with cooked brown lentils. Toss with wholegrain pasta. Add crunchy pepper or briefly steamed broccoli on the side.'),
      why:pair('Čočka přidá železo a omáčku můžeš uvařit do zásoby pro dny menstruace, kdy chceš méně stát u plotny.','Lentils add iron, and the sauce can be made ahead for period days when you want less time at the stove.'),
      partnerWhy:pair("Omáčku s čočkou můžeš uvařit dopředu, aby v době menstruace čekalo hotové jídlo se zdrojem železa.","Make lentil sauce ahead so a meal that includes iron is ready during a period."),
      sourceIds:['food-iron','food-vitamin-c'],
    },
    {
      id:'food-menstrual-chickpea-tray',
      title:pair('Cizrna a dýně z jednoho plechu','Chickpeas and pumpkin on one tray'),
      text:pair('Upeč kostky dýně, uvařenou cizrnu a brokolici s trochou oleje. Podávej s kuskusem. Přelij tahini rozmíchaným s citronem a vodou.','Roast pumpkin cubes, cooked chickpeas and broccoli with a little oil. Serve with couscous and tahini thinned with lemon and water.'),
      why:pair('Pokud při menstruaci uvítáš teplé jídlo bez častého míchání, plech usnadní přípravu. Cizrna přidá železo.','If a warm meal with little stirring appeals during your period, a tray makes preparation easier. Chickpeas add iron.'),
      partnerWhy:pair("Když v době menstruace přijde chuť na teplé jídlo, převezmi přípravu plechu s cizrnou, zeleninou a kuskusem.","When a warm meal appeals during a period, take care of a chickpea and vegetable tray with couscous."),
      sourceIds:['food-iron','food-plate'],
    },
  ],
  follicular: [
    {
      id:'food-follicular-cauliflower-bulgur',
      title:pair('Bulgur s květákem a cizrnou','Bulgur with cauliflower and chickpeas'),
      text:pair('Upeč květák s uvařenou cizrnou a římským kmínem. Smíchej s bulgurem, petrželí a citronovou šťávou. Přidej lžíci tahini rozmíchaného s vodou.','Roast cauliflower and cooked chickpeas with cumin. Mix with bulgur, parsley and lemon juice. Add a spoonful of tahini thinned with water.'),
      why:pair('Pokud máš po menstruaci chuť víc vařit, tahle miska nabídne nový recept s obilovinou, zeleninou a luštěninou.','If you feel like cooking more after your period, this bowl offers a new recipe with grains, vegetables and pulses.'),
      partnerWhy:pair("Pokud po menstruaci přijde chuť zkusit něco nového, nabídni společné vaření této misky s obilovinou, zeleninou a cizrnou.","If trying something new appeals after a period, suggest making this bowl of grains, vegetables and chickpeas together."),
      sourceIds:['food-plate'],
    },
    {
      id:'food-follicular-pea-pasta',
      title:pair('Těstoviny s hráškovým pestem','Pasta with pea pesto'),
      text:pair('Krátce povař mražený hrášek. Rozmixuj ho s bazalkou, vlašskými ořechy, citronem a trochou vody z těstovin. Promíchej s celozrnnými těstovinami a přidej rajčata.','Briefly boil frozen peas. Blend with basil, walnuts, lemon and a little pasta water. Toss with wholegrain pasta and add tomatoes.'),
      why:pair('Na rušnější den po menstruaci se hodí rychlá omáčka. Hrášek a ořechy rozšíří výběr rostlinných bílkovin.','For a busier day after your period, this sauce is quick. Peas and walnuts add variety to plant protein choices.'),
      partnerWhy:pair("Na rušnější den po menstruaci připrav rychlé těstoviny; hrášek a ořechy přidají různé rostlinné bílkoviny.","For a busier day after a period, prepare quick pasta with peas and walnuts for varied plant protein."),
      sourceIds:['food-protein'],
    },
    {
      id:'food-follicular-tempeh-rice',
      title:pair('Tempeh se zázvorem a rýží','Ginger tempeh with rice'),
      text:pair('Opeč plátky tempehu s trochou sójové omáčky a zázvoru. Přidej mrkev a zelí nakrájené najemno. Podávej s hnědou rýží a limetou.','Pan-fry tempeh slices with a little soy sauce and ginger. Add finely sliced carrots and cabbage. Serve with brown rice and lime.'),
      why:pair('Pokud se po menstruaci vracíš k delšímu pohybu, rýže s tempehem vytvoří vydatnější jídlo podle tvého hladu.','If you return to longer activity after your period, rice and tempeh make a substantial meal you can size to your hunger.'),
      partnerWhy:pair("Pokud se po menstruaci vrací delší pohyb, nabídni vydatné jídlo s rýží a tempehem a porci přizpůsob aktuálnímu hladu.","If longer activity resumes after a period, offer a substantial rice and tempeh meal with a portion that suits the appetite that day."),
      sourceIds:['food-plate','food-protein'],
    },
    {
      id:'food-follicular-chickpea-pancake',
      title:pair('Cizrnová placka se zeleninou','Chickpea pancake with vegetables'),
      text:pair('Cizrnovou mouku rozmíchej s vodou na hustší těsto a nech chvíli stát. Přidej strouhanou cuketu a bylinky. Usmaž tenké placky na troše oleje, důkladně z obou stran, a podávej s rajčatovým salátem.','Mix chickpea flour with water into a thick batter and leave briefly. Add grated courgette and herbs. Cook thin pancakes thoroughly on both sides in a little oil, then serve with tomato salad.'),
      why:pair('Ve dnech po krvácení můžeš luštěniny zkusit v jiné podobě. Placka nabídne bílkoviny bez složitého vaření.','After bleeding, you might enjoy pulses in a different form. The pancake provides protein without elaborate cooking.'),
      partnerWhy:pair("Po krvácení můžeš nabídnout luštěniny v jiné podobě: cizrnové placky se zeleninou přidají do jídla bílkoviny.","After bleeding, offer pulses in a different form: chickpea pancakes with vegetables add protein to the meal."),
      sourceIds:['food-protein'],
    },
    {
      id:'food-follicular-barley-beans',
      title:pair('Kroupy s houbami a bílými fazolemi','Barley with mushrooms and white beans'),
      text:pair('Uvař kroupy. Na pánvi opeč houby a pórek, přidej propláchnuté uvařené nebo konzervované bílé fazole a promíchej s kroupami. Dokonči petrželí a trochou olivového oleje.','Cook pearl barley. Sauté mushrooms and leeks, add rinsed cooked or canned white beans and combine with the barley. Finish with parsley and a little olive oil.'),
      why:pair('Pokud máš v této části cyklu prostor chystat jídlo dopředu, z jednoho hrnce může být i zítřejší oběd.','If this part of your cycle leaves room for meal preparation, one pot can also provide tomorrow’s lunch.'),
      partnerWhy:pair("V této části cyklu můžeš přípravu usnadnit větší dávkou krup s fazolemi a nabídnout i oběd na další den.","In this part of the cycle, make preparation easier with a larger batch of barley and beans and offer lunch for the next day too."),
      sourceIds:['food-plate'],
    },
    {
      id:'food-follicular-strawberry-oats',
      title:pair('Ovesné vločky s jahodami přes noc','Overnight oats with strawberries'),
      text:pair('Večer smíchej vločky s neslazeným sójovým nápojem obohaceným vápníkem. Nech v lednici. Ráno přidej jahody, dýňová semínka a lžíci sójového jogurtu.','Mix oats with unsweetened calcium-fortified soy drink in the evening and refrigerate. Add strawberries, pumpkin seeds and a spoonful of soy yogurt in the morning.'),
      why:pair('Pokud po menstruaci vyrážíš brzy z domu, hotová snídaně ušetří čas. Obohacený nápoj přidá vápník.','If you head out early after your period, a ready breakfast saves time. The fortified drink contributes calcium.'),
      partnerWhy:pair("Pokud po menstruaci přijdou časná rána, nachystej večer snídani; obohacený sójový nápoj přidá vápník.","If early starts follow a period, prepare breakfast the evening before; fortified soy drink contributes calcium."),
      sourceIds:['food-calcium','food-vegan'],
    },
    {
      id:'food-follicular-black-bean-wrap',
      title:pair('Tortilla s černými fazolemi','Black bean and avocado wrap'),
      text:pair('Prohřej uvařené černé fazole s kukuřicí a římským kmínem. Zabal do celozrnné tortilly s avokádem, rajčetem a salátem. Zakápni limetou.','Warm cooked black beans with sweetcorn and cumin. Wrap in a wholegrain tortilla with avocado, tomato and lettuce. Finish with lime juice.'),
      why:pair('Pro aktivnější den po menstruaci se jídlo dobře bere s sebou. Porci fazolí a tortilly uprav podle hladu.','For a more active day after your period, this meal travels well. Adjust the beans and tortilla to your hunger.'),
      partnerWhy:pair("Na aktivnější den po menstruaci nabídni jídlo s sebou a domluvte se, jak velká porce fazolí a tortilly bude příjemná.","For a more active day after a period, offer a packed meal and ask what portion of beans and tortilla would suit."),
      sourceIds:['food-plate','food-protein'],
    },
    {
      id:'food-follicular-lentil-spinach-curry',
      title:pair('Čočkové kari se špenátem','Lentil and spinach curry'),
      text:pair('Podus rajčata s česnekem a kari kořením. Přidej uvařenou zelenou čočku, špenát a trochu neslazeného sójového nápoje. Prohřej a podávej s rýží.','Simmer tomatoes with garlic and curry spices. Add cooked green lentils, spinach and a little unsweetened soy drink. Heat through and serve with rice.'),
      why:pair('I po krvácení má příjem železa své místo. Čočka ho přináší do běžného jídelníčku.','Dietary iron still matters after bleeding. Lentils help keep it part of ordinary meals.'),
      partnerWhy:pair("Čočkové kari můžeš nabídnout i po krvácení; příjem železa zůstává součástí běžné péče o jídlo.","Offer lentil curry after bleeding too; dietary iron remains part of everyday meals."),
      sourceIds:['food-iron','food-protein'],
    },
  ],
  ovulatory: [
    {
      id:'food-ovulatory-tofu-rolls',
      title:pair('Rýžové závitky s tofu','Rice paper rolls with tofu'),
      text:pair('Rýžový papír krátce namoč. Zabal do něj opečené tofu, uvařené rýžové nudle, okurku a mrkev. Namáčej do arašídového másla rozmíchaného s limetou, vodou a trochou sójové omáčky.','Briefly wet rice paper. Fill with cooked tofu, cooked rice noodles, cucumber and carrot. Dip in peanut butter mixed with lime, water and a little soy sauce.'),
      why:pair('Pokud máš kolem ovulace chuť na svěží jídlo, závitky ji spojí s tofu a nudlemi místo samotné zeleniny.','If fresh food appeals around ovulation, these rolls pair it with tofu and noodles rather than vegetables alone.'),
      partnerWhy:pair("Pokud kolem ovulace přijde chuť na svěží jídlo, nabídni závitky s tofu a nudlemi, které doplní samotnou zeleninu.","If fresh food appeals around ovulation, offer rolls with tofu and noodles to accompany the vegetables."),
      sourceIds:['food-plate','food-protein'],
    },
    {
      id:'food-ovulatory-soba-edamame',
      title:pair('Pohankové nudle s edamame','Soba noodles with edamame'),
      text:pair('Uvař pohankové nudle a edamame, mladé sójové boby, podle návodu. Přidej okurku, strouhanou mrkev a sezam. Promíchej s limetou a trochou sójové omáčky.','Cook soba noodles and edamame, young soybeans, according to the packet instructions. Add cucumber, grated carrot and sesame. Toss with lime and a little soy sauce.'),
      why:pair('Když kolem ovulace nechceš dlouho vařit, miska je rychlá a sójové boby přidají bílkoviny.','When you prefer less cooking around ovulation, this bowl is quick and the soybeans add protein.'),
      partnerWhy:pair("Když kolem ovulace není chuť trávit čas u plotny, můžeš připravit rychlou misku nudlí se sójovými boby jako zdrojem bílkovin.","When time at the stove is unappealing around ovulation, prepare a quick noodle bowl with soybeans for protein."),
      sourceIds:['food-protein'],
    },
    {
      id:'food-ovulatory-herb-couscous',
      title:pair('Bylinkový kuskus s fazolemi','Herby couscous with butter beans'),
      text:pair('Celozrnný kuskus zalij horkou vodou podle návodu. Vmíchej uvařené velké bílé fazole, rajčata, okurku a petržel. Přidej olivový olej a citron.','Prepare wholegrain couscous with hot water following the packet instructions. Stir in cooked butter beans, tomatoes, cucumber and parsley. Add olive oil and lemon.'),
      why:pair('Pokud uprostřed cyklu plánuješ den venku, kuskus nabídne rychlý oběd do krabičky s přílohou i luštěninou.','If you plan a day out around mid-cycle, couscous makes a quick packed lunch with both grains and pulses.'),
      partnerWhy:pair("Na společný den venku kolem ovulace nachystej kuskus s fazolemi do krabičky, aby byl oběd po ruce.","For a day out together around ovulation, pack couscous with beans so lunch is ready to hand."),
      sourceIds:['food-plate'],
    },
    {
      id:'food-ovulatory-lentil-salad',
      title:pair('Čočkový salát s olivami','Lentil salad with olives'),
      text:pair('Uvařenou čočku promíchej s rajčaty, okurkou, několika olivami a petrželí. Dochuť citronem a olivovým olejem. Jez s celozrnným chlebem.','Mix cooked lentils with tomatoes, cucumber, a few olives and parsley. Dress with lemon and olive oil. Serve with wholegrain bread.'),
      why:pair('Při chuti na salát kolem ovulace čočka a chléb doplní zeleninu, aby z ní vzniklo celé jídlo.','If you fancy salad around ovulation, lentils and bread turn the vegetables into a full meal.'),
      partnerWhy:pair("Pokud je kolem ovulace chuť na salát, nabídni k zelenině také čočku a chléb, aby vzniklo celé jídlo.","If salad appeals around ovulation, offer lentils and bread with the vegetables to make a full meal."),
      sourceIds:['food-plate'],
    },
    {
      id:'food-ovulatory-hummus-sandwich',
      title:pair('Chléb s hummusem a pečenou paprikou','Hummus and roasted pepper sandwich'),
      text:pair('Chléb namaž hummusem z cizrny. Přidej pečenou papriku, plátky okurky a rukolu. Když chceš, přisyp opražená slunečnicová semínka.','Spread bread with chickpea hummus. Add roasted pepper, cucumber slices and rocket. Sprinkle with toasted sunflower seeds if you like.'),
      why:pair('Pro rušný den kolem ovulace je to oběd bez dalšího vaření. Cizrna a semínka přispějí bílkovinami.','For a busy day around ovulation, this is lunch without more cooking. Chickpeas and seeds contribute protein.'),
      partnerWhy:pair("V rušném dni kolem ovulace může pomoct hotový chléb s hummusem; cizrna a semínka do něj přidají bílkoviny.","On a busy day around ovulation, a ready hummus sandwich can help; chickpeas and seeds add protein."),
      sourceIds:['food-protein'],
    },
    {
      id:'food-ovulatory-tofu-broccoli',
      title:pair('Tofu s brokolicí a bramborami','Tofu with broccoli and potatoes'),
      text:pair('Upeč malé brambory a kostky tofu. Brokolici přidej na plech až ke konci. Podávej s omáčkou z tahini, citronu a vody.','Roast small potatoes and cubed tofu. Add broccoli to the tray near the end. Serve with a sauce of tahini, lemon and water.'),
      why:pair('Pokud máš kolem ovulace chuť na teplou večeři, jídlo nabídne zeleninu, bílkoviny i přílohu bez zvláštního dietního pravidla.','If you want a warm dinner around ovulation, this meal combines vegetables, protein and a starchy base without a special diet rule.'),
      partnerWhy:pair("Na večer kolem ovulace se zeptej na chuť na teplé jídlo a nabídni tofu s brokolicí a bramborami.","For an evening around ovulation, ask whether a warm meal appeals and offer tofu with broccoli and potatoes."),
      sourceIds:['food-plate','food-protein'],
    },
    {
      id:'food-ovulatory-pita-chickpea-patties',
      title:pair('Pita s cizrnovými placičkami','Pita with chickpea patties'),
      text:pair('Uvařenou cizrnu rozmačkej s petrželí, římským kmínem a trochou ovesné mouky. Vytvaruj malé placičky a opeč. Dej je do pity se zelím, rajčetem a citronovým sójovým jogurtem.','Mash cooked chickpeas with parsley, cumin and a little oat flour. Shape into small patties and pan-fry. Put into pita with cabbage, tomato and lemony soy yogurt.'),
      why:pair('Pokud kolem ovulace vaříte spolu, každý si může naplnit pitu podle své chuti a velikosti hladu.','If you cook together around ovulation, each person can fill a pita to suit their own appetite and taste.'),
      partnerWhy:pair("Při společném vaření kolem ovulace můžeš připravit placičky a zeleninu zvlášť, aby si každý naplnil pitu podle chuti a hladu.","When cooking together around ovulation, prepare the patties and vegetables separately so each person can fill a pita to suit their taste and hunger."),
      sourceIds:['food-plate'],
    },
    {
      id:'food-ovulatory-pea-mint-soup',
      title:pair('Hrášková polévka s mátou','Pea and mint soup'),
      text:pair('Brambor nakrájej a uvař doměkka. Přidej mražený hrášek, krátce povař a rozmixuj s mátou. Polévku podávej teplou nebo vychlazenou. Přidej toast s rozmačkanými uvařenými nebo konzervovanými bílými fazolemi a citronem.','Dice a potato and cook until tender. Add frozen peas, simmer briefly and blend with mint. Serve the soup warm or chilled with toast topped with mashed cooked or canned white beans and lemon.'),
      why:pair('Když máš uprostřed cyklu chuť na menší porci, můžeš začít polévkou a toast si přidat podle hladu.','If you want a smaller portion around mid-cycle, start with soup and add toast according to your hunger.'),
      partnerWhy:pair("Pokud uprostřed cyklu stačí menší porce, nabídni polévku a nech fazolový toast po ruce pro případ dalšího hladu.","If a smaller portion suits around mid-cycle, offer soup and keep bean toast available in case more food is wanted."),
      sourceIds:['food-vegan','food-appetite-study'],
    },
  ],
  luteal: [
    {
      id:'food-luteal-pear-porridge',
      title:pair('Ovesná kaše s hruškou a ořechy','Pear and walnut porridge'),
      text:pair('Vločky uvař v neslazeném sójovém nápoji obohaceném vápníkem. Přidej hrušku, skořici, vlašské ořechy a lžíci mletého lnu.','Cook oats in unsweetened calcium-fortified soy drink. Add pear, cinnamon, walnuts and a spoonful of ground flaxseed.'),
      why:pair('Pokud před menstruací snídaně nestačí, můžeš zvětšit porci. Obohacený nápoj přidá vápník.','If breakfast leaves you hungry before your period, increase the portion. The fortified drink adds calcium.'),
      partnerWhy:pair("Pokud před menstruací běžná snídaně nestačí, nabídni přidání kaše; obohacený sójový nápoj v ní přispěje vápníkem.","If the usual breakfast is not enough before a period, offer more porridge; fortified soy drink contributes calcium."),
      sourceIds:['food-biocy','food-calcium','food-pms'],
    },
    {
      id:'food-luteal-pumpkin-chilli',
      title:pair('Fazolové chilli s dýní','Bean and pumpkin chilli'),
      text:pair('Podus cibuli, dýni a rajčata s uzenou paprikou. Přidej uvařené červené a černé fazole. Podávej s rýží. Část na další den nech zchladnout a ulož do lednice.','Simmer onion, pumpkin and tomatoes with smoked paprika. Add cooked kidney and black beans. Serve with rice. Cool and refrigerate a portion for the next day.'),
      why:pair('Když se v luteální fázi ozve větší hlad, připravené chilli usnadní najíst se bez dalšího vaření.','If you feel hungrier in the luteal phase, ready-made chilli makes it easier to eat without more cooking.'),
      partnerWhy:pair("Když se před menstruací ozve větší hlad, můžeš pomoct hotovým chilli, které stačí prohřát.","If hunger grows before a period, help by having chilli ready to heat up."),
      sourceIds:['food-intake-review','food-plate'],
    },
    {
      id:'food-luteal-peanut-stew',
      title:pair('Batát s tofu v arašídové omáčce','Sweet potato and tofu in peanut sauce'),
      text:pair('Batát nakrájený na kostky podus s rajčaty a vodou doměkka. Vmíchej arašídové máslo a opečené tofu. Přidej limetu a podávej s rýží.','Simmer cubed sweet potato with tomatoes and water until tender. Stir in peanut butter and cooked tofu. Add lime and serve with rice.'),
      why:pair('Pokud máš před menstruací větší chuť k jídlu, tahle večeře spojí přílohu, tofu i arašídy do vydatné porce.','If your appetite grows before your period, this dinner combines a starchy base, tofu and peanuts into a substantial meal.'),
      partnerWhy:pair("Při větší chuti k jídlu před menstruací nabídni sytější večeři s batátem, tofu a arašídy.","For a larger appetite before a period, offer a substantial dinner with sweet potato, tofu and peanuts."),
      sourceIds:['food-biocy','food-protein'],
    },
    {
      id:'food-luteal-creamy-bean-pasta',
      title:pair('Krémové těstoviny s bílými fazolemi','Creamy white bean pasta'),
      text:pair('Uvařené nebo konzervované bílé fazole rozmixuj s citronem, česnekem a trochou horké vody z těstovin. Omáčku prohřej se špenátem a vmíchej celozrnné těstoviny. Přidej olivový olej.','Blend cooked or canned white beans with lemon, garlic and a little hot pasta water. Warm the sauce with spinach and stir in wholegrain pasta. Add olive oil.'),
      why:pair('Na dny před menstruací nabídne teplé jídlo s celozrnnou přílohou. Krémová omáčka vznikne přímo z luštěnin.','For days before your period, this offers a warm meal with whole grains. The creamy sauce comes from pulses themselves.'),
      partnerWhy:pair("Na dny před menstruací můžeš připravit teplé celozrnné těstoviny s jemnou fazolovou omáčkou.","For the days before a period, prepare warm wholegrain pasta with a smooth bean sauce."),
      sourceIds:['food-pms','food-protein'],
    },
    {
      id:'food-luteal-potato-tempeh',
      title:pair('Brambory s brokolicí a tempehem','Potatoes with broccoli and tempeh'),
      text:pair('Upeč brambory a na pánvi opeč rozdrobený tempeh. Přidej brokolici krátce vařenou v páře. Omáčku udělej ze sójového jogurtu, česneku a pažitky.','Roast potatoes and pan-fry crumbled tempeh. Add briefly steamed broccoli. Make a sauce with soy yogurt, garlic and chives.'),
      why:pair('Pokud je v závěru cyklu hlad výraznější, přidej brambory nebo tempeh podle sebe. Fáze neurčuje pevnou velikost porce.','If hunger is stronger late in your cycle, add potatoes or tempeh to suit you. The phase does not set a fixed portion.'),
      partnerWhy:pair("Pokud je na konci cyklu hlad výraznější, nech na stole brambory i tempeh navíc, aby si druhý člověk mohl přidat podle sebe.","If hunger is stronger late in the cycle, leave extra potatoes and tempeh on the table so the other person can help themselves."),
      sourceIds:['food-intake-review','food-appetite-study','food-protein'],
    },
    {
      id:'food-luteal-hummus-snack',
      title:pair('Hummus s pitou a mrkví','Hummus with pita and carrot'),
      text:pair('Uvařenou nebo konzervovanou cizrnu rozmixuj s tahini, citronem a trochou vody. Dej do misky s teplou pitou a proužky mrkve. Pro rychlou svačinu použij hotový hummus.','Blend cooked or canned chickpeas with tahini, lemon and a little water. Serve with warm pita and carrot sticks. Use ready-made hummus for a quick snack.'),
      why:pair('Když se před menstruací objeví hlad mezi jídly, můžeš přidat svačinu místo čekání na další velké jídlo.','If you get hungry between meals before your period, add a snack rather than waiting for the next large meal.'),
      partnerWhy:pair("Při hladu mezi jídly před menstruací nabídni hummus s pitou a mrkví jako snadnou svačinu.","For hunger between meals before a period, offer hummus with pita and carrot as an easy snack."),
      sourceIds:['food-biocy','food-pms'],
    },
    {
      id:'food-luteal-apple-millet',
      title:pair('Jáhlová kaše s pečeným jablkem','Millet porridge with baked apple'),
      text:pair('Jáhly uvař v neslazeném sójovém nápoji obohaceném vápníkem. Přidej jablko upečené se skořicí a lžíci mandlového másla. Hustotu dolaď dalším nápojem.','Cook millet in unsweetened calcium-fortified soy drink. Add an apple baked with cinnamon and a spoonful of almond butter. Adjust the thickness with more soy drink.'),
      why:pair('Pokud máš před menstruací chuť na sladkou snídani, jablko ji doplní. Sójový nápoj přinese bílkoviny i přidaný vápník.','If you fancy a sweet breakfast before your period, apple adds that flavour. Soy drink contributes protein and added calcium.'),
      partnerWhy:pair("Pokud před menstruací přijde chuť na sladkou snídani, nabídni kaši s pečeným jablkem a sójovým nápojem obohaceným vápníkem.","If a sweet breakfast appeals before a period, offer porridge with baked apple and calcium-fortified soy drink."),
      sourceIds:['food-biocy','food-calcium','food-protein'],
    },
    {
      id:'food-luteal-lentil-pie',
      title:pair('Čočka zapečená pod bramborovou kaší','Lentils under a potato mash crust'),
      text:pair('Uvařenou čočku podus s mrkví, houbami a rajčaty. Dej do pekáčku, zakryj bramborovou kaší s olivovým olejem a zapeč. Podávej s hráškem.','Simmer cooked lentils with carrots, mushrooms and tomatoes. Transfer to a baking dish, cover with potato mash made with olive oil and bake. Serve with peas.'),
      why:pair('Pokud před menstruací ubývá chuť vařit, připravený pekáček může vystačit na dvě jídla. Porci zvol podle hladu.','If you feel less like cooking before your period, a prepared tray can provide two meals. Let your hunger guide the portion.'),
      partnerWhy:pair("Když před menstruací ubývá chuť vařit, připrav čočkový pekáček i na další jídlo a porce nechte podle hladu.","When cooking feels less appealing before a period, prepare a lentil bake for another meal too and let appetite guide the portions."),
      sourceIds:['food-plate','food-appetite-study'],
    },
  ],
};
