import {NAKSHATRAS,SIGN_RULERS} from "./togetherAstrology.js";
import {ASTRO_PLANETS,ASTRO_ASPECTS,ASTRO_SIGNS,ASTRO_DIGNITIES} from "./togetherAstrologyEditorial.js";
import {MOON_NAMES,ZODIAC} from "./togetherMoon.js";
import {astrologyDominants} from "./togetherAstrologyOverview.js";

// Names and fivefold sequence: Brihat Samhita 99.2. The interpretations below
// are original contemporary editorial, not translations of electional rules.
export const TITHI_QUALITIES=[
  {name:"Nandá",title:["Dát životu výživu","Nourish life"],text:["Obraz radosti otevírá rozdíl mezi tím, co nás na okamžik zabaví, a tím, co nás skutečně vyživuje. Pozornost může spočinout u malé věci, kterou chceme v životě dál živit.","The image of joy distinguishes momentary diversion from genuine nourishment. Attention can rest on one small thing we wish to keep alive."]},
  {name:"Bhadrá",title:["Připravit dobré podmínky","Prepare sound conditions"],text:["Příznivost tu čteme jako péči o podmínky, ne slib výsledku. Dobrý úmysl potřebuje prostředí: jasnou domluvu, dost času a něco, o co se může opřít.","We read auspiciousness as care for conditions rather than a promise of results. Good intentions need an environment: clarity, time and support."]},
  {name:"Vidžajá",title:["Síla, která se nemusí přít","Strength without a contest"],text:["Vítězství lze obrátit dovnitř: přestat živit automatickou reakci, která nás vzdaluje tomu, čemu věříme. Nejde o přemožení druhého, ale o věrnost zvolenému směru.","Victory can turn inward: ceasing to feed an automatic response that takes us away from our values. It becomes fidelity to a chosen direction rather than defeating another."]},
  {name:"Riktá",title:["Uvolnit místo","Make room"],text:["Prázdno nemusí být nedostatek. Může být prostorem, který vznikne po odložení přebytečného. Tento obraz zve k rozlišení mezi ztrátou něčeho živého a uvolněním toho, co už jen zabírá místo.","Emptiness need not be a lack. It can be the room left by releasing excess, distinguishing the loss of something alive from letting go of what only occupies space."]},
  {name:"Púrná",title:["Nechat celek dozrát","Let the whole ripen"],text:["Plnost se nemusí dokazovat dalším přidáváním. Obraz uzavřeného tvaru připomíná schopnost něco dokončit, přijmout jeho nedokonalost a chvíli u toho zůstat.","Fullness need not prove itself by adding more. A completed form suggests finishing something, accepting its imperfection and staying with it for a moment."]}
];
export const tithiQuality=tithi=>TITHI_QUALITIES[(tithi-1)%5];

const PAIR_READINGS={
  "Sun:Moon":["Směr a potřeba nejsou totéž. Celistvost vzniká, když vědomý záměr bere vážně i to, co tělo a cit skutečně unesou.","Direction and need are different. Wholeness lets conscious intention take bodily and emotional capacity seriously."],
  "Sun:Mercury":["Vlastní příběh a způsob jeho vyprávění se potkávají. Jasnost přichází, když slova neslouží jen obrazu o sobě, ale i přesnějšímu vidění skutečnosti.","Identity meets the language used to express it. Clarity comes when words serve perception as well as self-image."],
  "Sun:Venus":["Vědomý směr se dotýká toho, čemu přiznáváme cenu. Soulad začíná tam, kde to, co žijeme, odpovídá tomu, co říkáme, že milujeme.","Conscious direction meets what we value. Accord begins where lived choices match what we say we love."],
  "Sun:Mars":["Vůle hledá čin. Důležitý není jen dostatek síly, ale také rozlišení, jestli její použití chrání živý záměr, nebo pouze vlastní převahu.","Will seeks action. The issue is not only having force but whether it serves a living intention or personal dominance."],
  "Sun:Jupiter":["Vlastní směr se rozšiřuje o větší příběh. Důvěra zůstává živá, když snese, že osobní přesvědčení není posledním slovem o světě.","A personal direction opens to a larger story. Trust stays alive when conviction need not be the final word about the world."],
  "Sun:Saturn":["Živý záměr se setkává s časem a mezemi. Odpovědnost zde nemusí světlo utlumit: může mu dát tvar, který vydrží i bez okamžitého uznání.","A living intention meets time and limits. Responsibility can give it a lasting form without requiring immediate recognition."],
  "Sun:Uranus":["Střed a svoboda se potkávají v možnosti jednat jinak než ze zvyku. Změna má větší hloubku, když vyjadřuje něco pravdivého, místo aby pouze překvapovala.","Centre and freedom meet in the possibility of acting beyond habit. Change deepens when it expresses something true rather than merely surprising."],
  "Sun:Neptune":["Jasný tvar identity se dotýká něčeho, co nelze plně pojmenovat. Inspirace potřebuje prostor i rozlišení, aby se z citlivosti nestalo rozpouštění vlastního hlasu.","A clear identity meets something not fully nameable. Inspiration needs both space and discernment so sensitivity does not dissolve one's voice."],
  "Sun:Pluto":["Vědomý příběh se setkává s tím, co zůstává pod ním. Síla dozrává tam, kde dokáže přiznat vlastní motiv, aniž by jím musela řídit ostatní.","A conscious story meets its hidden layers. Strength matures when it can acknowledge a motive without using it to control others."],
  "Moon:Mercury":["Prožitek a jeho pojmenování se nemusí překrývat. Je možné něco jasně cítit a teprve hledat slova, která zkušenost nezploští.","Experience and its description need not coincide. A feeling can be clear before words can hold it without flattening it."],
  "Moon:Venus":["Potřeba bezpečí se setkává s přitažlivostí a potěšením. Blízkost může být svobodnější, když rozlišíme, co nás vyživuje a co jen utišuje nejistotu.","Safety meets attraction and pleasure. Closeness becomes freer when nourishment is distinguished from soothing insecurity."],
  "Moon:Mars":["Citlivost se dotýká síly jednat. Impuls může být zprávou o potřebě ochrany; podobu odpovědi lze zvolit až po tom, co tuto potřebu uslyšíme.","Sensitivity meets the force to act. An impulse may signal a need for protection; the response can be chosen after that need is heard."],
  "Moon:Jupiter":["Bezprostřední pocit hledá širší smysl. Naděje je podpůrná, když nemusí přeskakovat skutečnou zkušenost, která právě potřebuje být přijata.","An immediate feeling seeks wider meaning. Hope supports us when it does not bypass an experience that needs acceptance."],
  "Moon:Saturn":["Potřeba péče stojí vedle nároku vydržet. Zralá opora unese obojí: uzná citlivost a současně jí nabídne spolehlivý, nenásilný rámec.","The need for care stands beside endurance. Mature support acknowledges sensitivity while offering a reliable, unforced frame."],
  "Moon:Uranus":["Známé bezpečí se potkává s potřebou prostoru. Nová možnost nemusí znamenat ztrátu opory; může změnit její podobu.","Familiar safety meets a need for space. A new possibility need not remove support; it may change its form."],
  "Moon:Neptune":["Vnímavost se otevírá obrazům a náladám. Jemné rozlišení pomáhá poznat vlastní prožitek, aniž bychom z něj dělali jistotu o druhém člověku.","Receptivity opens to images and moods. Discernment helps recognise an experience without treating it as certainty about someone else."],
  "Moon:Pluto":["Bezprostřední pocit se může stát dveřmi ke starší vrstvě zkušenosti. Hloubka zde znamená prostor pro pravdivost, nikoli tlak na odhalení všeho najednou.","An immediate feeling can open a door to older experience. Depth means room for honesty, not pressure to reveal everything at once."],
  "Mercury:Venus":["Slovo a hodnota hledají společný jazyk. Jemnost řeči může nést pravdu i hranici, aniž by z nich dělala obchod za přijetí.","Speech and value seek a shared language. Gentle words can carry truth and boundaries without bargaining for acceptance."],
  "Mercury:Mars":["Myšlenka a čin se dotýkají. Rozlišit přesnost od ostrosti pomáhá, aby slovo něco objasnilo a nemuselo přitom zasáhnout druhého.","Thought and action meet. Distinguishing precision from sharpness lets words clarify without having to wound."],
  "Mercury:Jupiter":["Detail se potkává s velkým výkladem. Porozumění potřebuje schopnost uvidět souvislost a zároveň se vrátit k tomu, co skutečně víme.","Detail meets a larger interpretation. Understanding needs both a broad view and a return to what is actually known."],
  "Mercury:Saturn":["Myšlení získává rámec a odpovědnost. Přesnost je plodná, když pomáhá něco unést, ne když zakazuje otázku, na kterou ještě nemáme odpověď.","Thought meets structure and responsibility. Precision helps when it supports something rather than forbidding unanswered questions."],
  "Mercury:Uranus":["Známý způsob myšlení se otevírá jinému spojení. Záblesk poznání dozrává teprve tehdy, když pro něj najdeme srozumitelný a ověřitelný tvar.","A familiar thought pattern opens to another connection. Insight matures through an intelligible form that can be examined."],
  "Mercury:Neptune":["Pojem se dotýká obrazu. Poezie a intuice mohou rozšířit jazyk, pokud nezaměníme vnitřní přesvědčivost za ověřenou skutečnost.","Concept meets image. Poetry and intuition can widen language when inner conviction is not mistaken for verified fact."],
  "Mercury:Pluto":["Slova míří pod přijatelný povrch. Odhalit skrytý motiv je jiné než přisoudit ho druhému; poctivé zkoumání si nechává prostor změnit názor.","Words reach beneath an acceptable surface. Discovering a motive differs from assigning it to someone; honest inquiry leaves room to revise."],
  "Venus:Mars":["To, co přitahuje, se potkává se silou vykročit. Blízkost zůstává živá, když touha dokáže slyšet odpověď a nemusí ji předem zajistit.","Attraction meets the force to move towards it. Closeness stays alive when desire can hear an answer without securing it in advance."],
  "Venus:Jupiter":["Potěšení se rozšiřuje do štědrosti. Míra pomáhá poznat, kdy skutečně přidáváme život a kdy jen další nárok na jeho intenzitu.","Pleasure expands towards generosity. Proportion distinguishes adding life from demanding greater intensity."],
  "Venus:Saturn":["Hodnota se prověřuje časem. Věrnost něčemu nemusí znamenat setrvat v každé podobě; může znamenat hledat tvar, který je dlouhodobě pravdivý.","Value meets the test of time. Fidelity need not preserve every existing form; it may seek one that remains honest over time."],
  "Venus:Uranus":["Přitažlivost se setkává se svobodou. Živý vztah k tomu, co milujeme, potřebuje možnost nově uvidět i to, co už důvěrně známe.","Attraction meets freedom. A living relationship with what we love needs the possibility of seeing the familiar anew."],
  "Venus:Neptune":["Krása se dotýká ideálu. Zralá citlivost dovoluje milovat skutečnou podobu života i tehdy, když se nevejde do vytouženého obrazu.","Beauty meets an ideal. Mature sensitivity can love actual life even when it does not fit a cherished image."],
  "Venus:Pluto":["Hodnota a vazba se setkávají s otázkou držení a pouštění. Hloubka neznamená vlastnit; dovoluje vidět cenu něčeho i bez kontroly nad tím.","Value and attachment meet holding and releasing. Depth can recognise worth without needing control."],
  "Mars:Jupiter":["Čin dostává větší horizont. Odvaha je nosná, když se ptá také na důsledky a nenechá nadšení přerůst vlastní možnosti.","Action gains a wider horizon. Courage stays grounded when enthusiasm includes consequences and capacity."],
  "Mars:Saturn":["Síla se setkává s mezí. Trpělivost nemusí pohyb zastavit: může ho rozdělit na kroky, které lze opravdu unést a dokončit.","Force meets a limit. Patience can divide motion into steps that can actually be carried and completed."],
  "Mars:Uranus":["Impuls ke změně získává rozhodnost. Svoboda dozrává, když vedle průlomu unese i práci s tím, co po něm zůstane.","The impulse for change gains resolve. Freedom matures when it can tend what remains after a breakthrough."],
  "Mars:Neptune":["Vůle se setkává s inspirací a přesahujícím obrazem. Vědomý čin potřebuje vědět, čemu slouží, aby energie nezůstala jen v představě.","Will meets inspiration and a larger image. Conscious action needs to know what it serves so energy does not remain imaginary."],
  "Mars:Pluto":["Síla se dotýká moci. Podstatné je, zda chrání možnost žít, nebo se pokouší vynutit proměnu; skutečná rozhodnost nemusí druhého přemoci.","Force meets power. The distinction is between protecting life and forcing transformation; resolve need not overpower another."],
  "Jupiter:Saturn":["Rozšiřování se setkává s vymezováním. Život potřebuje obě gesta: smysl, kvůli němuž stojí za to vykročit, a tvar, v němž lze pokračovat.","Expansion meets definition. Life needs both a reason to move and a form in which it can continue."],
  "Jupiter:Uranus":["Větší příběh se otevírá nečekané možnosti. Svoboda myšlení roste, když nové poznání nemusí okamžitě vystřídat jednu absolutní jistotu druhou.","A larger story opens to an unexpected possibility. Free thought need not replace one absolute certainty with another."],
  "Jupiter:Neptune":["Důvěra se setkává s touhou po přesahu. Šíře srdce potřebuje rozlišení, aby víra rozšiřovala život a nemusela popírat jeho konkrétní podobu.","Trust meets transcendence. An open heart needs discernment so faith can widen life without denying its concrete form."],
  "Jupiter:Pluto":["Smysl se dotýká hlubších motivů a vlivu. Přesvědčení může být oporou, pokud unese zkoumání toho, komu slouží a jakou cenu za něj platíme.","Meaning meets deeper motives and influence. A conviction supports us when its purpose and cost remain open to examination."],
  "Saturn:Uranus":["Struktura se setkává s potřebou změny. Trvalá obnova rozlišuje oporu, kterou chceme zachovat, od zvyku, který už brání pohybu.","Structure meets change. Lasting renewal distinguishes support worth keeping from habits that block movement."],
  "Saturn:Neptune":["Tvar se dotýká beztvarého. Soucit a imaginace potřebují břehy; struktura zase důvod, proč má sloužit živému člověku místo pouhému pořádku.","Form meets the formless. Compassion and imagination need shores; structure needs a purpose beyond order alone."],
  "Saturn:Pluto":["Trvání se setkává s hlubokou proměnou. Obraz otevírá rozdíl mezi odpovědností za něco živého a udržováním tvaru pouze silou.","Endurance meets deep change. The image distinguishes responsibility for something alive from maintaining a form by force."],
  "Uranus:Neptune":["Nová možnost se dotýká společné imaginace. Dlouhé pozadí tohoto spojení zkoumá, jak dát intuici svobodnější podobu a nepřestat přitom rozlišovat.","New possibility meets shared imagination. This long background explores freer forms of intuition without abandoning discernment."],
  "Uranus:Pluto":["Průlom se dotýká kořene starého uspořádání. Změna je hlubší, když se neomezí na nové označení a promění i způsob zacházení se silou.","A breakthrough reaches the roots of an arrangement. Change deepens when it transforms the use of power rather than merely the label."],
  "Neptune:Pluto":["Společné obrazy se setkávají s tím, co zůstává pod povrchem. Tento velmi pomalý vztah patří dlouhému horizontu: proměně ideálů, významů a způsobů, jimiž hledáme přesah.","Shared images meet what lies beneath the surface. This very slow relationship belongs to a long horizon of changing ideals, meanings and ways of seeking transcendence."]
};
const select=(lang,pair)=>pair[lang==="en"?1:0];
const planetName=(id,lang)=>select(lang,ASTRO_PLANETS[id].name);
const aspectId=a=>a.aspect||a.id;
export function aspectReading(aspect,lang="cs"){
  const pair=PAIR_READINGS[`${aspect.a}:${aspect.b}`]||PAIR_READINGS[`${aspect.b}:${aspect.a}`];
  return `${select(lang,pair||["Dva různé principy se v tomto vztahu stávají součástí jednoho obrazu.","Two different principles become parts of one image in this relationship."])} ${select(lang,ASTRO_ASPECTS[aspectId(aspect)].text)}`;
}
export function astrologyEventTitle(event,lang="cs"){
  const L=(cs,en)=>lang==="en"?en:cs,n=id=>planetName(id,lang);
  if(event.type==="station")return `${n(event.body)} · ${event.direction==="retrograde"?L("obrat do retrográdního pohybu","station retrograde"):L("obrat do přímého pohybu","station direct")}`;
  if(event.type==="ingress")return `${n(event.body)} · ${L(...ZODIAC[event.from])} → ${L(...ZODIAC[event.to])}`;
  if(event.type==="phase")return L(...MOON_NAMES[event.phase]);
  if(event.type==="nakshatra")return `${L("Nakšatra","Nakshatra")} · ${NAKSHATRAS[event.from]} → ${NAKSHATRAS[event.to]}`;
  if(event.type==="tithi")return `${(event.to-1)%15+1}. tithi · ${event.to<=15?"Šukla pakša":"Krišna pakša"} · ${tithiQuality(event.to).name}`;
  return `${n(event.a)} — ${n(event.b)} · ${L(...ASTRO_ASPECTS[aspectId(event)].name)}`;
}
export function astrologyEventReading(event,lens,lang="cs"){
  const L=(cs,en)=>lang==="en"?en:cs;
  if(event.type==="aspect")return aspectReading(event,lang);
  if(event.type==="station"){
    const theme=L(...ASTRO_PLANETS[event.body].theme);
    if(lens==="jyotish")return L(`Vakra označuje zpětný pohyb gráhy. Změnu směru zde sledujeme jako výrazný časový předěl, nikoli jako obecné oslabení. Symbolické téma „${theme.toLowerCase()}“ čteme spolu se siderickým znamením; z obratu samotného neurčujeme výsledek.`,`Vakra denotes a graha's retrograde motion. A station is a marked temporal change, not a general weakening. Read “${theme.toLowerCase()}” together with its sidereal sign rather than deducing an outcome from reversal alone.`);
    if(lens==="hellenistic")return L(`Obrat mění způsob pohybu planety, nikoli jejího hostitele. Téma „${theme.toLowerCase()}“ proto čteme současně s vládcem znamení a jeho postavením. Jeden výrazný okamžik není celý úsudek o obloze.`,`A station changes motion, not the sign's host. Read “${theme.toLowerCase()}” together with the ruler and its position. One marked moment is not a complete judgement of the sky.`);
    return event.direction==="retrograde"?L(`Změna směru zvýrazňuje téma „${theme.toLowerCase()}“. V současném symbolickém čtení je to obraz návratu k motivu a ceně našeho jednání. Užitečné je znovu rozlišit, čemu dáváme sílu ze svobodné volby a co pouze opakujeme.`,`The reversal highlights “${theme.toLowerCase()}”. In contemporary symbolism it is an image of revisiting motives and costs: distinguishing freely chosen commitments from repetition.`):L(`Přechod do přímého pohybu otevírá obraz postupného ztělesnění tématu „${theme.toLowerCase()}“. Obrat není okamžitý skok vpřed: pohyb poblíž stanice zůstává pomalý. Smysl má nechat porozumění získávat konkrétní podobu.`,`The turn direct evokes gradually embodying “${theme.toLowerCase()}”. A station is not an instant leap forward; motion nearby stays slow. Understanding can acquire a concrete form step by step.`);
  }
  if(event.type==="ingress"){
    const from=planetName(SIGN_RULERS[event.from],lang),to=planetName(SIGN_RULERS[event.to],lang);
    const opening=lens==="western"?L("Přechod znamením mění symbolický způsob vyjádření planety.","A sign crossing changes the planet's symbolic mode of expression."):L(`Mění se prostředí a hostitel: ${from} → ${to}. Výklad se tak přesouvá také k postavení nového vládce znamení.`,`The setting and host change: ${from} → ${to}. Interpretation also turns to the new ruler's condition.`);
    return `${opening} ${L(...ASTRO_SIGNS[event.to].text)}`;
  }
  if(event.type==="tithi")return L(...tithiQuality(event.to).text);
  if(event.type==="nakshatra")return L("Měsíc překračuje hranici úseku hvězdného kruhu o 13° 20′. Raši může zůstat stejné, zatímco jemnější lunární čas už mění jméno. Tuto hranici čteme společně s tithi, ne jako samostatný soud o příznivosti dne.","The Moon crosses a 13°20′ stellar sector. Its rashi may remain unchanged while a finer lunar interval changes name. Read this boundary alongside the tithi, not as an independent verdict on the day.");
  const phases={
    0:["Obě světla se setkávají v délce. Nov lze číst jako ztišení před rozvinutím dalšího tvaru: nejprve rozpoznat živý záměr a nedávat mu hned všechny závazky hotového příběhu.","The two lights meet in longitude. A new Moon can be read as stillness before a form unfolds: recognising an intention before burdening it with a complete story."],
    2:["První čtvrť rozděluje kruh pravým úhlem při přibývání světla. Symbolicky se záměr setkává s konkrétní podobou: co už lze uskutečnit a co je potřeba změnit, aby pohyb zůstal živý.","The first quarter forms a right angle as light grows. Symbolically intention meets form: what can become real and what needs adjusting so movement stays alive."],
    4:["Světla stojí naproti sobě. Úplněk otevírá obraz viditelnosti a polarity: uvidět oba konce zkušenosti, aniž by se jeden musel stát viníkem druhého. Zrání zahrnuje i schopnost unést rozdíl.","The lights oppose one another. A full Moon evokes visibility and polarity: seeing both ends of an experience without making one the other's culprit."],
    6:["Poslední čtvrť tvoří pravý úhel při ubývání světla. Obraz směřuje k přehodnocení: rozlišit, co zkušenost skutečně přinesla a kterou podobu už není nutné nést do dalšího kola.","The last quarter forms a right angle as light wanes. Its image is reassessment: distinguishing what experience gave from what need not be carried into the next cycle."]
  };
  return L(...phases[event.phase]);
}

export function astrologyOverviewReading(sky,period,lang="cs"){
  const L=(cs,en)=>lang==="en"?en:cs,n=id=>planetName(id,lang),sign=p=>L(...ZODIAC[p.sign]);
  const d=astrologyDominants(sky,period),layers=[],lens=period.lens,event=d.priorityEvent,moon=sky.planets[1];
  const eventLayer=event?{key:"event",title:L("Výrazný předěl období","A marked change in the period"),fact:astrologyEventTitle(event,lang),text:astrologyEventReading(event,lens,lang),event}:null;
  const phaseText=sky.moon.elongation<180?L("Světla přibývá: obraz nabývá tvar a hledá vnější vyjádření.","Light is growing: the image acquires form and seeks expression."):L("Světla ubývá: obraz obrací pozornost k tomu, co ze zkušenosti zůstává podstatné.","Light is waning: attention turns to what remains essential from experience.");
  let title,summary,method,connection,context;
  if(lens==="western"){
    const focus=d.personal||d.lunar;
    const leadEvent=period.range==="week"&&event;
    title=leadEvent?astrologyEventTitle(event,lang):focus?astrologyEventTitle(focus,lang):L("Rytmus světel a pomalé pozadí","The lights and a slower background");
    summary=leadEvent?astrologyEventReading(event,lens,lang):focus?aspectReading(focus,lang):phaseText;
    if(focus)layers.push({key:"focus",title:L("Těsná vazba vybraného okamžiku","A close connection at the selected time"),fact:`${astrologyEventTitle(focus,lang)} · ${L("orb","orb")} ${focus.orb.toFixed(2)}° · ${focus.applying?L("sbíhavý","applying"):L("rozbíhavý","separating")}`,text:aspectReading(focus,lang)});
    if(eventLayer)layers.push(eventLayer);
    layers.push({key:"moon",title:L("Krátký rytmus uvnitř celku","A short rhythm within the whole"),fact:`${L(...MOON_NAMES[sky.moon.index])} · ${n("Moon")}: ${sign(moon)}${d.lunar?` · ${astrologyEventTitle(d.lunar,lang)}`:""}`,text:`${phaseText} ${d.lunar?aspectReading(d.lunar,lang):L(...ASTRO_SIGNS[moon.sign].text)}`});
    method=L("Souhrn skládá přesnou vazbu, výraznou změnu období a lunární rytmus. Dlouhé aspekty zůstávají v pozadí; jejich význam se nevynuluje každé ráno.","The reading combines a close aspect, a marked change and lunar rhythm. Slow aspects remain in the background; their significance does not reset every morning.");
    const shared=d.personal&&d.lunar?[d.personal.a,d.personal.b].find(id=>[d.lunar.a,d.lunar.b].includes(id)):null;
    connection=shared?L(`Dvě krátké vrstvy se potkávají u stejného principu: ${n(shared)}. Jeho téma „${L(...ASTRO_PLANETS[shared].theme).toLowerCase()}“ tak propojuje bezprostřední prožitek Měsíce s vědomějším směrem jednání. Čteme je spolu, ne jako dvě oddělené zprávy.`,`Two short layers meet in the same principle: ${n(shared)}. Its theme, “${L(...ASTRO_PLANETS[shared].theme).toLowerCase()}”, connects immediate lunar experience with a more conscious direction. Read them together, not as unrelated messages.`):L(`Lunární vrstva (${L(...MOON_NAMES[sky.moon.index])}) ukazuje, jak se hlavní téma setkává s proměnlivou potřebou a kapacitou. ${phaseText} Pomalé pozadí níže dává tomuto krátkému pohybu širší rámec.`,`The lunar layer (${L(...MOON_NAMES[sky.moon.index])}) places the main theme beside changing needs and capacity. ${phaseText} The slower background below gives this brief movement a wider frame.`);
    const slowAspect=d.background.find(a=>!focus||a.a!==focus.a||a.b!==focus.b);
    const slowPair=slowAspect&&(PAIR_READINGS[`${slowAspect.a}:${slowAspect.b}`]||PAIR_READINGS[`${slowAspect.b}:${slowAspect.a}`]);
    context=`${L(...MOON_NAMES[sky.moon.index])}: ${phaseText} ${slowAspect?L(`V delším pozadí zůstává ${astrologyEventTitle(slowAspect,lang)}. ${L(...slowPair).split(". ")[0]}.`,`The longer background retains ${astrologyEventTitle(slowAspect,lang)}. ${L(...slowPair).split(". ")[0]}.`):L(`Širší rámec nesou Jupiter (${sign(d.slow.find(p=>p.id==="Jupiter"))}) a Saturn (${sign(d.slow.find(p=>p.id==="Saturn"))}): rozšiřování smyslu vedle práce s mezemi.`,`Jupiter (${sign(d.slow.find(p=>p.id==="Jupiter"))}) and Saturn (${sign(d.slow.find(p=>p.id==="Saturn"))}) carry the wider frame: expanding meaning alongside work with limits.`)}`;
  }else if(lens==="hellenistic"){
    const host=d.strongestHost,route=d.hostRoute;
    title=host?L(`Obloha se sbíhá k hostiteli: ${n(host.id)}`,`The sky gathers around a host: ${n(host.id)}`):L("Sedm planet, síť vzájemných opor","Seven planets, a network of support");
    const hostText=host?L(`Ve znameních této planety se nachází ${host.guests.length} ze sedmi tradičních těles. Jejich odlišná témata tak sdílejí prostředí jednoho hostitele. ${L(...ASTRO_PLANETS[host.id].theme)} propojuje více částí obrazu; smysl získává až v návaznosti na další vládce.`,`${host.guests.length} of the seven traditional bodies occupy this ruler's signs. Their different themes share one host. “${L(...ASTRO_PLANETS[host.id].theme)}” links several parts of the image and gains meaning through the next rulers.`):L("Pozornost se rozděluje mezi více hostitelů. Celek nevzniká převahou jedné planety, ale čtením toho, jak si jednotlivé principy poskytují prostředí.","Attention is spread among hosts. The whole emerges by reading how the principles provide settings for one another.");
    summary=`${hostText} ${event?L(`Výrazný předěl v tomto období: ${astrologyEventTitle(event,lang)}.`,`A marked change in this period: ${astrologyEventTitle(event,lang)}.`):""}`;
    layers.push({key:"host",title:L("Hostitelé a jejich návaznost","Hosts and their chain"),fact:host?`${n(host.id)} ← ${host.guests.map(p=>n(p.id)).join(", ")}`:L("Bez jednoho soustředěného hostitele","No concentrated host"),text:hostText,route:route?.route.map(n),tail:route?.cycle.length>1?L(`Řetězec se uzavírá do kruhu: ${route.cycle.map(n).join(" → ")}. V této vrstvě tedy není jediný konečný vládce; jednotlivé principy se odkazují jeden na druhý.`,`The chain closes in a loop: ${route.cycle.map(n).join(" → ")}. This layer has no single final ruler; the principles refer to one another.`):route?.cycle.length===1?L(`Řetězec končí u planety ve vlastním znamení: ${n(route.terminal)}. To je konec této konkrétní návaznosti, nikoli automaticky vládce celého horoskopu.`,`This chain ends in domicile: ${n(route.terminal)}. That ends this particular chain without automatically making it ruler of an entire chart.`):null});
    layers.push({key:"lights",title:L("Jak se vidí obě světla","How the two lights regard each other"),fact:`${n("Sun")}: ${sign(sky.planets[0])} · ${n("Moon")}: ${sign(moon)} · ${d.lights?L(...ASTRO_ASPECTS[d.lights.id].name):L("bez hlavní konfigurace znamení","no major sign configuration")}`,text:d.lights?`${L("Jde o vztah celých znamení, který trvá i mimo přesný úhel.","This is a whole-sign relationship, persisting beyond an exact degree.")} ${aspectReading(d.lights,lang)}`:L("Znamení světel nejsou spojena jednou z pěti zde zobrazených konfigurací. Tradiční obraz odvrácení neznamená poruchu ani špatný den: upozorňuje, že jejich vztah nečteme touto přímou vazbou. Dále sledujeme jejich hostitele.","The lights' signs do not share one of the five configurations shown here. The traditional image of aversion is not a bad-day verdict; this direct connection is absent, so we continue through their hosts.")});
    if(eventLayer)layers.push(eventLayer);
    method=L("Začínáme vztahy znamení a jejich hostiteli. Počet hostů je způsob orientace v této společné obloze, ne tradiční výpočet vládce narození, sekty nebo celkové síly.","We begin with sign relationships and hosts. Guest counts orient this shared-sky reading; they are not a natal ruler, sect or total-strength calculation.");
    connection=L(`Slunce i Měsíc se v této obloze opírají o hostitele: ${n(sky.planets[0].ruler)} a ${n(moon.ruler)}. ${sky.planets[0].ruler===moon.ruler?"I jejich odlišné role tedy sdílejí jeden zdroj prostředí.":"Jejich odlišné role vstupují do dvou různých prostředí; právě návaznost vládců ukazuje, kde se mohou propojit."} Přechod znamením může tuto síť změnit i bez přesného stupňového aspektu.`,`The Sun and Moon have hosts here: ${n(sky.planets[0].ruler)} and ${n(moon.ruler)}. ${sky.planets[0].ruler===moon.ruler?"Their different roles share a setting.":"Their different settings can be connected by following their rulers."} A sign crossing can alter this network without an exact degree aspect.`);
    context=d.lights?L(`Vztah světel doplňuje ${L(...ASTRO_ASPECTS[d.lights.id].name).toLowerCase()} celých znamení (${sign(sky.planets[0])} — ${sign(moon)}). Směr a bezprostřední potřebu tak čteme v této konfiguraci i skrze uvedenou síť hostitelů.`,`The lights add a whole-sign ${L(...ASTRO_ASPECTS[d.lights.id].name).toLowerCase()} (${sign(sky.planets[0])} — ${sign(moon)}). Direction and immediate need are read through this configuration and the host network.`):L(`Slunce (${sign(sky.planets[0])}) a Měsíc (${sign(moon)}) nemají hlavní vazbu celých znamení. Jejich propojení proto dále hledáme skrze hostitele; jedno téma samo tento celek nevysvětluje.`,`The Sun (${sign(sky.planets[0])}) and Moon (${sign(moon)}) have no major whole-sign connection. We continue through their hosts; one theme alone does not explain the whole.`);
  }else{
    const q=tithiQuality(sky.jyotish.tithi),paksha=sky.jyotish.waxing?"Šukla pakša":"Krišna pakša";
    title=`${q.name} · ${L(...q.title)}`;
    summary=`${L(...q.text)} ${sky.jyotish.waxing?L("V přibývající polovině cyklu tento obraz čteme jako postupné rozvíjení.","In the waxing half, read this image through gradual development."):L("V ubývající polovině cyklu tento obraz čteme skrze vstřebání a rozlišení.","In the waning half, read this image through assimilation and discernment.")} ${event&&event.type==="station"?L(`Vedle lunárního rytmu stojí výrazný obrat: ${astrologyEventTitle(event,lang)}.`,`Alongside the lunar rhythm stands a marked station: ${astrologyEventTitle(event,lang)}.`):""}`;
    layers.push({key:"tithi",title:L("Povaha lunárního času","The quality of lunar time"),fact:`${paksha} · ${sky.jyotish.tithiName} · ${sky.jyotish.fortnightDay}. tithi · ${q.name}`,text:`${L(...q.text)} ${L("Pět názvů se opakuje třikrát v každé půli lunace. Čas zde získává kvalitu skrze vztah Slunce a Měsíce, nikoli den v občanském kalendáři.","The five names repeat three times within each half-lunation. Time takes its quality from the Sun–Moon relationship, not the civil calendar date.")}`});
    layers.push({key:"mansion",title:L("Místo Měsíce a jeho opora","The Moon's place and support"),fact:`${sky.jyotish.name} · ${L("páda","pada")} ${sky.jyotish.pada} · ${L("raši","rashi")}: ${sign(moon)}`,text:L(`Tithi a nakšatra zachycují dvě různé věci: vzájemný pohyb světel a místo Měsíce ve hvězdném kruhu. Vládce jeho raši je ${n(moon.ruler)}. Sledujeme tak současně rytmus, prostředí i princip, který mu poskytuje oporu; jednu značku nepovažujeme za výklad celého dne.`,`Tithi and nakshatra describe different things: the lights' relative motion and the Moon's stellar place. Its rashi ruler is ${n(moon.ruler)}. Rhythm, setting and support are read together; no single marker interprets a whole day.`),route:d.moonRoute.route.map(n)});
    if(eventLayer)layers.push(eventLayer);
    method=L("Tato vrstva spojuje tithi, pakšu, nakšatru a siderická znamení. Názvy kvalit pocházejí z Brihat samhity; kontemplativní významy jsou současné čtení tanmay. Západní aspekty zde nepoužíváme jako dršti.","This layer combines tithi, paksha, nakshatra and sidereal signs. Quality names come from Brihat Samhita; contemplative meanings are contemporary tanmay readings. Western aspects are not used as drishti.");
    const nextTithi=period.events.find(e=>e.type==="tithi"&&e.time>new Date(sky.date).getTime());
    connection=nextTithi?L(`Kvalita ${q.name} se během vybraného období dále promění v ${tithiQuality(nextTithi.to).name}. Nakšatra ${sky.jyotish.name} a raši ${sign(moon)} mezitím nesou vlastní hranice. Celek proto není jedna vlastnost dne: je to překrytí několika rytmů, které se nemění současně.`,`Within this period, ${q.name} next becomes ${tithiQuality(nextTithi.to).name}. The mansion ${sky.jyotish.name} and rashi ${sign(moon)} have their own boundaries. The whole is an overlap of rhythms changing at different times, not one quality assigned to a day.`):L(`Kvalita ${q.name}, nakšatra ${sky.jyotish.name} a raši ${sign(moon)} skládají různé míry času. Žádnou z nich nepřeneseme automaticky na celý kalendářní den; jejich návaznost je patrná při posunu času.`,`The quality ${q.name}, mansion ${sky.jyotish.name} and rashi ${sign(moon)} combine different measures of time. None is automatically assigned to a whole civil day; moving the clock reveals their sequence.`);
    const guru=d.slow.find(p=>p.id==="Jupiter"),shani=d.slow.find(p=>p.id==="Saturn");
    context=L(`Delší rámec: Guru — ${sign(guru)}, Šani — ${sign(shani)}. ${shani.ruler==="Jupiter"?"Šani je navíc v Guruově znamení: obraz trpělivé práce se opírá o smysl a učení.":guru.ruler==="Saturn"?"Guru je navíc v Šaniho znamení: obraz růstu hledá oporu v čase a konkrétní odpovědnosti.":"Učení a šíře pohledu stojí vedle trpělivosti a nesených důsledků."} Tithi mění krátký rytmus uvnitř tohoto pomalejšího obrazu.`,`The longer frame: Guru — ${sign(guru)}, Shani — ${sign(shani)}. ${shani.ruler==="Jupiter"?"Shani also occupies Guru's sign: patient work draws on meaning and learning.":guru.ruler==="Saturn"?"Guru also occupies Shani's sign: growth seeks support in time and responsibility.":"Learning and breadth stand beside patience and consequences."} Tithi changes the short rhythm within this slower image.`);
  }
  const background=d.background.map(a=>({key:`${a.a}-${a.b}`,title:astrologyEventTitle(a,lang),fact:a.wholeSign?L("Vztah celých znamení","Whole-sign relationship"):`${L("orb","orb")} ${a.orb.toFixed(2)}° · ${L("začátek → konec období","period start → end")} ${a.startOrb.toFixed(2)}° → ${a.endOrb.toFixed(2)}°`,text:aspectReading(a,lang)}));
  const resources=d.dignified.map(p=>`${n(p.id)}: ${sign(p)} · ${L(...ASTRO_DIGNITIES[p.dignity].name)}`);
  return {title,summary,context,method,connection,layers,background,slow:d.slow,resources,
    backgroundText:lens==="jyotish"?L("Guru a Šani se pohybují pomaleji než lunární ukazatele. Jeden nese v tradiční symbolice učení a rozšíření, druhý čas a nesené důsledky. Jejich siderická znamení tvoří širší rámec; tithi uvnitř něj mění krátký rytmus. Zvláštní dršti ani daši tato vrstva nevyhodnocuje.","Guru and Shani move more slowly than the lunar indicators. One carries learning and expansion, the other time and consequences. Their sidereal signs form a wider frame within which tithi changes the short rhythm. This layer does not evaluate special drishti or dashas."):L("Tyto polohy a vazby jsou pomalejší vrstvou obrazu. Pro konkrétní den je čteme spolu s rychlým děním; samotná přítomnost dlouhého aspektu z něj nedělá dnešní novou událost.","These positions and connections form a slower layer. For one day, read them alongside faster changes; a long aspect is not a new event simply because it is present today.")};
}
