// Educational suggestions, not phase-based exercise prescriptions.
export const CYCLE_GUIDE = {
  menstrual: {name:["Menstruační fáze","Menstrual phase"],about:["Probíhá krvácení. Menstruace je zároveň začátkem folikulární fáze; pro přehled ji ukazujeme samostatně.","Bleeding is taking place. Menstruation is also the start of the follicular phase; it is shown separately here."],woman:["Pokud je ti příjemně, běžný pohyb může pokračovat. Při křečích zkus teplo, procházku nebo jemné protažení. Intenzitu sniž podle potíží, ne automaticky podle kalendáře.","Continue normal movement if comfortable. For cramps, try warmth, a walk or gentle stretching. Adjust intensity to symptoms, not automatically to the calendar."],partner:["Zeptej se, zda pomůže teplo, jídlo, převzetí úkolu nebo prostor. Nabídni klidnější variantu společného plánu a respektuj odpověď.","Ask whether warmth, food, taking over a task or some space would help. Offer a quieter plan and respect the answer."],idea:["Procházka nebo čaj bez spěchu","An unhurried walk or tea"]},
  follicular: {name:["Folikulární fáze","Follicular phase"],about:["Před ovulací dozrávají folikuly. Délka této části cyklu se může měnit; více energie není pravidlem pro každou ženu.","Follicles develop before ovulation. The length of this phase can vary; increased energy is not universal."],woman:["Jestli se cítíš dobře, drž svůj obvyklý silový či vytrvalostní plán. Novou dovednost nebo náročnější výlet vybírej podle chuti a zotavení.","If you feel well, follow your usual strength or endurance plan. Choose a new skill or a longer outing according to interest and recovery."],partner:["Nabídni něco nového, ale nepředpokládej, že musí mít více energie. Domluvte si délku aktivity i možnost změnit plán.","Offer something new without assuming extra energy. Agree on the duration and an option to change plans."],idea:["Vyzkoušet společně něco nového","Try something new together"]},
  ovulatory: {name:["Možné ovulační období","Possible ovulatory phase"],about:["Ovulace je uvolnění vajíčka. Z kalendáře ji nelze potvrdit a nemusí přijít uprostřed cyklu. Tento údaj neoznačuje plodné ani bezpečné dny.","Ovulation is the release of an egg. A calendar cannot confirm it, and it need not happen mid-cycle. This does not identify fertile or safe days."],woman:["Pohyb, setkání i intimitu vybírej podle vlastního pocitu. Kalendář není důvod přidávat zátěž ani podstupovat osobní rekord.","Choose movement, social time and intimacy according to how you feel. A calendar is no reason to increase load or attempt a personal best."],partner:["Ptej se na přání a souhlas. Vyšší chuť na kontakt nebo sex není povinnost ani spolehlivý znak fáze.","Ask about wishes and consent. Greater interest in company or sex is neither an obligation nor a reliable sign of a phase."],idea:["Rande podle společné chuti","A date you both feel like"]},
  luteal: {name:["Luteální fáze","Luteal phase"],about:["Po ovulaci následuje luteální fáze. U některých žen se před menstruací objevují potíže PMS; jejich přítomnost i intenzita jsou individuální.","The luteal phase follows ovulation. Some people experience premenstrual symptoms; their presence and intensity vary."],woman:["Udržuj pravidelný spánek, jídlo a pohyb. Při únavě nebo potížích uprav délku a náročnost tréninku. Zapisuj vlastní zkušenost, ať vidíš svůj vzorec.","Keep sleep, meals and movement regular. Adjust session length and effort when tired or symptomatic. Track your own experience to notice patterns."],partner:["Naslouchej bez vysvětlování pocitů hormony. Nabídni konkrétní pomoc a plán s menším časovým tlakem, pokud o něj stojí.","Listen without explaining feelings away as hormones. Offer practical help and a less time-pressured plan if wanted."],idea:["Společná večeře a volný večer","Dinner together and an unhurried evening"]}
};
export function cyclePhase(doc, summary, today) {
  if(!summary?.day || doc.mode === "paused") return {id:null,basis:"unknown"};
  if(summary.observedBleeding || ["light","medium","heavy"].includes(doc.days?.[today]?.flow)) return {id:"menstrual",basis:"recorded"};
  if(summary.reason!=="estimate" || !summary.next || summary.day>summary.median) return {id:null,basis:"unknown"};
  const approx=summary.median-14;
  return {id:summary.day<approx-2?"follicular":summary.day<=approx+2?"ovulatory":"luteal",basis:"estimated"};
}
export const CYCLE_SOURCES=[
  ["Office on Women's Health · cyklus","https://womenshealth.gov/menstrual-cycle/your-menstrual-cycle"],
  ["NHS · bolest při menstruaci","https://www.nhs.uk/conditions/period-pain/"],
  ["NHS · PMS","https://www.nhs.uk/conditions/pre-menstrual-syndrome/"]
];
