// Original editorial. Physiology, everyday invitations and poetic metaphor
// stay separate; none of these strings infers a person's state from a date.
export const CYCLE_ORDER=['menstrual','follicular','ovulatory','luteal'];
const pair=(cs,en)=>[cs,en];
export const CYCLE_DEPTH={
  menstrual:{
    short:pair('Menstruační fáze','Menstrual phase'),title:pair('Místo pro nový začátek','Room for a new beginning'),
    hormones:pair('Na přelomu cyklů jsou estradiol a progesteron nízko. FSH pomáhá rozběhnout další skupinu folikulů. Menstruace je už začátkem nové folikulární fáze.','Around the cycle boundary, estradiol and progesterone are low. FSH supports another group of follicles. Menstruation already belongs to the new follicular phase.'),
    uterus:pair('Funkční vrstva děložní sliznice se odlučuje. Děloha při tom může mít stahy. Krvácení není očista od toxinů; je to obnova tkáně.','The functional uterine lining sheds, sometimes with uterine contractions. Bleeding is tissue renewal, not a detoxification process.'),
    woman:pair('Začni u skutečné potřeby. Pokud máš bolesti nebo jsi unavená, může pomoci teplo a méně povinností. Je-li ti dobře, nemusíš se nutit do ústraní.','Begin with what you actually need. With pain or fatigue, warmth and fewer demands may help. If you feel well, there is no need to retreat.'),
    partner:pair('Nabídni jednu konkrétní pomoc, kterou sám dotáhneš. Třeba uvařit, nakoupit nebo převzít večerní úkol. A pak se zeptej, jestli chce společnost, dotek, nebo klid.','Offer one concrete task you can take care of completely: a meal, shopping or an evening chore. Then ask whether she would like company, touch or quiet.'),
    care:[
      {id:'move',name:pair('Pohyb a odpočinek','Movement and rest'),woman:pair('Zkus pár minut chůze nebo jemného pohybu a všimni si odpovědi těla. Když se potíže zhoršují, změň plán. Ani odpočinek, ani běžný trénink nemusíš ospravedlňovat.','Try a few minutes of walking or gentle movement and notice your response. If symptoms worsen, change the plan. Neither rest nor your usual training needs a justification.'),partner:pair('Navrhni krátkou cestu s možností kdykoli se vrátit. Není třeba ji rozhýbávat, když chce odpočívat, ani brzdit, když se cítí dobře.','Suggest a short outing with an easy return. You need neither push her to move when she wants rest nor hold her back when she feels well.')},
      {id:'food',name:pair('Jídlo a péče','Food and care'),woman:pair('Nech jídlo být oporou: něco pravidelného, sytého a dostupného. Teplé jídlo může být příjemné, ale není to povinnost ani hormonální předpis.','Let food support you: regular, satisfying and accessible. Warm food may feel comforting, but it is neither a requirement nor a hormonal prescription.'),partner:pair('Zeptej se, na co má chuť, a nabídni jídlo i úklid po něm. Výživa nemusí být další věc, kterou musí naplánovat sama.','Ask what she would enjoy, and offer to prepare it and clear up. Food need not become another thing she has to organise.')},
      {id:'mind',name:pair('Prožitek a psychika','Experience and feelings'),woman:pair('Co cítím v těle a co si o tom právě říkám? Zkus tyto dvě věci rozlišit. Únava může potřebovat spánek; smutek může potřebovat být slyšen.','What do I feel in my body, and what am I telling myself about it? Try separating the two. Tiredness may need sleep; sadness may need to be heard.'),partner:pair('Naslouchej tomu, co skutečně říká. Nepřekládej její nespokojenost automaticky jako následek cyklu. Může být citlivější a současně mít pravdu o něčem důležitém.','Listen to what she actually says. Do not translate dissatisfaction automatically into a cycle effect. She can be sensitive and still be right about something important.')},
      {id:'plan',name:pair('Plány a hranice','Plans and boundaries'),woman:pair('Vyber jednu věc, kterou lze dnes zjednodušit. Zbytek nemusíš rušit předem. Nech si možnost rozhodnout podle skutečného dne.','Choose one thing you could simplify today. You need not cancel everything in advance. Keep room to decide according to the actual day.'),partner:pair('Domluvte se, co opravdu musí proběhnout a co lze odložit. Pomoc znamená nést část odpovědnosti, ne jen čekat na další pokyn.','Agree what truly needs doing and what can wait. Helping means carrying some responsibility, not only waiting for the next instruction.')},
      {id:'bond',name:pair('Blízkost a vztah','Closeness and relationship'),woman:pair('Můžeš chtít náruč i samotu. Zkus říct: „Pomohlo by mi, kdybys…“ a doplnit jedinou konkrétní věc.','You may want an embrace or solitude. Try saying, “It would help if you…” and add one concrete thing.'),partner:pair('„Mám s tebou chvíli být, něco převzít, nebo ti nechat prostor?“ Odpověď přijmi bez osobního výkladu odmítnutí.','“Would you like me to stay with you, take something on, or give you space?” Receive the answer without turning it into personal rejection.')}
    ],
    symbol:{season:pair('Zima','Winter'),day:pair('Noc','Night'),direction:pair('Sever','North'),archetype:pair('Strážkyně prahu','Keeper of the threshold'),
      text:pair('V této autorské mapě je lůno obrazem prostoru, který nemusí nic dokazovat. Zimní země není prázdná: drží kořeny, vodu i možnost dalšího života. Nemusíš tento obraz cítit doslova v děloze. Může být prostým dovolením na chvíli nenabízet světu žádný výsledek.','In this original map, the womb is an image of space that need not prove itself. Winter ground is not empty: it holds roots, water and the possibility of life. You need not feel this image literally in your uterus. It can simply give permission to offer the world no result for a while.'),
      shadow:pair('Odpočinek se někdy mění v opuštění sebe. Rozliš: potřebuji samotu, nebo tiše čekám, zda si někdo všimne, že mi není dobře?','Rest can sometimes become abandoning yourself. Distinguish: do I need solitude, or am I silently waiting for someone to notice I am not well?'),
      question:pair('Co mohu odložit, aniž bych odložila samu sebe?','What can I put down without putting myself aside?'),
      ritual:pair('Polož chodidla na zem. Pokud je ti to příjemné, dej dlaň na břicho nebo hrudník. Třikrát volně vydechni a pojmenuj jedinou věc, kterou dnes nemusíš nést.','Place your feet on the floor. If comfortable, put a hand on your abdomen or chest. Exhale freely three times and name one thing you need not carry today.'),
      storyTitle:pair('Inaniny brány','Inana’s gates'),
      story:pair('V sumerském příběhu Inana při sestupu prochází sedmi branami a ztrácí znaky svého postavení. Tady si z příběhu vypůjčujeme motiv odkládání rolí. Je to naše kontemplativní četba, nikoli starověký výklad menstruace: kým jsem, když nemusím být užitečná, silná ani obdivovaná?','In the Sumerian story, Inana passes seven gates on her descent and loses the signs of her standing. Here we borrow the motif of setting roles aside. This is our contemplative reading, not an ancient interpretation of menstruation: who am I when I need not be useful, strong or admired?'),source:'inana'},
    shared:pair('Čaj a jedna věc, kterou dnes nemusíme','Tea and one thing we can put down')
  },
  follicular:{
    short:pair('Folikulární fáze','Follicular phase'),title:pair('Růst vlastním tempem','Growing at your own pace'),
    hormones:pair('Ve vaječníku dozrávají folikuly; jeden obvykle převezme hlavní roli. Jeho buňky vytvářejí více estradiolu. Délka této části cyklu se může měnit.','Follicles develop in the ovary; usually one becomes dominant. Its cells produce more estradiol. This part of the cycle can vary in length.'),
    uterus:pair('Estradiol podporuje obnovu a růst děložní sliznice po krvácení. Jde o biologický proces, ne pokyn, že musíš být právě teď produktivnější.','Estradiol supports the rebuilding and growth of the uterine lining after bleeding. This is a biological process, not an instruction to become more productive.'),
    woman:pair('Pokud přichází chuť něco zkusit, dej jí malý konkrétní prostor. Nemusíš z ní hned udělat závazek na celý měsíc. A jestli nepřichází, ani to není selhání cyklu.','If curiosity arrives, give it a small, concrete space. It need not become a month-long commitment. If it does not arrive, your cycle has not failed.'),
    partner:pair('Ptej se na její vlastní zájem. Nabídni společné objevování bez očekávání, že právě teď zvládne více. Radost z nápadu nemusí znamenat souhlas se vším kolem něj.','Ask about her own interests. Offer to explore something together without expecting extra capacity. Enjoying an idea does not mean agreeing to everything around it.'),
    care:[
      {id:'move',name:pair('Pohyb a odpočinek','Movement and rest'),woman:pair('Navazuj na svůj skutečný trénink, spánek a zotavení. Novou dovednost zkus v takové dávce, po které zbude chuť se vrátit.','Build on your actual training, sleep and recovery. Try a new skill in a dose that leaves you wanting to return.'),partner:pair('Vyberte aktivitu, kde můžete být oba začátečníci. Soutěž a výkon přidávejte jen tehdy, když je chcete oba.','Choose an activity where you can both be beginners. Add competition and performance only if you both want them.')},
      {id:'food',name:pair('Jídlo a péče','Food and care'),woman:pair('Drž běžná jídla, dostatek tekutin a prostor pro hlad i sytost. Pro tuto fázi není potřeba zvláštní očista ani omezení potravin.','Keep regular meals, hydration and space to notice hunger and fullness. This phase calls for no special cleanse or food restriction.'),partner:pair('Můžete společně objevit nový recept. Obohacení patří do chuti a zážitku, ne do kontroly jejího jídla.','You could discover a new recipe together. Enrichment belongs in flavour and experience, not in monitoring her food.')},
      {id:'mind',name:pair('Prožitek a psychika','Experience and feelings'),woman:pair('Všimni si rozdílu mezi živou zvědavostí a tlakem dohnat, co jsi minule nestihla. Který malý pokus je opravdu tvůj?','Notice the difference between curiosity and pressure to catch up. Which small experiment is truly yours?'),partner:pair('Ptej se, co ji na nápadu přitahuje, ještě než začneš řešit provedení. Nejprve porozumění, potom plán.','Ask what draws her to an idea before solving how to make it happen. Understanding first, planning second.')},
      {id:'plan',name:pair('Plány a hranice','Plans and boundaries'),woman:pair('Vyber jeden pokus a konkrétní první krok. Zbytek může zůstat možností. Budoucí já nemusí splnit všechny dnešní nápady.','Choose one experiment and a first step. Everything else can remain a possibility. Your future self need not carry out every idea you have today.'),partner:pair('Domluvte si délku, náklady i možnost skončit dřív. Dobrá společná novost nechává oběma volbu.','Agree on time, cost and the option to finish early. A good shared new experience leaves both people a choice.')},
      {id:'bond',name:pair('Blízkost a vztah','Closeness and relationship'),woman:pair('Řekni partnerovi něco, co tě právě zajímá a co o tobě možná ještě neví. Ne jako úkol, jen jako otevřené dveře.','Tell your partner about something that interests you and they may not know about you. Offer an open door rather than a task.'),partner:pair('„Co bych s tebou mohl poznat novýma očima?“ Nech ji také měnit názor; zájem není slib.','“What could I see with fresh eyes alongside you?” Leave room for her to change her mind; interest is not a promise.')}
    ],
    symbol:{season:pair('Jaro','Spring'),day:pair('Svítání','Dawn'),direction:pair('Východ','East'),archetype:pair('Objevitelka','Explorer'),
      text:pair('Jaro v této mapě není příkaz rozkvést. Je obrazem malého výhonku, který nejprve hledá světlo. Moudrost lůna tu znamená umět dát vznikajícímu tvaru čas. Něco nového může být křehké, nedokončené a přesto pravdivé.','Spring in this map is not an order to bloom. It is the image of a small shoot seeking light. Womb wisdom here means giving an emerging form time. Something new can be fragile, unfinished and still true.'),
      shadow:pair('Nový začátek může být i útěkem před nedokončeným. Co chci opravdu pěstovat a co mě jen na chvíli oslnilo?','A new beginning can also be an escape from unfinished things. What do I truly want to grow, and what only dazzled me for a moment?'),
      question:pair('Čemu chci dát první malý souhlas?','What deserves my first small yes?'),
      ritual:pair('Otevři okno nebo na chvíli vyjdi ven. Vyber si jednu živou drobnost, kterou dřív tvůj pohled míjel. Pak udělej stejně malý první krok v něčem vlastním.','Open a window or step outside. Notice one living detail you usually overlook. Then take an equally small first step in something of your own.'),
      storyTitle:pair('Persefonin návrat','Persephone’s return'),
      story:pair('Homérský hymnus vypráví o Démétér, ztrátě dcery a jejich návratu k sobě. Obnovení růstu následuje po setkání a dohodě. Pro naši mapu je to otázka: co se ve mně může vrátit k životu, když pro to vzniknou podmínky? Příběh nezakládá biologický kalendář čtyř archetypů.','The Homeric hymn tells of Demeter, the loss of her daughter and their reunion. Growth returns after reunion and an agreement. Our map asks: what might return to life in me when the conditions allow it? The story does not establish a biological calendar of four archetypes.'),source:'demeter'},
    shared:pair('Malý společný objev','A small discovery together')
  },
  ovulatory:{
    short:pair('Ovulační fáze','Ovulatory phase'),title:pair('Setkání bez ztráty sebe','Meeting without losing yourself'),
    hormones:pair('Vzestup estradiolu předchází výrazné vlně LH. Ta spouští děje vedoucí k uvolnění vajíčka. Progesteron pak začíná stoupat. Kalendář tuto událost neměří.','Rising estradiol precedes a pronounced LH surge, triggering events that release an egg. Progesterone then begins to rise. A calendar does not measure this event.'),
    uterus:pair('Děložní sliznice je ve fázi růstu. Hlen děložního hrdla může být pod vlivem estrogenu řidší; samotný pocit ani tento přehled nepotvrzují ovulaci.','The uterine lining is growing. Cervical mucus may become thinner under oestrogen; neither a feeling nor this view confirms ovulation.'),
    woman:pair('Blízkost může mít mnoho podob. Vyber si takovou, ve které jsi přítomná a svobodná. Chuť na společnost, sex nebo výkon se nedá vyčíst z čísla dne.','Closeness takes many forms. Choose one in which you feel present and free. A cycle day cannot tell you your desire for company, sex or performance.'),
    partner:pair('Vnímej ji jako člověka, ne jako předpověď zvýšené chuti na kontakt. Zajímej se o její dnešní ano i ne a přines do setkání také vlastní pravdivost.','Meet a person, not a prediction of greater desire for contact. Be interested in her present yes and no, and bring your own honesty to the encounter.'),
    care:[
      {id:'move',name:pair('Pohyb a odpočinek','Movement and rest'),woman:pair('Můžeš se opřít o běžný plán. Pokud zkusíš něco intenzivního, ať důvodem je připravenost a chuť, ne očekávaný hormonální vrchol.','You can follow your usual plan. If you try something intense, let readiness and interest be the reason, not an expected hormonal peak.'),partner:pair('Při společném pohybu se slaďte podle skutečného tempa. Její fáze není důvod přidávat náročnost ani porovnávat výsledky.','Match your shared movement to your actual pace. Her phase is no reason to increase difficulty or compare results.')},
      {id:'food',name:pair('Jídlo a péče','Food and care'),woman:pair('Jez tak, aby jídlo podporovalo tvůj den. Není potřeba hledat potravinu, která tuto fázi „zapne“ nebo vylepší.','Eat in a way that supports your day. There is no need to find a food that switches on or improves this phase.'),partner:pair('Udělejte z jídla chvíli společné pozornosti. Odložte na chvíli telefon a nechte si čas skutečně ochutnat.','Let a meal become a moment of shared attention. Put your phones aside and take time to taste it.')},
      {id:'mind',name:pair('Prožitek a psychika','Experience and feelings'),woman:pair('Kde říkám ano z radosti a kde proto, abych nezklamala? Otevřenost může mít pevnou hranici.','Where does my yes come from delight, and where from not wanting to disappoint? Openness can have a firm boundary.'),partner:pair('Zajímej se o její radost i nejistotu. Pochvala nemusí mířit jen na vzhled: můžeš si všimnout odvahy, tvořivosti nebo způsobu, jak je s tebou.','Be interested in her delight and uncertainty. Appreciation need not focus only on appearance: notice courage, creativity or the way she is with you.')},
      {id:'plan',name:pair('Plány a hranice','Plans and boundaries'),woman:pair('Před společenským plánem si nech okamžik na vlastní odpověď. Kolik kontaktu chci a jak se pak vrátím k sobě?','Before a social plan, give yourself a moment to answer. How much contact do I want, and how will I return to myself afterwards?'),partner:pair('Naplánujte setkání, které dává prostor oběma. Souhlas s večeří není automaticky souhlas s dalším programem nebo intimitou.','Plan a meeting that leaves room for both of you. Agreeing to dinner does not automatically mean agreeing to more plans or intimacy.')},
      {id:'bond',name:pair('Blízkost a vztah','Closeness and relationship'),woman:pair('Zkus vyjádřit přání bez nápověd, které musí druhý rozluštit. „Dnes bych s tebou chtěla…“ je pozvání, ne smlouva.','Try expressing a wish without clues the other person must solve. “Today I would like to…” is an invitation, not a contract.'),partner:pair('„Jaký druh blízkosti by ti dnes byl příjemný?“ Domluvte si i jednoduchý způsob, jak zastavit nebo změnit směr bez vysvětlování.','“What kind of closeness would feel good today?” Agree on an easy way to stop or change direction without needing to explain.')}
    ],
    symbol:{season:pair('Léto','Summer'),day:pair('Poledne','Noon'),direction:pair('Jih','South'),archetype:pair('Tvůrkyně spojení','Weaver of connection'),
      text:pair('Letní obraz je plnost, která se může nabídnout a nemusí se rozdat. Lůno tu představuje schopnost něco nést: vztah, nápad, ticho nebo čin. Nejde o povinnost mateřství ani o hodnotu založenou na plodnosti. Tvoření má mnoho podob a některé nikdo další neuvidí.','The summer image is fullness that can be offered without being given away. The womb represents the capacity to hold a relationship, an idea, silence or an action. It is no duty of motherhood or value based on fertility. Creation takes many forms, some unseen by anyone else.'),
      shadow:pair('Když se cítím viděná, nezapomínám na to, co sama vidím a chci? Dar se může změnit v sebeopuštění, když za něj tajně čekám přijetí.','When I feel seen, do I forget what I see and want? A gift can become self-abandonment when I secretly exchange it for acceptance.'),
      question:pair('Co chci sdílet a co má zůstat moje?','What do I want to share, and what should remain mine?'),
      ritual:pair('Posaďte se na chvíli proti sobě. Každý řekne jednu věc, kterou na druhém dnes opravdu vidí, a jedno přání. Odpověď může být ano, ne nebo jinak.','Sit facing each other for a moment. Each names one thing they truly notice in the other and one wish. The answer may be yes, no or something different.'),
      storyTitle:pair('Zahrada s otevřenou bránou','A garden with an open gate'),
      story:pair('Autorský obraz: zahradnice otevře bránu a nabídne plody. Neodstraní však plot, kořeny ani svůj vlastní stůl. Pohostinnost nepotřebuje ztrátu hranic. Co ze své plnosti chci nabídnout tak, abych u toho zůstala doma i sama v sobě?','An original image: a gardener opens the gate and offers fruit. She does not remove the fence, the roots or her own table. Hospitality need not lose its boundaries. What can I offer from my fullness while remaining at home in myself?'),source:null},
    shared:pair('Rande s prostorem pro ano i ne','A date with room for yes and no')
  },
  luteal:{
    short:pair('Luteální fáze','Luteal phase'),title:pair('Rozlišit, co si nesu dál','Choosing what to carry onward'),
    hormones:pair('Žluté tělísko vzniklé z folikulu vytváří hlavně progesteron a také estradiol. Pokud se nerozvíjí těhotenství, jeho činnost později klesá a hladiny těchto hormonů se snižují.','The corpus luteum formed from the follicle produces mainly progesterone and also estradiol. Without a developing pregnancy, its activity later declines and these hormone levels fall.'),
    uterus:pair('Progesteron mění děložní sliznici směrem k sekreční fázi. S poklesem hormonální podpory se připravuje další krvácení. Jak se při tom cítíš, zůstává individuální.','Progesterone shifts the uterine lining towards its secretory phase. Falling hormonal support precedes the next bleed. How you feel remains individual.'),
    woman:pair('Pokud se zmenšuje tvoje kapacita, zkus dříve pojmenovat potřebu. Zároveň můžeš mít obyčejný dobrý den. Vlastní opakované záznamy řeknou více než příběh, který se o této fázi vypráví.','If your capacity feels smaller, try naming the need sooner. You may also simply have a good day. Your repeated records tell you more than a story about this phase.'),
    partner:pair('Neshazuj její téma jako „jen hormony“. Můžeš pomoci ubrat tlak a mluvit konkrétněji. Pokud je rozhovor příliš napjatý, domluvte si pauzu i čas, kdy se k němu vrátíte.','Do not dismiss her concern as “just hormones”. Help reduce pressure and be specific. If a conversation becomes too tense, agree on a pause and a time to return.'),
    care:[
      {id:'move',name:pair('Pohyb a odpočinek','Movement and rest'),woman:pair('Při únavě zkrať délku nebo náročnost, ne nutně celý pohyb vynechávej. Když se cítíš dobře, není důvod rušit fungující plán jen podle fáze.','When tired, reduce duration or intensity without necessarily giving up movement. If you feel well, there is no reason to cancel a working plan because of the phase alone.'),partner:pair('Nabídni variantu plánu s menším tlakem na čas. Respektuj i rozhodnutí pokračovat v běžné aktivitě.','Offer a version of the plan with less time pressure. Respect a decision to continue with the usual activity too.')},
      {id:'food',name:pair('Jídlo a péče','Food and care'),woman:pair('Všímej si hladu, spánku a toho, co ti dělá dobře. Pravidelné jídlo může být jednodušší oporou než přísná pravidla. Chuť na určité jídlo není morální selhání.','Notice hunger, sleep and what feels supportive. Regular meals can be simpler support than strict rules. Wanting a particular food is not a moral failure.'),partner:pair('Pomoz, aby běžná péče byla dostupná. Nakup nebo připrav jídlo bez komentářů k její chuti a bez nevyžádaných výživových rad.','Help make ordinary care accessible. Shop or prepare food without comments on her appetite or unsolicited nutrition advice.')},
      {id:'mind',name:pair('Prožitek a psychika','Experience and feelings'),woman:pair('Odděl situaci, prožitek a reakci: co se stalo, co mě zabolelo, co potřebuji udělat jinak? Citlivost nemusíš popírat ani jí předat všechna rozhodnutí.','Separate the situation, feeling and response: what happened, what hurt, what do I need to do differently? You need neither deny sensitivity nor let it make every decision.'),partner:pair('Zopakuj vlastními slovy, čemu jsi porozuměl, a teprve potom nabídni řešení. Přijetí jejího prožitku neznamená, že musíte souhlasit se všemi výklady.','Reflect back what you understood before offering a solution. Accepting her experience does not mean agreeing with every interpretation.')},
      {id:'plan',name:pair('Plány a hranice','Plans and boundaries'),woman:pair('Podívej se na rozdělané závazky. Co chci dokončit, co upravit a co pustit? Rozhodnutí můžeš opřít o skutečné důvody a ověřit je i v jiný den.','Look at your commitments. What do I want to finish, adjust or release? Ground decisions in actual reasons and revisit them on another day too.'),partner:pair('Vezměte jeden opakovaný zdroj tření a změňte jednu praktickou věc. Třeba kdo vaří, kdy odpočíváte nebo jak oznamujete změnu plánu.','Choose one recurring source of friction and change one practical thing: who cooks, when you rest or how you communicate a change of plan.')},
      {id:'bond',name:pair('Blízkost a vztah','Closeness and relationship'),woman:pair('„Když se stane…, cítím…, pomohlo by mi…“ Stačí jedna situace. Než se pustíte do celého vztahu, ověřte si, že na rozhovor máte prostor oba.','“When… happens, I feel…, and it would help if…” One situation is enough. Before addressing the whole relationship, check that you both have room for the conversation.'),partner:pair('„Chceš teď vyslechnout, pomoci, nebo se k tomu vrátit v domluvený čas?“ Držte se tématu a nepoužívejte kalendář jako vysvětlení toho druhého.','“Would you like listening, help, or to return at an agreed time?” Stay with the issue instead of using the calendar to explain the other person.')}
    ],
    symbol:{season:pair('Podzim','Autumn'),day:pair('Soumrak','Dusk'),direction:pair('Západ','West'),archetype:pair('Rozlišující','One who discerns'),
      text:pair('Podzimní obraz nese sklizeň i třídění. Moudrost dělohy zde není tajný hlas, který má vždy pravdu. Je pozváním ptát se: čemu dál dávám prostor a co už živím jen ze zvyku? Něco může dozrát, něco zůstat nedokončené a něco se stát kompostem pro jiný začátek.','The autumn image holds harvest and sorting. Uterine wisdom here is no secret voice that is always right. It invites a question: what do I keep making room for, and what do I sustain only from habit? Some things ripen, some stay unfinished, and some become compost for another beginning.'),
      shadow:pair('Rozlišování se může změnit v odsuzování sebe nebo druhého. Dokážu pojmenovat hranici tak, aby chránila život a nepotřebovala trestat?','Discernment can become condemnation of yourself or another. Can I name a boundary that protects life without needing to punish?'),
      question:pair('Co si chci ponechat a co už nemusím nést stejným způsobem?','What do I want to keep, and what need I no longer carry in the same way?'),
      ritual:pair('Pojmenuj jednu věc, za kterou děkuješ, jednu, která potřebuje změnu, a jeden malý čin do příštího týdne. Pokud jste dva, mluvte každý za sebe.','Name one thing you appreciate, one that needs change and one small action for the next week. If there are two of you, each speaks for themselves.'),
      storyTitle:pair('Spirála místo návratu na začátek','A spiral rather than a return to zero'),
      story:pair('Autorský obraz: cesta se vrací ke stejnému stromu, ale člověk přichází s jinou zkušeností. „Božská spirála“ tu pojmenovává možnost návratu bez vymazání toho, co jsme se naučili. Žádná fáze není vyšší. Hloubka vzniká tím, že příště rozpoznáme o kousek dříve, co potřebuje péči.','An original image: the path returns to the same tree, but the traveller brings different experience. “Divine spiral” names a return that does not erase what we learned. No phase ranks higher. Depth grows when, next time, we recognise a little sooner what needs care.'),source:null},
    shared:pair('Klidné ohlédnutí a jedna malá změna','A quiet reflection and one small change')
  }
};

export function resolveCycleExploration(phase,date,exploration){
  const current=CYCLE_ORDER.includes(phase?.id)?phase.id:null;
  const manual=exploration?.date===date&&exploration?.current===current&&CYCLE_ORDER.includes(exploration.id)?exploration.id:null;
  return {current,shown:manual||current,exploring:Boolean(manual&&manual!==current)};
}

export const CYCLE_MAP_LAYERS={care:pair('Každý den','Everyday care'),body:pair('V těle','In the body'),symbol:pair('V obrazech','In images')};
const patternText=pair('Hormony a nervový systém spolu souvisejí, ale stejná fáze nemusí přinášet stejný prožitek. U PMS a PMDD může hrát roli citlivost na běžné hormonální změny. Zkus sledovat spánek, potíže, náladu a to, co opravdu pomohlo, alespoň přes dva cykly. Dnešní pocit si nemusíš vysvětlit jedinou příčinou.','Hormones and the nervous system interact, but the same phase need not bring the same experience. Sensitivity to ordinary hormonal changes can play a role in PMS and PMDD. Track sleep, symptoms, mood and what actually helped across at least two cycles. You need not explain today’s feeling by a single cause.');
const spiralText=pair('Spirála je tady obraz návratu s novou zkušeností. Stejná potřeba se může objevit znovu, ale už ji nemusím přehlédnout stejným způsobem. „Božská“ může znamenat úctu k životu, ne tvrzení o biologickém zákonu. Vyber si jeden drobný poznatek, který si chceš vzít do dalšího obratu.','The spiral is an image of returning with new experience. The same need may return, but I need not overlook it in the same way. “Divine” can mean reverence for life, not a biological law. Choose one small understanding to carry into the next turn.');

// This is a navigation tree over the existing editorial, not another source of
// phase estimates. Unknown days have no implicit phase, even inside the map.
export function cycleMapTopics(phaseId,layer='care',role='client'){
  const guide=CYCLE_DEPTH[phaseId];if(!guide)return [];
  const partner=role==='coach';
  if(layer==='body')return [
    {id:'overview',label:pair('Souvislosti','Overview'),title:pair('Tělo v této fázi','The body in this phase'),paragraphs:[guide.hormones,guide.uterus]},
    {id:'hormones',label:pair('Hormony','Hormones'),title:pair('Čtyři propojené signály','Four connected signals'),paragraphs:[guide.hormones]},
    {id:'uterus',label:pair('Děloha','Uterus'),title:pair('Co se děje v děloze','What happens in the uterus'),paragraphs:[guide.uterus]},
    {id:'pattern',label:pair('Vlastní vzorec','Your pattern'),title:pair('Tělo, nálada a vlastní vzorec','Body, mood and your own pattern'),paragraphs:[patternText]}
  ];
  if(layer==='symbol')return [
    {id:'overview',label:pair('Souvislosti','Overview'),title:guide.symbol.archetype,paragraphs:[guide.symbol.text],question:guide.symbol.question,correspondences:guide.symbol},
    {id:'archetype',label:pair('Archetyp','Archetype'),title:guide.symbol.archetype,paragraphs:[guide.symbol.text],question:guide.symbol.question,correspondences:guide.symbol},
    {id:'shadow',label:pair('Pod obrazem','Beneath'),title:pair('Co se může skrývat pod obrazem','What may hide beneath the image'),paragraphs:[guide.symbol.shadow,partner?pair('Zkus tento obraz vztáhnout nejprve k sobě. Potom se zeptej, co v něm nachází ona. Není to návod, jak ji pojmenovat.','Apply the image to yourself first. Then ask what she finds in it. It is not a way to label her.'):pair('Která část obrazu je mi blízká a která mi nesedí? Obojí je užitečná odpověď.','Which part of this image feels close, and which does not fit? Both are useful answers.')]},
    {id:'story',label:pair('Příběh','Story'),title:guide.symbol.storyTitle,paragraphs:[guide.symbol.story]},
    {id:'ritual',label:pair('Malý rituál','Small ritual'),title:pair('Přenést obraz do dne','Bring the image into your day'),paragraphs:[guide.symbol.ritual]},
    {id:'spiral',label:pair('Božská spirála','Divine spiral'),title:pair('Božská spirála','The divine spiral'),paragraphs:[spiralText]}
  ];
  return [
    {id:'overview',label:pair('Souvislosti','Overview'),title:guide.title,paragraphs:[partner?guide.partner:guide.woman]},
    ...guide.care.map(item=>({id:item.id,label:({move:pair('Pohyb','Movement'),food:pair('Jídlo','Food'),mind:pair('Psychika','Feelings'),plan:pair('Plány','Plans'),bond:pair('Blízkost','Closeness')})[item.id],title:item.name,paragraphs:[partner?item.partner:item.woman]})),
    {id:'shared',label:pair('Chvíle spolu','Together'),title:pair('Jedna chvíle spolu','One moment together'),paragraphs:[guide.shared],plan:guide.shared}
  ];
}

export function cycleMapSelection(phaseId,layer,topicId,role='client'){
  const topics=cycleMapTopics(phaseId,layer,role);
  return {topics,topic:topics.find(topic=>topic.id===topicId)||topics[0]||null};
}

// Teaching curves are authored shapes, not sampled clinical measurements.
// Each series has its own maximum of 1; heights cannot compare concentrations.
export function cycleHormoneSchematic(steps=120){
  const n=Number.isInteger(steps)?Math.max(24,Math.min(360,steps)):120;
  const bell=(x,c,w)=>Math.exp(-.5*((x-c)/w)**2);
  const rows=Array.from({length:n+1},(_,i)=>{const x=i/n;return {x,e2:.09+.86*bell(x,.42,.085)+.49*bell(x,.76,.105),p4:.04+.94*bell(x,.75,.11),lh:.06+.94*bell(x,.49,.025),fsh:.13+.24*bell(x,.045,.085)+.34*bell(x,.49,.04)+.15*bell(x,1,.07)};});
  const peaks=Object.fromEntries(['e2','p4','lh','fsh'].map(key=>[key,Math.max(...rows.map(row=>row[key]))]));
  return rows.map(row=>({...row,...Object.fromEntries(Object.keys(peaks).map(key=>[key,row[key]/peaks[key]]))}));
}

export const CYCLE_HORMONES=[
  {id:'e2',name:pair('Estradiol','Estradiol'),short:'E2',dash:'',description:pair('Estrogen tvořený hlavně ve vaječníku. Podporuje růst sliznice; před ovulací stoupá a v luteální fázi má menší druhou vlnu.','An oestrogen produced mainly in the ovary. Supports lining growth; rises before ovulation with a smaller second wave in the luteal phase.')},
  {id:'p4',name:pair('Progesteron','Progesterone'),short:'P4',dash:'8 4',description:pair('Po ovulaci ho vytváří žluté tělísko. Připravuje sliznici k sekreční činnosti. Bez pokračujícího těhotenství jeho hladina ke konci cyklu klesá.','Produced by the corpus luteum after ovulation. Prepares the lining for secretory activity. Without a continuing pregnancy, its level falls near the cycle end.')},
  {id:'lh',name:pair('Luteinizační hormon','Luteinising hormone'),short:'LH',dash:'2 4',description:pair('Signál z hypofýzy. Jeho výrazná předovulační vlna spouští děje vedoucí k ovulaci; křivka je pouze schéma.','A pituitary signal. Its pronounced preovulatory surge triggers events leading to ovulation; the curve is only a diagram.')},
  {id:'fsh',name:pair('Folikuly stimulující hormon','Follicle-stimulating hormone'),short:'FSH',dash:'10 3 2 3',description:pair('Signál z hypofýzy, který podporuje růst folikulů. Na hranici cyklů se zvyšuje a má i menší předovulační vlnu.','A pituitary signal supporting follicle growth. Rises around the cycle boundary and has a smaller preovulatory wave.')}
];

export const CYCLE_DEPTH_SOURCES=[
  {id:'physiology',title:'Reed & Carr · Endotext',url:'https://www.endotext.org/wp-content/uploads/pdfs/the-normal-menstrual-cycle-and-the-control-of-ovulation.pdf'},
  {id:'owh',title:'Office on Women’s Health · Your menstrual cycle',url:'https://womenshealth.gov/menstrual-cycle/your-menstrual-cycle'},
  {id:'pms',title:'NHS · PMS',url:'https://www.nhs.uk/conditions/pre-menstrual-syndrome/'},
  {id:'pain',title:'NHS · Period pain',url:'https://www.nhs.uk/symptoms/period-pain/'},
  {id:'movement',title:'McNulty et al. · Cycle and exercise performance',url:'https://link.springer.com/article/10.1007/s40279-020-01319-3'},
  {id:'mind',title:'NIMH · Hormone sensitivity and PMDD',url:'https://www.nimh.nih.gov/research/research-conducted-at-nimh/research-areas/clinics-and-labs/sbe/participate-in-research/premenstrual-dysphoric-disorder'},
  {id:'demeter',title:'Homeric Hymn to Demeter · CHS, Harvard',url:'https://chs.harvard.edu/primary-source/homeric-hymn-to-demeter-sb/'},
  {id:'inana',title:'Inana’s descent · ETCSL, Oxford',url:'https://etcsl.orinst.ox.ac.uk/section1/tr141.htm'}
];
