// Original editorial. Traditional vocabulary is identified separately from
// contemporary contemplative readings; none of these passages predicts events.
export const ASTRO_PLANETS={
  Sun:{symbol:"☉",name:["Slunce","Sun"],vedic:"Súrja",theme:["Střed a vědomý směr","Centre and conscious direction"],
    text:["Slunce v symbolickém horoskopu drží střed. Není to jen vůle prosadit se, ale schopnost stát za tím, čemu dáváš život. Jeho světlo odhaluje rozdíl mezi tím, co tě vyživuje, a tím, čím si pouze udržuješ obraz o sobě.","The symbolic Sun holds a centre: the capacity to stand behind what you bring to life. Its light distinguishes what nourishes you from what merely maintains your self-image."],
    shadow:["Stínem středu je přesvědčení, že všechno musí obíhat kolem něj. Zralá síla dovoluje ostatním zářit bez toho, aby se zmenšila.","The shadow of a centre is the belief that everything must revolve around it. Mature strength allows others to shine without diminishing itself."]},
  Moon:{symbol:"☽",name:["Měsíc","Moon"],vedic:"Čandra",theme:["Paměť těla a proměnlivost","Bodily memory and change"],
    text:["Měsíc patří rytmu, přijímání a paměti. Jeho symbolika se dotýká toho, co se v nás ozve ještě před vysvětlením: známého bezpečí, neklidu, hladu po blízkosti. Proměna jeho světla připomíná, že celistvost nemusí být pořád celá vidět.","The Moon belongs to rhythm, receptivity and memory: what responds before explanations arrive, familiar safety, unease, hunger for closeness. Its changing light suggests that wholeness need not always be entirely visible."],
    shadow:["Pocit může být pravdivou zprávou o tvém prožívání a přesto nemusí přesně popisovat druhého člověka. Péče začíná rozlišením těchto dvou věcí.","A feeling can truthfully describe your experience without accurately describing another person. Care begins by distinguishing the two."]},
  Mercury:{symbol:"☿",name:["Merkur","Mercury"],vedic:"Budha",theme:["Posel mezi světy","Messenger between worlds"],
    text:["Merkur propojuje to, co ještě nemá společný jazyk. Je průvodcem přes práh mezi tušením a slovem, zkušeností a pochopením. Jeho obratnost nespočívá jen v rychlosti myšlení, ale i ve schopnosti změnit pohled, když se objeví něco živějšího než původní vysvětlení.","Mercury moves between intuition and speech, experience and understanding. Its agility is not merely quick thinking but the willingness to change perspective when something more alive than the original explanation emerges."],
    shadow:["Slovo může spojovat i chránit před skutečným setkáním. Všímej si rozdílu mezi pochopením a potřebou mít poslední slovo.","Words can connect us or protect us from meeting. Notice the difference between understanding and needing the final word."]},
  Venus:{symbol:"♀",name:["Venuše","Venus"],vedic:"Šukra",theme:["Hodnota, přitažlivost a soulad","Value, attraction and accord"],
    text:["Venuše pojmenovává, čemu říkáme ano. Kráse, potěšení, vztahu, ale také ceně, kterou za soulad platíme. Její hlubší vrstva není být oblíbený: je to cit pro hodnotu, který dovoluje volit blízkost svobodně, nikoli ze strachu ze ztráty.","Venus names what we say yes to: beauty, pleasure, relationship, and the price we pay for harmony. Its deeper layer is a sense of value that lets closeness be chosen freely rather than from fear of loss."],
    shadow:["Pokoj za cenu nevyřčené pravdy bývá křehký. Jemnost může nést jasnou hranici; nemusí ji rozpouštět.","Peace bought with unspoken truth is fragile. Gentleness can carry a clear boundary rather than dissolve it."]},
  Mars:{symbol:"♂",name:["Mars","Mars"],vedic:"Mangala",theme:["Síla vykročit a rozlišit","The force to act and distinguish"],
    text:["Mars je řez, který oddělí záměr od nekonečného váhání. Patří mu odvaha, obrana i schopnost říct dost. Vědomá marsovská síla nemusí vítězit nad člověkem před tebou. Může chránit něco křehkého, co bez rozhodného činu nemá prostor.","Mars is the cut that separates intention from endless hesitation. Courage, defence and enough belong here. Conscious force can protect something vulnerable rather than defeat the person in front of you."],
    shadow:["Naléhavost není totéž co jasnost. Hněv může ukázat překročenou hranici; podobu odpovědi si přesto vybíráš.","Urgency is not clarity. Anger may point to a crossed boundary; you still choose the form of your response."]},
  Jupiter:{symbol:"♃",name:["Jupiter","Jupiter"],vedic:"Guru",theme:["Smysl a šíře pohledu","Meaning and breadth of vision"],
    text:["Jupiter otevírá prostor, v němž jednotlivá zkušenost patří do většího příběhu. Je symbolem důvěry, učení a štědrosti. Jeho otázka není jen kam růst, ale čemu takový růst slouží a koho do něj dokážeš zahrnout.","Jupiter opens the space in which one experience belongs to a larger story. It symbolises trust, learning and generosity, asking what expansion serves and whom it can include."],
    shadow:["Velký příběh může přerůst skutečnost. Důvěra zraje tam, kde snese i nevědění a konkrétní odpovědnost.","A grand story can outgrow reality. Trust matures when it can accommodate uncertainty and concrete responsibility."]},
  Saturn:{symbol:"♄",name:["Saturn","Saturn"],vedic:"Šani",theme:["Čas, hranice a věrnost","Time, boundaries and fidelity"],
    text:["Saturn připomíná, že tvar vzniká také omezením. Čas, který není nekonečný, dává váhu rozhodnutí. V jeho symbolice se setkává strach ze selhání se schopností zůstávat: unést postupnost, nést důsledky a dát slibu opakovanou skutečnou podobu.","Saturn reminds us that form also comes through limitation. Finite time gives choices weight. Fear of failure meets the capacity to remain, to bear consequences and repeatedly give a promise actual form."],
    shadow:["Kázeň může být péčí, nebo trestem, který sis osvojil/a. Pevná struktura má podpírat život, ne dokazovat tvoji hodnotu.","Discipline can be care or an inherited punishment. A sound structure supports life; it need not prove your worth."]},
  Uranus:{symbol:"♅",name:["Uran","Uranus"],vedic:null,theme:["Probuzení a přerušení vzorce","Awakening and interruption"],
    text:["V moderní astrologické řeči Uran ztělesňuje okamžik, kdy staré vysvětlení přestane stačit. Otevírá nezvyklou možnost a požadavek svobody. Je pomalý: jeho znamení je společným kulturním pozadím mnoha lidí, nikoli dnešní osobní zprávou.","In modern astrology Uranus symbolises the moment an old explanation stops being enough. It opens unusual possibilities and a claim to freedom. Its slow sign placement is collective background, not a personal daily message."],
    shadow:["Být jiný není samo o sobě osvobození. Skutečná změna potřebuje i schopnost žít následky nově zvolené cesty.","Being different is not liberation by itself. Real change also means living the consequences of the new path."]},
  Neptune:{symbol:"♆",name:["Neptun","Neptune"],vedic:null,theme:["Průzračnost a rozpuštění hranic","Porosity and dissolving boundaries"],
    text:["Neptun je v moderní symbolice oceán, v němž se oddělené tvary na chvíli rozpustí. Patří sem obraz, sen, soucit i touha po přesahu. Jeho pomalý pohyb popisuje dlouhé společné motivy; jemnost obrazu není důkazem jeho doslovné pravdivosti.","Modern Neptune is the ocean in which separate forms briefly dissolve: image, dream, compassion and longing for transcendence. Its slow motion belongs to long collective themes; a subtle image is not evidence of literal truth."],
    shadow:["Soucit bez rozlišení se může změnit v záchranu druhého proti jeho vůli. Odevzdání potřebuje vědomou volbu, ne ztrátu vlastního hlasu.","Compassion without discernment can become rescuing someone against their will. Surrender needs conscious choice, not the loss of your own voice."]},
  Pluto:{symbol:"♇",name:["Pluto","Pluto"],vedic:null,theme:["Kořen, moc a proměna","Roots, power and transformation"],
    text:["Pluto v moderní astrologii obrací pohled pod povrch: k tomu, co držíme silou, čeho se bojíme pustit a co se ztrácí pod přijatelným příběhem. Jde o pomalou generační symboliku. Hloubka není intenzita za každou cenu, ale ochota setrvat u pravdy bez nátlaku.","Modern Pluto looks beneath the surface: what we grip, fear releasing, or hide under an acceptable story. This is slow generational symbolism. Depth means staying with truth without coercion, not intensity at any cost."],
    shadow:["Proměnu nelze vynutit u sebe ani u druhého. Když něco končí, může být důstojným činem přestat to ovládat.","Transformation cannot be forced in yourself or another. When something ends, relinquishing control can be an act of dignity."]}
};
export const ASTRO_SIGNS=[
  {symbol:"♈",mode:0,text:["Oheň Berana míří k prvnímu pravdivému pohybu. Tato část kruhu zkoumá, jak jednat přímo a přitom nezaměnit odvahu za tlak. Začátek ještě nemusí znát celý příběh.","Aries fire moves towards a first honest action. It explores directness without mistaking courage for pressure. A beginning need not know the whole story."]},
  {symbol:"♉",mode:1,text:["Země Býka dává zkušenosti tělo a čas. Hodnota se poznává tím, co skutečně vyživuje a co lze opakovaně unést. Stálost zraje, když umí být oporou i bez křečovitého držení.","Taurus earth gives experience a body and time. Value appears in what nourishes and can be sustained. Stability matures when support need not become a tight grip."]},
  {symbol:"♊",mode:2,text:["Vzduch Blíženců otevírá více oken do stejné skutečnosti. Pohyb mezi pohledy může přinést svobodu; roztříštěnost přichází, když už žádnému z nich nevěnujeme celou pozornost.","Gemini air opens several windows onto one reality. Moving between perspectives can free us; fragmentation arrives when none receives full attention."]},
  {symbol:"♋",mode:0,text:["Voda Raka hledá prostor, kde lze povolit obranu. Paměť, domov a péče zde nejsou minulostí, ale živým způsobem přijímání. Ochrana má umožnit růst, ne zabránit odchodu.","Cancer water seeks room to lower defences. Memory, home and care are living ways of receiving. Protection can enable growth rather than prevent departure."]},
  {symbol:"♌",mode:1,text:["Oheň Lva chce dát vnitřnímu životu viditelný tvar. Tvořivost je zde ochotou něco odhalit a podepsat se pod to. Zářit neznamená být pořád sledován/a.","Leo fire gives inner life visible form. Creativity means revealing something and standing behind it. Shining need not mean being watched all the time."]},
  {symbol:"♍",mode:2,text:["Země Panny rozlišuje, co potřebuje péči a co už jen další kontrolu. Malá přesná změna může sloužit celku. Dokonalost naopak někdy oddaluje kontakt s tím, co už žije.","Virgo earth distinguishes what needs care from what merely invites more control. A small precise change can serve the whole. Perfection may postpone contact with what is already alive."]},
  {symbol:"♎",mode:0,text:["Vzduch Vah poznává sebe také skrze setkání. Rovnováha není pevný bod, ale živé vyjednávání mezi dvěma pravdami. Krása vztahu unese i rozdíl, který nezmizí.","Libra air meets itself through encounter. Balance is living negotiation between two truths. The beauty of a relationship can contain differences that remain."]},
  {symbol:"♏",mode:1,text:["Voda Štíra sestupuje tam, kde už povrchní souhlas nestačí. Intimita, důvěra a moc zde žádají poctivost. Hloubka začíná svolením, nikoli právem proniknout do druhého.","Scorpio water descends where surface agreement is insufficient. Intimacy, trust and power call for honesty. Depth begins with consent, not entitlement to penetrate another."]},
  {symbol:"♐",mode:2,text:["Oheň Střelce spojuje cestu s otázkou smyslu. Odvaha překročit známý obzor může rozšířit život. Zralý směr však nepotřebuje proměnit vlastní přesvědčení v pravdu pro všechny.","Sagittarius fire connects a journey with meaning. Crossing a familiar horizon can widen life. A mature direction need not turn one conviction into everyone's truth."]},
  {symbol:"♑",mode:0,text:["Země Kozoroha převádí záměr do tvaru, který obstojí v čase. Učí se nést odpovědnost bez tvrdosti k vlastní zranitelnosti. Dosažený vrchol nemá být jediným místem, kde smíš odpočívat.","Capricorn earth turns intention into a form that endures. Responsibility can coexist with vulnerability. The summit need not be the only place where rest is allowed."]},
  {symbol:"♒",mode:1,text:["Vzduch Vodnáře hledí na život z odstupu a ptá se, jak může fungovat jinak. Svoboda i společenství potřebují prostor pro odlišnost. Velká idea nesmí ztratit člověka, kterého se týká.","Aquarius air steps back to see how life could work differently. Freedom and community both need room for difference. A large idea must not lose the person it concerns."]},
  {symbol:"♓",mode:2,text:["Voda Ryb připomíná prostupnost všeho živého. Citlivost a imaginace dovolují vnímat souvislosti, které nelze sevřít pojmem. Soucit zůstává svobodný, když má také břehy.","Pisces water recalls life's permeability. Sensitivity and imagination perceive connections beyond concepts. Compassion remains free when it also has shores."]}
];
export const ASTRO_ELEMENTS=[["Oheň","Fire"],["Země","Earth"],["Vzduch","Air"],["Voda","Water"]];
export const ASTRO_MODES=[["Počínající","Cardinal"],["Udržující","Fixed"],["Proměnlivé","Mutable"]];
export const ASTRO_ASPECTS={
  conjunction:{name:["Konjunkce","Conjunction"],text:["Dva principy stojí v témže směru. Jejich témata se v symbolickém čtení prolínají, takže může být obtížnější rozeznat jeden od druhého. Síla vzniká ze spojení, jasnost z rozlišení.","Two principles point in the same direction. Their themes merge symbolically, making them harder to distinguish. Union gives strength; discernment gives clarity."]},
  sextile:{name:["Sextil","Sextile"],text:["Šedesát stupňů spojuje odlišné, ale spolupracující části kruhu. Tradičně jde o podpůrné spojení; v našem čtení o možnost, které je potřeba vyjít vstříc. Potenciál se sám nepromění v čin.","Sixty degrees links different but cooperative parts of the circle. Traditionally supportive, it can be read as an opening that needs participation. Potential does not turn itself into action."]},
  square:{name:["Kvadratura","Square"],text:["Pravý úhel ponechává oba principy v napětí. Jeden nelze vyřešit prostým popřením druhého. Tvůrčí odpověď hledá nový způsob, jak dát místo oběma, nikoli vítěze jejich sporu.","A right angle holds two principles in tension. One cannot be resolved by denying the other. A creative response makes room for both rather than choosing a winner."]},
  trine:{name:["Trigon","Trine"],text:["Sto dvacet stupňů propojuje znamení stejného živlu. Symbolicky je tu snazší proudění a společný jazyk. To, co jde samo, může nést dar i zůstat nepovšimnuté; vědomé užití mu dává hloubku.","One hundred and twenty degrees links signs of the same element. Symbolically there is flow and a shared language. What comes easily can be a gift or remain unnoticed; conscious use gives it depth."]},
  opposition:{name:["Opozice","Opposition"],text:["Dva póly leží naproti sobě. Obraz může připomínat vlastní část, kterou snáze vidíme u druhých. Integrace nevyžaduje splynutí: dovoluje oběma pólům zůstat odlišné a přesto patřit do celku.","Two poles face each other. The image can evoke a part of ourselves more easily seen in others. Integration need not merge them; both can stay different while belonging to a whole."]}
};
export const ASTRO_DIGNITIES={
  domicile:{name:["Ve vlastním znamení","In domicile"],text:["Planeta je v tradičním systému hostitelem tohoto znamení. Mluví vlastním jazykem a její princip má jasné prostředky. To není záruka příjemného výsledku; i dobře vybavená síla potřebuje zralé zacházení.","The planet hosts this sign in the traditional system. It speaks its own language and has clear resources. That does not guarantee pleasant outcomes; a well-equipped force still needs mature use."]},
  exaltation:{name:["V povýšení","In exaltation"],text:["Tradiční obraz čestného hosta: princip planety zde získává význačné místo. Povýšení je specifická důstojnost, ne obecné hodnocení dobrého dne ani člověka.","The traditional image of an honoured guest: the planet's principle receives a prominent place. Exaltation is a specific dignity, not a rating of a good day or person."]},
  detriment:{name:["Naproti vlastnímu znamení","Opposite its domicile"],text:["Planeta působí v prostředí, jehož jazyk není její vlastní. Starší astrologie to nazývá exilem. Jako kontemplativní obraz to otevírá učení skrze rozdíl, nikoli soud o slabosti nebo smůle.","The planet works in a setting whose language is not its own, traditionally called detriment. As a contemplative image this suggests learning through difference, not a judgement of weakness or bad luck."]},
  fall:{name:["V pádu","In fall"],text:["Znamení leží naproti místu tradičního povýšení. Název patří historické technice, ne hodnotě člověka. Obraz se dá číst jako potřeba najít vlastní tvar síly bez opory ve známé roli.","The sign lies opposite the planet's traditional exaltation. The term belongs to a historical technique, not human worth. It can evoke finding a form of strength without a familiar role."]},
  guest:{name:["V hostujícím znamení","In a host's sign"],text:["Zde sledujeme vládce znamení jako hostitele. Ukazuje další článek symbolického příběhu: v jakém prostředí se může princip této planety projevit. Ostatní tradiční důstojnosti tato vrstva nevyhodnocuje.","Here the sign's ruler acts as host and another link in the symbolic story. This layer does not evaluate other traditional dignities."]}
};
export const ASTRO_LENSES={
  western:{name:["Západní","Western"],subtitle:["Tropický zvěrokruh","Tropical zodiac"],text:["Dvanáct znamení se odvíjí od jarního bodu. Moderní výklad pracuje také s Uranem, Neptunem a Plutem a čte planetární obrazy jako jazyk vnitřních procesů. Zobrazené vazby jsou úhlové aspekty s rozpětím do 4°.","Twelve signs start at the vernal equinox. Modern interpretation also includes Uranus, Neptune and Pluto, reading planetary images as a language of inner processes. Connections shown are angular aspects within a 4° orb."]},
  hellenistic:{name:["Helénistický","Hellenistic"],subtitle:["Sedm světel, vládci a znamení","Seven lights, rulers and signs"],text:["Tropický kruh zůstává stejný; mění se způsob čtení. Sedm tradičních planet, jejich domicíly a povýšení vytvářejí síť hostitelů. Aspekty v grafu spojují celá znamení. Zrození, ascendent, domy ani denní a noční sektu z těchto údajů neurčujeme.","The tropical circle stays the same; the reading changes. Seven traditional planets, domiciles and exaltations form a network of hosts. Chart aspects connect whole signs. This information does not establish birth, ascendant, houses or day/night sect."]},
  jyotish:{name:["Džjótiša","Jyotisha"],subtitle:["Siderická Čitrá, nakšatra a tithi","Sidereal Chitra, nakshatra and tithi"],text:["Hvězdný rámec zde ukotvuje Spicu, sanskrtskou Čitru, na začátku Vah. Od tropických poloh se odečítá vypočtená ajanámša. Vedle znamení čteme lunární stanici a tithi, jinou míru času. Používáme Čitrá pakša, nikoli tabulkovou Lahiri; blízko hranic se výsledky mohou lišit.","This stellar frame anchors Spica, Sanskrit Chitra, at the beginning of Libra. A calculated ayanamsa is subtracted from tropical positions. We also read the lunar mansion and tithi, another measure of time. This is Chitra Paksha, not tabulated Lahiri; boundary results may differ."]}
};
export const ASTRO_SOURCES=[
  ["Astronomy Engine · souřadnice, precese a fáze", "https://github.com/cosinekitty/astronomy/blob/master/source/js/README.md"],
  ["SIMBAD · Spica, souřadnice a vlastní pohyb", "https://simbad.cds.unistra.fr/simbad/sim-basic?Ident=Spica"],
  ["Astrodienst · rozdíly mezi ajanámšami", "https://www.astro.com/astrology/in_ayanamsha_e.htm"],
  ["Ptolemaios · Tetrabiblos I.4–24", "https://penelope.uchicago.edu/Thayer/E/Roman/Texts/Ptolemy/Tetrabiblos/1B*.html"],
  ["Varáhamihira · Brihat džátaka II.1, planetární symbolika", "https://www.wisdomlib.org/hinduism/book/brihat-jataka-by-varahamihira-sanskrit-english/d/doc1501584.html"],
  ["Varáhamihira · Brihat džátaka I.13, povýšení a oslabení", "https://www.wisdomlib.org/hinduism/book/brihat-jataka-by-varahamihira-sanskrit-english/d/doc1501576.html"],
  ["Súrja siddhánta · XIV, měření času", "https://www.swaveda.com/texts/surya-siddhanta/14/"],
  ["Súrja siddhánta · II, polohy a lunární úseky", "https://www.swaveda.com/texts/surya-siddhanta/2/"]
];
export const JYOTISH_READINGS={
  Sun:["Súrja je v indickém symbolickém slovníku spojen se světlem vědomí, autoritou a životní orientací. Gráha znamená uchopující princip: tento jazyk se ptá, co drží naši pozornost a k čemu ji obrací. Zde jde o obraz společné oblohy, nikoli určení osobního átmakáraky.","Surya is associated with the light of consciousness, authority and life's orientation. Graha suggests a grasping principle: what holds attention and where it turns it. This is a common-sky image, not a personal atmakaraka calculation."],
  Moon:["Čandra nese v džjótiše zvláštní význam pro mysl, vnímání a rytmus. Její polohu proto čteme také ve 27 nakšatrách. Raši dává širší třicetistupňové pole; nakšatra rozlišuje jemnější úsek a páda jeho čtvrtinu. Jsou to různé vrstvy téže polohy, ne různé planety.","Chandra carries particular importance for mind, perception and rhythm. Its position is also read through 27 nakshatras. Rashi gives a thirty-degree field; nakshatra distinguishes a finer sector and pada its quarter. These are layers of one position."],
  Mercury:["Budha symbolizuje rozlišování, řeč a schopnost učit se. V této vrstvě se neptáme, jak rychle přichází myšlenky, ale jak se z poznatku stává skutečné porozumění. Proměnlivost není nedostatek: může být ochotou opravit vlastní výklad.","Budha symbolises discernment, speech and learning. This layer asks how information becomes understanding. Adaptability can be the willingness to revise one's own interpretation."],
  Venus:["Šukra je spojen s potěšením, krásou a schopností ocenit život v jeho smyslové podobě. Indický obraz učitele asurů se nedá ztotožnit pouze s římskou bohyní lásky. Otevírá i rozdíl mezi přitažlivostí, znalostí a tím, čemu nakonec dáme svou věrnost.","Shukra is associated with pleasure, beauty and appreciation of embodied life. The Indian image of the teacher of asuras is not identical with the Roman goddess of love. It also opens questions of attraction, knowledge and allegiance."],
  Mars:["Mangala představuje rozhodnost, odvahu a sílu chránit. V symbolické praxi je možné tuto sílu číst jako schopnost dokončit čin a nést jeho důsledky. Samotnou polohou na dnešní obloze se neurčuje osobní mangala dóša ani partnerská vhodnost.","Mangala represents resolve, courage and protective strength. Symbolically this can mean completing an action and bearing its consequences. Today's sky alone does not establish personal mangala dosha or compatibility."],
  Jupiter:["Guru znamená učitel. Jupiterova symbolika tak míří ke vztahu mezi věděním, důvěrou a moudrostí, která mění jednání. Rozdíl mezi názorem a žitou orientací se ukáže teprve tehdy, když poznání něco stojí.","Guru means teacher. Jupiter's symbolism concerns knowledge, trust and wisdom that changes conduct. The difference between an opinion and a lived orientation emerges when understanding asks something of us."],
  Saturn:["Šani v sobě nese pomalost a váhu času. Jeho obraz se dotýká trpělivosti, následků a práce, kterou nelze přeskočit. V našem kontemplativním čtení není karma trestem za minulost, ale pozorností k tomu, co opakovanými činy dál vytváříme.","Shani carries slowness and the weight of time: patience, consequences and work that cannot be skipped. In our contemplative reading, karma is attention to what repeated actions continue to create, not a punishment narrative."]
};
